### ISSUE TITLE
Simple way to get valid faked enity-objects without writing in DB

### ISSUE THREAD

**Issue by brud** [fzaninotto/Faker#1001]
Hi, i try to make generator for [Eris](https://github.com/giorgiosironi/eris) by using ` $entities = $populator->execute(); `for property-based **unit** tests. 

For now $populator->execute() makes flush on entity manager, and because of that my tests are **functional** (cover business logic and DB stuff).

Is this real to make flush in populator by argument (like a `$populator->execute($store = true)`)?

**Comment by fzaninotto** [comment]
You might want to look at https://github.com/nelmio/alice
