### ISSUE TITLE
Unknown formatter vat

### ISSUE THREAD

**Issue by christiancannata** [fzaninotto/Faker#1020]
Doesn't find vatId() formatter! 

$faker = new \Faker\Generator();
        $faker->addProvider(new \Faker\Provider\en_US\Person($faker));
        $faker->addProvider(new \Faker\Provider\en_US\Address($faker));
        $faker->addProvider(new \Faker\Provider\en_US\PhoneNumber($faker));
        $faker->addProvider(new \Faker\Provider\Payment($faker));
        $faker->addProvider(new \Faker\Provider\Lorem($faker));
        $faker->addProvider(new \Faker\Provider\Internet($faker));
        $faker->addProvider(new \Faker\Provider\Company($faker));
        $faker->addProvider(new \Faker\Provider\it_IT\Company($faker));

        $type="CARRIER";

        for ($i = 0; $i < 2; $i++) {
            $company = new Company();
            $company->setName($faker->company);
            $company->setEmail($faker->email);
            $company->setWebsite($faker->url);
            $company->setVat($faker->vatId());

            $company->setCreatedAt(new \DateTime());
            $company->setUpdatedAt(new \DateTime());
            $company->setType($type);
            $manager->persist($company);

        }

 [InvalidArgumentException]  
  Unknown formatter "vat"

**Comment by David-Vander-Elst** [comment]
same issue here... any solution?

**Comment by christiancannata** [comment]
I have resolved, because there was an older version of faker in a dependency package!

**Comment by David-Vander-Elst** [comment]
Hello Thank you christian.

I updated package via composer but the problem persist.

Any idea?

**Comment by christiancannata** [comment]
You could see if you have a package in composer.json that has fzaninotto/Faker as dependency, if composer download the package with faker dependency, It will ignore your fzaninotto/Faker in composer.json

I have "fzaninotto/faker":"dev-master" in composer json and I have found the package that has an older version of fzaninotto/faker

**Comment by David-Vander-Elst** [comment]
it's fixed, thank you for your reactivity;

**Comment by Kyslik** [comment]
Hmm I just hit this problem:

```
Psy Shell v0.9.4 (PHP 7.1.14 — cli) by Justin Hileman
>>> (Faker\Factory::create())->vat
InvalidArgumentException with message 'Unknown formatter "vat"'
>>>
```

Any hints?

**Comment by MaxChu23** [comment]
@Kyslik It could be because of locale that was initially. For example, for pt_PT vat function is `$faker->taxpayerIdentificationNumber;`

**Comment by wixys** [comment]
Hi there,

I took the functions that I need from Faker\Provider\ar_SA\Person and put in the Faker\Provider\en_US\Person, fixed!
