### ISSUE TITLE
Faker should take male last name and male first name

### ISSUE THREAD

**Issue by piotrooo** [fzaninotto/Faker#1022]
In polish language male or female last name in specific examples match only to male or female e.g.:

`Błażej Grabowska` isn't correct polish name. Should be `Błażej Grabowski`.

So if I not define male or female name rand element should return both random elements (first name and last name) for the same gender.

```
$firstName = $faker->firstName; //random element for male
$lastName = $faker->lastName; //random element for male too
```

**Comment by fzaninotto** [comment]
Formatters are independent of one another. This logic should go into a `fullName` formatter.
