### ISSUE TITLE
Define phone format

### ISSUE THREAD

**Issue by piotrooo** [fzaninotto/Faker#1023]
`PhoneNumber` provider should have method for generate phone number for specific format (declared in field `$formats`).

E.g.:

```
public function phoneNumberFor($format)
{
    //check if format exists, if not parse random
    return static::numerify($format)l;
}
```

PS. I know I can use `numerify` method but IMHO generate specific phone number format should be in `PhoneNumber` provider context.

**Comment by fzaninotto** [comment]
Nah, if you have a given format, use `numerify()`.
