### ISSUE TITLE
realText generate invalid looking text

### ISSUE THREAD

**Issue by gulaandrij** [fzaninotto/Faker#1024]
realText method can generate invalid text, with ',.' in the end, like this:

> Five, 'and I'll tell you his history,' As they walked off together. Alice was soon submitted to by all three to settle the question, and they all spoke at once, she found herself lying on the floor,.

**Comment by fzaninotto** [comment]
Fixed by #1025

**Comment by gulaandrij** [comment]
In Russian locale also can be generated invalid text like this "Еще я хотел вас попросить, чтобы эта сделка осталась между нами, по — ревизии как живые, — сказал Ноздрев. —."
