### ISSUE TITLE
Generator phpdoc missing mehods

### ISSUE THREAD

**Issue by piotrooo** [fzaninotto/Faker#1026]
I've question why in `Generator` class in the phpdocs not exists all methods e.g.: ` @method string name($gender = null)`, is any reason for this? I can make PR to fix this.

**Comment by fzaninotto** [comment]
The generator only contains phpdoc for formatters available in all locales. Locale-specific generators are not there - because that could be misleading. 

If you found a missing formatter that is generally available, please open a PR.
