### ISSUE TITLE
Polish county

### ISSUE THREAD

**Issue by piotrooo** [fzaninotto/Faker#1028]
This is only idea, to discuss.

In Poland we have something like county for each state. Currently number of counties are about 380. Maybe good idea will be generator for county? 
Describe:

```
$faker->county; //rand element for all of the defined counties
$faker->county($state = null); // if we pass state take random for state otherwise rand element for all the defined counties
```

**Comment by fzaninotto** [comment]
Good idea, feel free to add a formatter for that. Closing to keep the issues list manageable.
