### ISSUE TITLE
Faker DateTime bug?

### ISSUE THREAD

**Issue by XTRO123** [fzaninotto/Faker#1034]
Hi,
I just want to know, is it my mistake? I'm using PHP v7.0.9 on XAMPP (windows 10) and getting error:
![web](https://cloud.githubusercontent.com/assets/2737316/18618470/2853932c-7df0-11e6-821a-b3338e3ce25a.jpg)

___
Code is:
![code](https://cloud.githubusercontent.com/assets/2737316/18618472/2f0e7baa-7df0-11e6-9d48-7ca7ef9279bf.jpg)

__ 
Same code on Linux works perfect
Please, help!

**Comment by fzaninotto** [comment]
Did you set the default timezone in `php.ini`?

**Comment by XTRO123** [comment]
Yes.
php.ini:
[Date]
date.timezone = "Europe/Moscow"

**Comment by okj579** [comment]
It looks like this was fixed in #953. Try using the master branch.

**Comment by XTRO123** [comment]
I think that it's my error in my project. May be something interfere working with Dates. Faker without something works perfect.
