### ISSUE TITLE
Create issue running on PHP7

### ISSUE THREAD

**Issue by royhg** [fzaninotto/Faker#1035]
Hello fzaninotto,

Its great to have Faker in my project..
I have an issue that have "Invalid Numeric Literal error" on start using faker in PHP7 environment..
It was said that error on your class_exists checking..
But I cant to resolve that error...
Or It was my PHP7 conf error?
I run it successfully using PHP-5.6 environment..
Tq.
Roy.

**Comment by fzaninotto** [comment]
Can you paste your code and the actual error message?

**Comment by royhg** [comment]
use faker\factory;
$faker = Faker\Factory::create();

Invalid Numeric Literal..

that error has been raised when I used Bitnami [on](https://bitnami.com/redirect/to/124969/bitnami-wampstack-7.0.11-0-dev-windows-installer.exe) 
the last release with PHP-7.0 enviroment.

Sorry that actually my environment has already change to PHP5.6 since the faker running well.
But I still not found what make faker error when running on PHP7.

**Comment by fzaninotto** [comment]
Where is the exception thrown? The stack trace? Please add more details.

Also, since the [Faker unit test suite passes with PHP7](https://travis-ci.org/fzaninotto/Faker/jobs/161254211), I'll close this until you can give more evidence that there is a bug on the lib and not on your side.
