### ISSUE TITLE
Time between

### ISSUE THREAD

**Issue by stefanbaas** [fzaninotto/Faker#1036]
Hello, is there a function to get a random time between two given times.
Something like this:
`timeBetween($startTime = '09:00:00', $endTime = '12:00:00');`
OR
`time($format = 'H:i:s', $min = '00:00:00', $max = 'now') `
If it is not possible, maybe you can add it in the future release.
Thank you!

**Comment by fzaninotto** [comment]
That's `dateTimeBetween`, and it's [documented](https://github.com/fzaninotto/Faker#fakerproviderdatetime).
