### ISSUE TITLE
How about random domain name?

### ISSUE THREAD

**Issue by RubtsovAV** [fzaninotto/Faker#1043]
I want to implement the random domain names generator based on RFC standards. Do you think it will be helpful?

**Comment by fzaninotto** [comment]
Do you mean [`domainName`](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/Internet.php#L111-L114)? It already exists.

**Comment by RubtsovAV** [comment]
No, I mean full random symbols in domain name. The existing `domainName` based on `lastName`. It's not random (Not full random, I mean). I think this feature will be helpfull for testing usecase.

**Comment by fzaninotto** [comment]
I don't understand. Could you give example domain names you'd like Faker to generate?

**Comment by RubtsovAV** [comment]
Examples:
adfsad12-adf.com
anysymobls.com

**Comment by fzaninotto** [comment]
OK, then you misunderstand the purpose of Faker. We don't intend to generate *every possible data* for a given pattern, just *some plausible data*. We could add more patterns to the `domainName` formatter, but one day someone will ask about utf-8 domains and so on and so forth. 

For the usage it's built for (database population, test fixtures, stress test), I think the `domainName` is good enough. If, for your own usage, you need more complexity, use the `regex` formatter, or create your `RFCCompliantDomainName` provider and publish it as a standalone project - some users may find it useful, too.

**Comment by RubtsovAV** [comment]
OK. I understand.
