### ISSUE TITLE
InvalidArgumentException: Unable to find provider "HTMLLorem" with locale "en_US"

### ISSUE THREAD

**Issue by approached** [fzaninotto/Faker#1048]
I have follow error now:
InvalidArgumentException: Unable to find provider "HTMLLorem" with locale "en_US"

`/home/kloos/workspace/alpaca/vendor/fzaninotto/faker/src/Faker/Factory.php:46
/home/kloos/workspace/alpaca/vendor/fzaninotto/faker/src/Faker/Factory.php:21
/home/kloos/workspace/alpaca/vendor/laravel/framework/src/Illuminate/Database/DatabaseServiceProvider.php:67
/home/kloos/workspace/alpaca/vendor/laravel/framework/src/Illuminate/Container/Container.php:746
/home/kloos/workspace/alpaca/vendor/laravel/framework/src/Illuminate/Container/Container.php:644
/home/kloos/workspace/alpaca/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:709
/home/kloos/workspace/alpaca/vendor/laravel/framework/src/Illuminate/Database/DatabaseServiceProvider.php:71
/home/kloos/workspace/alpaca/vendor/laravel/framework/src/Illuminate/Container/Container.php:746
/home/kloos/workspace/alpaca/vendor/laravel/framework/src/Illuminate/Container/Container.php:644
/home/kloos/workspace/alpaca/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:709
/home/kloos/workspace/alpaca/vendor/orchestra/testbench/src/Traits/WithFactories.php:18
/home/kloos/workspace/alpaca/tests/TestCase.php:109
/home/kloos/workspace/alpaca/tests/TestCase.php:14
`

**Comment by approached** [comment]
Maybe this commit was not so good...
https://github.com/fzaninotto/Faker/commit/715f6e2f6055196d4f8c914a90d3ea4035f4b2b2

**Comment by gacek85** [comment]
+1

**Comment by fzaninotto** [comment]
I can't reproduce the issue. Can you provide me with a failing test case?

**Comment by fzaninotto** [comment]
Ah, I know: case-dependent OS. I'll fix it soon.

**Comment by fzaninotto** [comment]
Can you confirm it's fixed?

**Comment by gacek85** [comment]
Yup, worked fine now, cheers!

**Comment by ee0pdt** [comment]
Thanks for fixing so quickly!
