### ISSUE TITLE
Please change your dev-master version

### ISSUE THREAD

**Issue by approached** [fzaninotto/Faker#1049]
Hi,

Laravel and many other packages used a required state like this:
`"fzaninotto/faker": "~1.4",`

Or with the command:
`composer require fzaninotto/faker`

Everytime i will pull the dev-master version! Can you please remove it in the composer.lock file?

`    "extra": {
        "branch-alias": {
            "dev-master": "1.6.x-dev"
        }
    }
`

This is the reason why this error happened https://github.com/fzaninotto/Faker/issues/1048

**Comment by ht2** [comment]
Hi @approached, pretty sure you can just target the tag with `"fzaninotto/faker": "1.6.0",` if you need a confirmed working production release

**Comment by approached** [comment]
@ht2 
I know and it works great :-)
But if i newbie and i would use this package i follow the installation instruction like this:
`composer require fzaninotto/faker`

After the installation i have this error: https://github.com/fzaninotto/Faker/issues/1048

**Comment by curry684** [comment]
I think the real issue here is that releases are way too sporadic - last stable is from Apr 29th and 185 commits behind current master.

@fzaninotto any specific reason for the really long delays between releases?

**Comment by fzaninotto** [comment]
Yes, it's a lot of work each time:

- writing a changelog (which is not a simple `git log`)
- writing a blog post highlighting the new features
- doing a release on GitHub
- doing a release on packagist

Feel free to point to master if you need the latest features.

**Comment by approached** [comment]
@fzaninotto your workfalse is shitty :-)

- don't write a changelog
- if you have a new feature, than just add/remove in your readme file
- on github is just one command example: git tag 1.33.7
- packagist works full automatic

This workflow i use on https://github.com/approached/laravel-image-optimizer too.

**Comment by fzaninotto** [comment]
@approached That's why you have 30 stars and this repo 9000. Thanks for your advice, but I'll keep my workflow.
