### ISSUE TITLE
Image and relative path

### ISSUE THREAD

**Issue by Soullivaneuh** [fzaninotto/Faker#1057]
The image helper is great, but you have to pass an absolute path to be accurate.

You can pass a relative one but it will depends of form where you command is called and can be unstable especially for deploy tools like Capistrano.

It would be great to be able to pass variables or constant like `__DIR__` or `%kernel.root_dir%` for Symfony.

What do you think?

**Comment by fzaninotto** [comment]
Nah, it's up to the developer to build an absolute path with what's at their disposal (be it `__DIR__` or `%kernel.root_dir%`).

**Comment by Soullivaneuh** [comment]
@fzaninotto Could you please elaborate a bit about how to do this?
