### ISSUE TITLE
Feature suggestion - support to neighborhood in Address

### ISSUE THREAD

**Issue by joubertredrat** [fzaninotto/Faker#1081]
Hi guys, I liked this lib a lot, thanks.

I think that is good idea to add support to neighborhood in Address, using random data from streetName or with defined strings.

What you think guys?

**Comment by gavinkalika** [comment]
can you give an example?

**Comment by marjetika** [comment]
@joubertredrat - do you have an example for this?

**Comment by fzaninotto** [comment]
No news for too long, closing.
