### ISSUE TITLE
Faker localization 'en_ZA' not rendering $firstNameFemale for names with salutation

### ISSUE THREAD

**Issue by cchamusi** [fzaninotto/Faker#1086]
The faker localization 'en_ZA' not rendering $firstNameFemale for names with salutation. I am getting the following outputs in my database.
Miss {{$firstNameFemale}} Munyai
Dr. {{$firstNameFemale}} Watson
Mrs. {{$firstNameFemale}} Hattingh

**Comment by Newman101** [comment]
Bug spotted and fixed. :)
