### ISSUE TITLE
new providers

### ISSUE THREAD

**Issue by tablatronix** [fzaninotto/Faker#109]
Has anyone created a provider for html or markov chains ?

Html would be handy for wysiwyg editor content for blogs, cms's and comment systems.

A markov generator would be much better for approximation of actual logical content than the random lorem one. Especially for word count statistics and keyword analysis, tagging, search systems etc.

**Comment by tablatronix** [comment]
No one is going to contribute if you close the issue....

**Comment by nineinchnick** [comment]
Isn't a markov chain gen implemented as [realText](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/Text.php#L14)?

**Comment by tablatronix** [comment]
Yes it is now, just making a snarky point.
