### ISSUE TITLE
German Cities

### ISSUE THREAD

**Issue by tetrodoxin** [fzaninotto/Faker#1095]
There is no city 'Leipziger Land'. Formerly, there has been a county called like this, but even then you couldn't use it in addresses. Since the actual metropolis in that area is 'Leipzig' I suggest to rename 'Leipziger Land' to just 'Leipzig' and it would be fine.

Furthermore there's a type in 'Büsingenm Hochrhein', which is actually just 'Büsingen'.

**Comment by tetrodoxin** [comment]
I just saw, there are more typos or writing errors.
I could deal with the german providers and send a pull request. Would you be ok with that?

**Comment by fzaninotto** [comment]
Sure, please do.

**Comment by fzaninotto** [comment]
Fixed by #1098
