### ISSUE TITLE
en_GB postcodes are often invalid

### ISSUE THREAD

**Issue by DivineOmega** [fzaninotto/Faker#1104]
When compared to the following regular expression, a large number (most?) of the en_GB locale postcodes generate by Faker seem to be invalid.

`^(GIR ?0AA|[A-PR-UWYZ]([0-9]{1,2}|([A-HK-Y][0-9]([0-9ABEHMNPRV-Y])?)|[0-9][A-HJKPS-UW]) ?[0-9][ABD-HJLNP-UW-Z]{2})$`

This regular expression is a slightly modified version of one previously provided by the UK government. See: https://stackoverflow.com/questions/164979/uk-postcode-regex-comprehensive

**Comment by SecondeJK** [comment]
I have put your regex in a loop and run it x1million and can't find a single instance of it failing (though that was out of laziness - I can see the locale provided postcodes in the code and there's not that many anyway). Can you post an example where one is invalid? Or, if the examples have been modified this can be closed.

**Comment by DivineOmega** [comment]
Fair enough. Perhaps this was fixed at some point. Thanks for looking into it.
