### ISSUE TITLE
Consider refactoring readme.md?

### ISSUE THREAD

**Issue by tuwannu** [fzaninotto/Faker#1116]
The `readme.md` file has grown quite a lot since I first heard about this `Faker` library a few years ago. It's a bit overwhelming to read through it now:

- Navigating within the content involves lots of scrolling
- Some examples use really a lot of page/screen real estate (e.g. [Real Life Usage](https://github.com/fzaninotto/Faker#real-life-usage))
- Language specific formatters, does it need to be all on the same page?
- Etc.

Take both of your inspirations, Perl's [Data::Faker](http://search.cpan.org/~jasonk/Data-Faker-0.07/) and ruby's [Faker](http://www.rubydoc.info/gems/faker/1.6.6) as examples, they both have some kind of paginated or sticky navigation.

Would you consider refactoring `readme.md` file? One of these tools could be used:

- [ReadTheDocs](https://readthedocs.org/), e.g. [Money for PHP](http://moneyphp.org/en/latest/) (docs reside in `/doc` folder in the repo)
- [GitHub Wiki](https://help.github.com/articles/about-github-wikis/), e.g. [Dingo](https://github.com/dingo/api/wiki) (separate repo for wiki, but either editable by contributors or by any users)
- etc.

Would be happy to help.

**Comment by fzaninotto** [comment]
Thanks for your suggestion. I'm quite happy with the fact that we can easily bundle the doc with the source code, so people don't need to look for the website url to get the doc. The navigation is perfectible, but we already have anchors. So I guess we'll leave it like that.
