### ISSUE TITLE
Composer / Github Tags out of sync

### ISSUE THREAD

**Issue by RStrydom** [fzaninotto/Faker#1117]
Hi,

I see that there are a few closed issues regarding this and I was hoping someone could help me out.

I am currently in need of the `idNumber()` generator located @ `faker/src/Faker/Provider/en_ZA/Person.php`
When I do the `composer require fzaninotto/faker` I get the `^1.6` entry placed in my composer.json file. But when I go to the quoted class, (scroll to the bottom) - I do not see this method at all. I have confirmed that when I clone the repo I can see the code, as well as changing the composer value to `^1.6.0`, `1.60`, `v1.6.0` , `~1.6` even `1.*` but none of them gave me the code I was looking for.

I am currently using it in a Laravel 5.3 install and would really like to depend on this feature which is clearly in the codebase.

You assistance will be greatly appreciated.

**Comment by curry684** [comment]
If you look at the 1.6 tagged version of that file at https://github.com/fzaninotto/Faker/blob/v1.6.0/src/Faker/Provider/en_ZA/Person.php you'll see it simply wasn't part of that release yet. So nothing is out of sync, and everything is working as expected and intended. Composer by default just includes the latest stable if you do not specify a version yourself, hence the completely correct `^1.6`.

Use `"fzaninotto/faker": "dev-master"` if you really need the latest features, you may need to tweak the `minimum-stability` requirement as well (https://getcomposer.org/doc/04-schema.md#minimum-stability).

**Comment by RStrydom** [comment]
@curry684  - Thank you very much, I must not have double checked all my facts. I have switched to dev-master and can now see the code I was looking for.
