### ISSUE TITLE
How to generate text without certain characters (i.e. spaces)?

### ISSUE THREAD

**Issue by anik786** [fzaninotto/Faker#1128]
How do I use faker to create a string of length 100 without any spaces (or certain characters).

Currently the closest I can get to achieve this is:

```
$faker->text(100);
```

But this of course includes space.

**Comment by curry684** [comment]
That's not really a common scenario for fake data. You could just substr(str_replace(' ', '', $faker->text(200)), 0, 100);

**Comment by anik786** [comment]
Could we potentially add this feature. For example, we could have:

```
$faker->textExcept(100, [' ', '.'])
```

Which would generate 100 characters without spaces and full stops.

A use case of this may be to test certain fields where certain characters are not allowed. For example testing a 100 character "first-name".

**Comment by fzaninotto** [comment]
Nope, you'll have to implement it in pure PHP on your side.

**Comment by thezahedi** [comment]
You can use
```
$length = 200;
$faker->lexify(str_repeat('?', $length));
```
