### ISSUE TITLE
Class 'Faker\Factory' not found

### ISSUE THREAD

**Issue by endrianus** [fzaninotto/Faker#1130]
Hello. I'm using laravel 5.2 and my Faker version is 1.6 but. When I run : 

`php artisan migrate --seed`

it says : 

`Class 'Faker\Factory' not found`

Could you please help me ?

**Comment by endrianus** [comment]
Here is my composer.json contents.

`{
    "name": "Laravel Angular Admin",
    "description": "Laravel + Angularjs + Bootstrap + AdminLTE binded by Gulp workflow Admin Dashboard Boilerplate",
    "keywords": ["laravel", "angular", "bootstrap", "admin", "admin template", "ui-router", "api", "angular-bootstrap"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "tymon/jwt-auth": "^0.5.9",
        "barryvdh/laravel-cors": "0.7.x",
        "laravelangular/generators": "2.7.x",
        "dingo/api": "1.0.x@dev",
        "laravel/socialite": "^2.0",
        "bican/roles": "2.1.*",
        "fzaninotto/faker": "^1.6"
    },
    "require-dev": {
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*",
        "squizlabs/php_codesniffer": "*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
           "php -r \"unlink('code_of_conduct.md');\"",
           "php -r \"unlink('CHANGELOG.md');\"",
           "php -r \"unlink('.codeclimate.yml');\"",
           "php -r \"unlink('.travis.yml');\"",
           "php artisan key:generate",
           "php artisan jwt:generate"
        ],
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php -r \"copy('.env.example', '.env');\"",
            "php artisan optimize",
            "php artisan key:generate"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
`

**Comment by endrianus** [comment]
Here is my composer.json contents. 

![screen shot 2016-12-31 at 11 11 53 am](https://cloud.githubusercontent.com/assets/16950480/21575752/1fddf844-cf4a-11e6-9648-d7451b6c09ba.png)

**Comment by JoseCage** [comment]
@endrianus How are configured you `/database/factories/ModelFactory.php` file?

**Comment by endrianus** [comment]
this is my model factory class.

![screen shot 2017-01-01 at 10 56 15 am](https://cloud.githubusercontent.com/assets/16950480/21580133/01456f26-d011-11e6-9e31-51f245c829e0.png)

and this my seeder class.

![screen shot 2017-01-01 at 10 56 24 am](https://cloud.githubusercontent.com/assets/16950480/21580134/09173d4c-d011-11e6-9fae-32c78cb7aac3.png)

**Comment by endrianus** [comment]
Solved it !! I just remove `"fzaninotto/faker": "^1.6"` then `composer update`. After that reinstall again using `composer require fzaninotto/faker`. Now work like a charm. Thank you Jose for your response.

**Comment by JoseCage** [comment]
@endrianus  Nice to know..

Happy new Year..

![bitmoji](https://render.bitstrips.com/v2/cpanel/10215885-227153730_1-s4-v1.png?transparent=1&width=246)
