### ISSUE TITLE
unique but optional fake number

### ISSUE THREAD

**Issue by hardfire** [fzaninotto/Faker#1133]
I want to optionally generate a unique number within a range. But, I don't want the optional value(null) to be unique.

`$values =  $faker->unique()->optional()->numberBetween(10, 50)` returns only one optional which makes sense logically, and,
`$values =  $faker->optional()->unique()->numberBetween(10, 50)` gives back an error `Call to a member function numberBetween() on null`

What would be the right way to generate optional() but unique() values?

**Comment by fzaninotto** [comment]
You'll have to create your own system for that, using a custom value pool.

**Comment by tremby** [comment]
I came across this issue today, and found that it was asked for here and also in #685. I'm surprised it's closed. It seems like something which would be a common requirement.

What is the suggested workaround? I'm currently working around it with `$faker->numberBetween(0, 3) === 0 ? null : $faker->unique()->email`
