### ISSUE TITLE
National Insurance number for en_GB

### ISSUE THREAD

**Issue by anik786** [fzaninotto/Faker#1134]
Can we add a national insurance number for GB locale, as majority of the people in Great Britain has one, and is often used in forms.

National insurance numbers are usually a format similar to this: QQ123456C

They are often printed in pairs like this: QQ 12 34 56 C

The format of the number is two prefix letters, six digits, and one suffix letter. More information can be found here: https://en.wikipedia.org/wiki/National_Insurance_number

**Comment by anik786** [comment]
A fast way to achieve this using the current methods is as follows:
```
$faker->regexify('^[A-Z]{2} \d{2} \d{2} \d{2} [A-Z]$')
```
Note that this still can generate some invalid national insurance number, as there are many other weird conditions that it should follow. e.g. Neither of the first two letters can be D, F, I, Q, U or V. The second letter also cannot be O. The prefixes BG, GB, NK, KN, TN, NT and ZZ are not allocated.

However this should be enough to generate NI numbers that look like NI numbers.

**Comment by fzaninotto** [comment]
Yes you can do it, feel free to open a PR for that.

**Comment by anik786** [comment]
Cool!
