### ISSUE TITLE
PHP 7.1 Incompatibility for method seed()

### ISSUE THREAD

**Issue by neomerx** [fzaninotto/Faker#1136]
Due to changes in `mt_rand()` it breaks many tests that rely on Faker's `seed()` method.

From official [Backward incompatible changes](http://php.net/manual/en/migration71.incompatible.php)
> mt_rand() will now default to using the fixed version of the Mersenne Twister algorithm. If deterministic output from mt_srand() was relied upon, then the MT_RAND_PHP with the ability to preserve the old (incorrect) implementation via an additional optional second parameter to mt_srand().

#### Current Implementation
```php
    public function seed($seed = null)
    {
        if ($seed === null) {
            mt_srand();
        } else {
            mt_srand((int) $seed);
        }
    }
```
#### Possible Solution
It's not cryptography so we can stick to Pre-PHP 7.1
```php
        if ($seed === null) {
            mt_srand();
        } else {
            if (PHP_VERSION_ID < 70100) {
                mt_srand((int) $seed);
            } else {
                mt_srand((int) $seed, MT_RAND_PHP);
            }
        }
```

**Comment by Plopix** [comment]
+1

**Comment by Plopix** [comment]
It is already fixed in master actually @neomerx.
https://github.com/fzaninotto/Faker/blob/master/src/Faker/Generator.php#L192

I think you can close this issue ;)

++

**Comment by neomerx** [comment]
Well, until it's actually released it causes yooge :smile: amount of errors in existing projects as the project declares
```
    "require": {
        "php": "^5.3.3|^7.0"
    },
```

It either should be released or the version should be fixed.
