### ISSUE TITLE
Please add a .gitattributes file

### ISSUE THREAD

**Issue by InsaneScripts** [fzaninotto/Faker#1147]
Please add a `.gitattributes` file to exclude the `/test` directory and any other files that aren't needed in production (e.g.: `CHANGELOG.md` , `CONTRIBUTING.md`).

Thanks :smiley:

**Comment by lichunqiang** [comment]
This is impossible.  The author rejected to add this file long long ago.

**Comment by fzaninotto** [comment]
see #1085
