### ISSUE TITLE
How to create a faker image with  different extensions?

### ISSUE THREAD

**Issue by mkillua** [fzaninotto/Faker#1149]
Hi guys, 
thanks for your project. I'm using on my unit tests but i need to test if an image is png,gif or jpge.
I read the documentation but i don't found how to create a faker image with others extensions.
It's possible?

**Comment by fzaninotto** [comment]
No, you'll have to write your own provider for that, or use a library like [Imagine](https://github.com/avalanche123/Imagine) to make the conversion
