### ISSUE TITLE
Passing null to the iban provider generates invalid ibans

### ISSUE THREAD

**Issue by blaues0cke** [fzaninotto/Faker#1155]
I use the following fixture:

```
AppBundle\Entity\BankAccount:
    bankAccount_{1..25}:
        accountOwnerName: '<name()>'
        bankName:         '<words(3, true)>'
        bic:              '<swiftBicNumber()>'
        iban:             '<iban(null)>'
```

Like the [documentation](https://github.com/fzaninotto/Faker) says:

```
// Generates a random IBAN. Set $countryCode to null for a random country
iban($countryCode)      // 'IT31A8497112740YZ575DJ28BP4'
```

this should generate valid ibans for different countries. In fact it generates ibans like `NULL98476049370264537467753371` instead. Passing nothing to `iban()` does not work too, since the first parameter is required.

Am I failing in passing `null` or is this a bug?

        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0",
        "hautelook/alice-bundle": "^2.0@beta",
        "nelmio/alice": "^3.0@beta",
        "theofidry/alice-data-fixtures": "^1.0@beta",
        "doctrine/data-fixtures": "^1.2"

**Comment by eyeskiller** [comment]
You have probably something wrong in your definition. 

As you can see this part of code:

```
    public static function iban($countryCode, $prefix = '', $length = null)
     {
         $countryCode = is_null($countryCode) ? self::randomKey(self::$ibanFormats) : strtoupper($countryCode);
```

And if I can tell, faster is using 

`$countryCode === NULL`

but not significant...

**Comment by blaues0cke** [comment]
But it seems that `null` is passed to `strtoupper($countryCode)`, this would explain the uppercase `NULL` in `NULL98476049370264537467753371`.

**Comment by raphaeldealmeida** [comment]
I think your framework are using this parameter like a string, including NULL.

A valid test for [iban method](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/Payment.php#L225) is to receve a invalid string. Actually string null or another unrecognized parameter is allowed. Following [this site](https://www.iban.com/) to start iban with "NULL" is inválid.
