### ISSUE TITLE
Accept \DateTimeImmutable in parameters

### ISSUE THREAD

**Issue by JarekW** [fzaninotto/Faker#1162]
Functions like `dateTimeBetween($from, $to)` and other currently only accept `\DateTime` as parameters. This should be changed to `\DateTimeInterface` so `\DateTimeImmutable` will be also valid.

**Comment by fzaninotto** [comment]
Except `DateTimeInterface` requires PHP 5.5.0. Faker requires PHP >= 5.3.3.

**Comment by JarekW** [comment]
@fzaninotto Is there a plans in faker to switch to new version (2.0 maybe)? 5.3 is not supported from 14 August 2014.

**Comment by fzaninotto** [comment]
Not yet.

**Comment by localheinz** [comment]
How about now, @fzaninotto?

**Comment by fzaninotto** [comment]
Still not yet.

**Comment by Nek-** [comment]
Any plan to announce @fzaninotto?

**Comment by Warxcell** [comment]
Now? :D
