### ISSUE TITLE
Class 'Faker\ORM\Eloquent\Populator' not found

### ISSUE THREAD

**Issue by Magefo** [fzaninotto/Faker#1169]
Hi, i am trying to populate entities with population adapters, Athough Eloquent is supported, i can't use it

**Comment by fzaninotto** [comment]
Did you use the master branch? It's probably not yet released.

**Comment by shalawani** [comment]
Hi, i am trying to populate entities with population adapters, Athough Eloquent is supported, i can't use it

**Comment by alec-joy** [comment]
The documentation says that Eloquent is a supported ORM adapter but, even on the master branch, there isn't an ORM driver for it. Should we be using Doctrine2 since that's what Eloquent uses under the hood?
