### ISSUE TITLE
Generate fake identities that fit to each other

### ISSUE THREAD

**Issue by amenk** [fzaninotto/Faker#1178]
Is it possible, for example when generating a name, to generate a mail that fits to it?

For example, Doe, John -> JohnDoe123@gmail.com

The Problem is that we often debug in our database of fake data and it is very confusing when John Doe has a email address that implies another name like MaxMusterman123@gmail.com

Same might apply for company names. John Doe might probably be in the Doe and Sons company.

**Comment by fzaninotto** [comment]
Duplicate of #557

**Comment by amenk** [comment]
Thanks for finding the dupe --- but they seem to be closed both now?

**Comment by fzaninotto** [comment]
Yes, that's a "won't fix" type of closed.

**Comment by amenk** [comment]
But why? Too complicated? Would you accept such a PR ?

**Comment by fzaninotto** [comment]
If you want to give it a try, you're welcome. But I don't think the current architecture allows it without breaking BC hard.
