### ISSUE TITLE
middleName consistency

### ISSUE THREAD

**Issue by JustBlackBird** [fzaninotto/Faker#1191]
At the moment different providers expose middle names in different ways.

For example, person provider for `ru_RU` locale exposes middle names with two methods: [`middleNameMale`](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/ru_RU/Person.php#L117) and [`middleNameFemale`](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/ru_RU/Person.php#L131). At the same time, person provider for `vi_VN` locale exposes middle names as a single [`middleName`](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/vi_VN/Person.php#L164) method.

I suggest to use only one way of exposing middle names. To be compatible with `lastName` and `firstName` it should be done as in `vi_VN` locale with a single method `middleName` with `$gender` flag.

If the maintainer is interested in it I could provide a PR to fix this.

**Comment by fzaninotto** [comment]
I don't mind inconsistencies in middleNames.

**Comment by JustBlackBird** [comment]
Consider an use case when the lib is used to generate test data for multilingual system. If I use both `ru_RU` and `vi_VN` locales for testing I have to **vary method name** to get middle name. For example:

```php
$faker = \Faker\Factory::create('ru_RU');
$faker->middleNameMale(); // There is no "middleName" method :(
```
but
```php
$faker = \Faker\Factory::create('ru_RU');
$faker->middleName(\Faker\Provider::GENDER_MALE);
```
