### ISSUE TITLE
Provider pt_PT - address

### ISSUE THREAD

**Issue by pipanni** [fzaninotto/Faker#1197]
Hi

When generating the full address with "$this->faker->address" the postal code would be next to the street address without any space between them and with a line break. It makes more sense and looks better on single line outputs to replace the "\n" in the code by a single space.

So, at line 25 of the file "faker\src\Faker\Provider\pt_PT\Address.php" one should replace the "\n" by " ".

**Comment by fzaninotto** [comment]
Could you open a PR?

**Comment by raphaeldealmeida** [comment]
Done with tests

**Comment by fzaninotto** [comment]
Fixed by #1203
