### ISSUE TITLE
Locale sets fail even if $locale is given

### ISSUE THREAD

**Issue by banqhsia** [fzaninotto/Faker#1200]
Hi, I'm using `Laravel` and `Faker` to fill my database.

To fill some random seeds, I gave the `create` method a parameter that is my locale.

But still seems latin seeds. 

```php
class ArticlesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $faker = Faker::create('zh_TW');

        //  Generate 10 articles
        for ($i=0; $i < 10; $i++) {
            Article::create([
                'key' => uniqid(),
                'title' => $faker->sentence,
                'content' => $faker->text
            ]);

        }
    }
}

```

The locale `zh_TW` provider exists, but still got latin sentences and texts.

- Laravel Version: 5.4.19
- Faker Version: 1.6

**Comment by fzaninotto** [comment]
This is a Laravel-related bug, please open an issue there.
