### ISSUE TITLE
Doctrine and ManyToMany relation

### ISSUE THREAD

**Issue by jc-oclock** [fzaninotto/Faker#1201]
Hi,
It seems the join tables n:m are not populated automatically by Faker with Doctrine, as descripted in #55 and #54. The PR related here does not seem to have been merged ? (and I cant merged this from a patch dating back to 2012).

What do you think about it ?
Thanks !

**Comment by fzaninotto** [comment]
The Doctrine parts of Faker was contributed by the Doctrine dore developers, but they don't maintain it anymore. I'm considering removing this code from the Faker repository.

**Comment by jc-oclock** [comment]
Ok, we'll manage with this.
Thanks for replying.
