### ISSUE TITLE
EntityPopulator.fillcolumns() using method_exists calling private method

### ISSUE THREAD

**Issue by cap-dev** [fzaninotto/Faker#1210]
I have come across an issue where fillColumns is using 'method_exists' on line 202. This gives rise to issues with a call to a callable but private method in one of our Doctrine objects. Would it be possible to change this call to 'is_callable' instead, as the private method is not then called and causing the process to fail?

**Comment by fzaninotto** [comment]
Unfortunately the contributor of the Doctrine populator is not around anymore. I'm considering removing the Doctrine populator from the Faker core.
