### ISSUE TITLE
Introduce `currentLocale()` to work with the content language

### ISSUE THREAD

**Issue by sourcerer-mike** [fzaninotto/Faker#1211]
As a translator app or service
I want to provide my mocked data with the current locale
so that the context is still valid no matter to what locale I switch in each test.

You can change the used locale via PHP code.
Unfortunately it is not possible to receive the current locale in yml files.
Introducing a `currentLocale()` or similar would be great.

Also consider this for the other misc faker providing language information like `currentCountryCode()` etc.

**Comment by fzaninotto** [comment]
I think you've opened your issue on the wrong repo : there is no YAML files in Faker, and the locale is explicit in the initialization.
