### ISSUE TITLE
Add random array generator

### ISSUE THREAD

**Issue by elnur** [fzaninotto/Faker#1215]
I have a test where a mock is supposed to return an array. I don't really care what's in that array because I just need to test that the tested method passes that array to another mock. Hence it'd be nice to have a random array generator in Faker.

**Comment by curry684** [comment]
Isn't that use case fundamentally flawed? Test cases should be reproducible, so you definitely need to check that the array contents were passed through unharmed:

```
return [1,2,3];
...
$this->assertEquals([1,2,3], $array);
// Or at the very least:
$this->assertCount(3, $array);
```
I don't see any valid use case whatsoever for "just give me an array with some elements of unspecified type and value".

**Comment by elnur** [comment]
`assertEquals()` compares arrays fine. I don't really care what's in the array as long as it's passed further to another mock. And that's verified with the `with()` specification of the mocked method.

> Not caring about the content does not make a case for a fixture generator yet, you could even say it explicitly doesn't as Faker's job is to supply **fake** data, not **random** data. For random data you already have `mt_rand()`.

Sorry, mate, can't agree with you there. Faker has methods generating random data. I can easily get random numbers, strings, days. Why not arrays? I could use `paragraphs()` here, but it's not explicit enough.

**Comment by dandonahoe** [comment]
@curry684 I get what you're saying, but there's an option to seed Faker to facilitate reproducible results. See[Seeding the Generator](https://github.com/fzaninotto/Faker#seeding-the-generator)

**Comment by curry684** [comment]
That's not the point, you'd still be assuming it fills an array with integers. An array could be filled with DateTimes, long strings, other arrays, hashes, own classes, you name it. It's not Faker's job to facilitate ALL of that, and again it's beside Faker's goal. Faker's job is to provide reproducible test data. If the only requirement you have is that you get an array, use `return [];`. If it needs to contain 10 integers, use `return array_fill(10, 1);`. There is nothing Faker can do to *generically* make that any more straightforward.

**Comment by fzaninotto** [comment]
I don't know what a random array looks like. This is too broad for Faker to provide relevant data. I suggest you pick the formatters that seem to fit your use case, and build your own populator based on that.

**Comment by browner12** [comment]
This is a feature I've been looking for for awhile.  Maybe an example would help illustrate the need.

I have a model called `Dealer`, and a field called `service_areas`, which is a list of cities the dealer services. This is stored as a `json` field in the table, and Laravel automatically will cast it to a `Collection` object for me.  When seeding the table, I would like to get an ***array*** of cities, that would then automatically be `json_encode`d for storage in the DB.

The ideal signature for me would look something like this:

```php
$faker->arrayOf(5)->city;  // ['Madison', 'Milwaukee', 'Oshkosh', 'Neenah, 'Menasha']
```

Currently the Lorem provider has the options to provide strings or arrays.

```php
$faker->word; // 'hello'
$faker->words; // ['hello', 'there']
$faker->sentence; // 'hello there'
$faker->sentences; // ['hello there', 'general kenobi']
$faker->paragraph;
$faker->paragraphs;
```

So we already provide this functionality for a select number of fields, but it would be great to extend that to **all** fields.  I would be glad to help implement this feature if it would be accepted.

**Comment by localheinz** [comment]
See https://github.com/fzaninotto/Faker/pull/710.

**Comment by browner12** [comment]
thanks for the heads up @localheinz
