### ISSUE TITLE
add ui-faces

### ISSUE THREAD

**Issue by jens1o** [fzaninotto/Faker#1221]
Some ui face-links were pretty cool.

**Comment by fzaninotto** [comment]
No, thanks.

**Comment by jens1o** [comment]
I'm sorry?

**Comment by fzaninotto** [comment]
Feel free to create a standalone provider for that, but Faker core focuses on most common use cases, and I believe this is not one of them.

**Comment by jens1o** [comment]
Okay, thanks for this detailed explaination.
