### ISSUE TITLE
add site in gerenal and cep pt-br, Neighborhood pt-br and others

### ISSUE THREAD

**Issue by pedroskakum** [fzaninotto/Faker#1222]
Suggestions for next additions:
-faker site
-faker cep (post address code) pt-br
-faker neighborhood in pt-br and others

**Comment by fzaninotto** [comment]
I'm looking forward to reducing the number of open issues. If you need a place to keep a task list for your language, please use another tool!

**Comment by pedroskakum** [comment]
As visions only improve the quality of your product, but sorry for the inconvenience
