### ISSUE TITLE
valid() and unique() don't mix

### ISSUE THREAD

**Issue by srgraham** [fzaninotto/Faker#1225]
```php
// example validation function to pass to valid()
function maxLength($len) {
    $func = function ($value) use ($len) {
        return strlen($value) <= $len;
    };
    return $func;
}


// successfully filters out usernames > 10 characters
$faker->valid(maxLength(10))->userName();

// errors, sending an object to valid() instead of a chosen string
$faker->valid(maxLength(10))->unique()->userName();

// Exception: Serialization of 'Closure' is not allowed 
$faker->unique()->valid(maxLength(10))->userName();
```

**Comment by iBotPeaches** [comment]
Hit this as well, I just marked the code snippet with this ticket. Builds only fail like 1 in 20 when it happens to generates a duplicate (non-unique) value. 

Perhaps I can take a dive into solving this, I'll take a look this weekend.

**Comment by zhikiri** [comment]
Hello guys, I'll check this issue if it's okay for you ?

**Comment by marjetika** [comment]
@zhikiri are you working on this issue?

**Comment by zhikiri** [comment]
@marjetika no, I'm not :) feel free to go forward with this

**Comment by pimjansen** [comment]
Flag this as enhancement since this would probably mean a breaking change as well on how and if we can stack those modifiers.

@localheinz @fzaninotto what is your view on this feature? Since all of those methods are completely isolated i think it will be pretty hard to get this job done without breaking all the things

**Comment by fzaninotto** [comment]
I agree, it's impossible to fix without a breaking change. And I think that the fluid interface was a trap - we shouldn't use it for modifiers in the future.
