### ISSUE TITLE
Is `random` in method names superfluous?

### ISSUE THREAD

**Issue by nikhiltri** [fzaninotto/Faker#1245]
There are a few method names with the word `random` in them:

```
randomNumber(2);
randomDigit;
randomElement(['a', 'b', 'c']);
```

While other methods that return similarly random data have more concise names, like:

```
dateTimeThisYear;
name;
words(3);
```

All these methods return data that is randomly chosen among a subset, or perhaps put another way, "fake"—random dates, random names, and random words. The randomness is implied by the essential purpose of this package being to provide random values. So is the word `random` in these method names repetitive? Can they and other methods with the word `random` in it be simplified to just `number(2)`, `digit` and `element(['a', 'b', 'c'])`?

**Comment by ed-piisang** [comment]
I agree. It also adds inconsistency.

**Comment by fzaninotto** [comment]
True, but there are 2 problems:

1. Renaming these methods will break BC, which is a no-no before Faker 2.0
2. Some of the method names without "random" may be PHP reserved words in PHP < 7

So I won't consider this for the near future.

**Comment by ed-piisang** [comment]
Pehraps give it a 2.0 Label so you can at least group such issues for the future?
