### ISSUE TITLE
Remove historical currencies

### ISSUE THREAD

**Issue by eidng8** [fzaninotto/Faker#1250]
I've met a problem recently, with the generated currency code being outdated, and hence, failed (false alarm) one of my unit test on currencies.

I think we should remove historical codes from the faker. I you agree, I can make a PR.

**Comment by fzaninotto** [comment]
Which currencies are you talking about?

**Comment by eidng8** [comment]
A lot! e.g. `EEK`, `LTL`.

This [wiki list](https://en.wikipedia.org/wiki/ISO_4217#Historical_currency_codes) has it all.

**Comment by fzaninotto** [comment]
OK, could you make a PR?

**Comment by fzaninotto** [comment]
Fixed in #1251
