### ISSUE TITLE
Feature Suggestion: uri-template

### ISSUE THREAD

**Issue by fireproofsocks** [fzaninotto/Faker#1253]
JSON Schema supports a keyword to indicate that a value is a 'uri-template' (see http://json-schema.org/latest/json-schema-validation.html#rfc.section.8.3.8 and https://tools.ietf.org/html/rfc6570).  It would be a useful feature to be able to generate fake URI Templates.

**Comment by fzaninotto** [comment]
Interesting, but not in core. I suggest you create a specialized provider, and publish it as a standalone package.
