### ISSUE TITLE
Feature Suggestion: uri-reference

### ISSUE THREAD

**Issue by fireproofsocks** [fzaninotto/Faker#1254]
JSON Schema now supports a format for "uri-reference".  See http://json-schema.org/latest/json-schema-validation.html#rfc.section.8.3.7 and https://tools.ietf.org/html/rfc3986 .  It would be useful to be able to generate fake uri-references.  Sometimes this is the same as the JSON Schema "uri" keywords, but sometimes it can be email addresses, phone numbers, etc.

Some examples:
```
ftp://ftp.is.co.za/rfc/rfc1808.txt
http://www.ietf.org/rfc/rfc2396.txt
ldap://[2001:db8::7]/c=GB?objectClass?one
mailto:John.Doe@example.com
news:comp.infosystems.www.servers.unix
tel:+1-816-555-1212
telnet://192.0.2.16:80/
urn:oasis:names:specification:docbook:dtd:xml:4.1.2
```

**Comment by fzaninotto** [comment]
Interesting, but not in core. I suggest you create a specialized provider, and publish it as a standalone package.
