### ISSUE TITLE
Volunteer Offer for Doctrine Support

### ISSUE THREAD

**Issue by dohpaz42** [fzaninotto/Faker#1270]
I've noticed in a few of the Doctrine issues that the current Doctrine maintainer is no longer maintaining the Doctrine code, and that you are considering dropping support for the ORM. I would like to volunteer to maintain the Doctrine code, and help with the Doctrine issues / PRs.

**Comment by fzaninotto** [comment]
Sure, be my guest! Please open PRs and I'll review them.
