### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by celldweller24** [fzaninotto/Faker#1276]
With command "composer update" for Laravel 5.2 I have an error
```
- Updating fzaninotto/faker (v1.6.0 => v1.7.1)
    The package has modified files:
    M .gitignore
    M .travis.yml
    M CHANGELOG.md
    M CONTRIBUTING.md
    M LICENSE
    M Makefile
    M composer.json
    M phpunit.xml.dist
    M readme.md
    M src/Faker/Calculator/Iban.php


  [ErrorException]
  A non-numeric value encountered
```

The repository that was included:
"fzaninotto/faker": "1.7.1"
php version - 7.1

**Comment by fzaninotto** [comment]
I need more information about the error (file, line)

**Comment by celldweller24** [comment]
It is all that i see in console output

**Comment by raphaeldealmeida** [comment]
Please, paste your composer.json for test

**Comment by isaacabensur** [comment]
I am getting the same error [ErrorException] A non-numeric value encountered when I give an artisan command php artisan migrate:refresh –seed. 

` public function run()
    {
       $faker = Faker\Factory::create();
        $users = User::all();

        foreach ($users as $user) {
            Employee::create([
                'nombres' => $faker->name,
                'apellido_paterno' => $faker->lastName,
                'apellido_materno' => $faker->lastName,
                'document_type' => $faker->randomElement(['dni', 'ce', 'le']),
                'document_number' => $faker->numberBetween(11111111, 99999999),
                'telefono' => $faker->numberBetween(11111111, 99999999),
                'area' => $faker->word,
                'tipo_contrato' => $faker->randomElement(['Indefinido', 'Temporal']),
                'sueldo' => $faker->numberBetween(1000, 10000),
                'asignacion_familiar' => $faker->randomElement(['1', '0']),
                'fecha_ingreso' =>  Carbon\Carbon::now(),
                'user_id' => $user->id,
                'estado' => '1',
                'created_by' => 'seeder',
                'modified_by' => 'seeder',
            ]);
        }
    }`

**Comment by fzaninotto** [comment]
Sorry, this seems to be a Laravel issue, please use their bug tracker.
