### ISSUE TITLE
Faked first name "Max" results in random number written to database

### ISSUE THREAD

**Issue by Zaister** [fzaninotto/Faker#1282]
I'm using the faker library with the german locale to generate customer data for tests. On occasion, the first name "Max" is generated. However, every time this name is generated, the database field filled by the factory()->create() call writes a seemingly random integer number into the field.

I believe this happens because "max" is also a function, and the field is somehow being evaluated before storing. This is corroborated by the fact the if I hardcode the name as "Min", the field is filled with 0.

**Comment by fzaninotto** [comment]
This sounds like a bug on your side rather than on the Faker side.

Are you using a Faker populator, or a third-party library?

**Comment by Zaister** [comment]
I'm using $faker->firstNameMale for this. I think the problem occurs within the factory code where the faked data is transformed into a database insert statement. Now that i think about it that is probably not your library but Laravel Eloquent code.

**Comment by fzaninotto** [comment]
Fine, I'm closing the issue then.
