### ISSUE TITLE
Add sequence capabilities

### ISSUE THREAD

**Issue by axelitus** [fzaninotto/Faker#1299]
Sometimes it's necessary to fake sequences. It would be nice to have a sequence generator that could handle the sequence code in the background.

I have coded a rough version of a sequence generator for numbers that I could share in a PR integrating it to the package.

The usage is:

```
echo "Sequence #1"
echo $faker->sequence()->next;
echo $faker->sequence()->next;
echo $faker->sequence()->next;

echo "Sequence #2"
echo $faker->sequence(true)->next;
echo $faker->sequence()->next;
echo $faker->sequence()->next;

echo "Sequence #3"
echo $faker->sequence(true, 25)->next;
echo $faker->sequence()->next;
echo $faker->sequence()->next;
```

and will output:

```
Sequence #1
1
2
3
Sequence #2
1
2
3
Sequence #3
25
26
27
```

Based on this we could easily extend the functionality to have `nextBit`, `nextOctal`, `nextHex`, `nextChars` methods which could output the next element in sequence in binary, octal, hex format and chars that go from a to z and then from aa to zz and so on.

Do you think the package would benefit from something like this?

**Comment by fzaninotto** [comment]
What's random about it?

**Comment by axelitus** [comment]
The sequence itself is not random. I found myself in the need to fake database records for seeding and some of the fields for this records are sequences (which are not the primary key so they do not get 
generated by the db).

I'm using Laravel and it's factories and seeders and the code looks like this:

Seeder:
```php
// ChildTableSeeder.php
Parent::all()->map(function($parent) use($faker) {
    $faker->unique(true);         // for each parent reset the unique table (child names are unique per parent scope)
    $faker->sequence(true);    // for each parent que start the sequence again (sequence is per parent scope)
    factory(Child::class, 3)->create([
        'parent_id' => $parent->id
    ]);
});
```

Factory:
```php
// ChildFactory.php
$factory->define(Child::class, function (Faker $faker) {
    return [
        'parent_id' => 1,
        'sequenceable' => $faker->sequence()->next,
        'name' => $faker->unique()->name
    ];
});
```

This allows me to have the sequencing encapsulated in the object that it's already passed into the closure and makes the code easier and descriptive. If there was no sequence inside the faker, the code handling it would unnecessarily clutter the classes.

I think this is helpful, at least for me in this case doing the sequence in the faker was better than the alternatives and I think it's nice to have.

**Comment by fzaninotto** [comment]
It is helpful for seeding, but it doesn't belong to a fake data generator. I advise you to publish it as a standalone package, or in Laravel Factories / Seeders.

**Comment by daniel-iwaniec** [comment]
The name **faker** suggests generating **fake** data, not **random** data so I don't see how not being random excludes something from this library. It would be better to just admit that creating and/or maintaining sequence would be too much work for too little library users.

**Comment by panzer-planet** [comment]
You could use a static variable to get a sequence of values. You don't need faker for that.

$factory->define(VesselTrack::class, function (Faker $faker) {
    static $intervals = 0;
    return [
        'created_at' => \Carbon\Carbon::now()->subDays(3)->addMinutes(10 * $intervals++),
        'latitude' => $faker->latitude(-40,-49),
        'longitude' => $faker->longitude(160, 178),
    ];
});
```
