### ISSUE TITLE
Use of undefined constant MT_RAND_PHP

### ISSUE THREAD

**Issue by mburak** [fzaninotto/Faker#1308]
Hi, I'm trying to run a test using the Faker with PHP7 and I'm getting the following message, it looks like that constant is not defined? Where should it be?

```
Use of undefined constant MT_RAND_PHP - assumed 'MT_RAND_PHP'

/Users/mburak/Dev/facebook-instant-articles-sdk-php/vendor/fzaninotto/faker/src/Faker/Generator.php:215
```

**Comment by fzaninotto** [comment]
Which is your precise PHP version?

**Comment by mburak** [comment]
I'm actually using HHVM with PHP7 compatibility... is there anything you think might work?

**Comment by fzaninotto** [comment]
It seems HHVM isn't really compatible with PHP7... And I don't want to try and support it. So, closing this issue.
