### ISSUE TITLE
Add kinder sentence in readme.md for beginners

### ISSUE THREAD

**Issue by chiroruxx** [fzaninotto/Faker#1311]
I think sample codes in [readme.md](https://github.com/fzaninotto/Faker/blob/master/readme.md) is hard to understand for beginners. Because the code of auto loading and creating a `Faker/Factory` instance is omitted from 2nd sample code in [Basic Usage](https://github.com/fzaninotto/Faker#basic-usage).

So, this adds kinder sentence before 2nd sample code. "After this sample code, they are omitted the code of auto loading and creating a `Faker/Factory` instance".

**Comment by fzaninotto** [comment]
I disagree: someone with basic PHP knowledge should be able to understand this. It's been the case for more than 5 years already.
