### ISSUE TITLE
Please rename the project to faker (lower case name) not upper case.

### ISSUE THREAD

**Issue by tuanphpvn** [fzaninotto/Faker#1324]
Use Faker name (uppercase) will lead to composer cannot recognize and add it to autoload class when run command: ```composer dumpautoload```.

Please change the name to faker (lower case instead)

**Comment by fzaninotto** [comment]
What? Is this a breaking change from composer or what. Faker has been properly working with composer for years now.

**Comment by tuanphpvn** [comment]
Here is steps to reproduce:
In the working dir ( my project)

Go to ```vendor/fzaninotto/```

```git clone https://github.com/fzaninotto/Faker.git```

Go back to working dir: I run ```php bin/console cache:clear``` => error occur (cannot find Faker class)

And I realize composer cannot recognize Faker ( in upper case)
I must manual change Faker -> faker
Run again and it works.

Please check even symfony project also use lower case as the name.

**Comment by fzaninotto** [comment]
this is not how to install yhe project, use composer not git.

**Comment by tuanphpvn** [comment]
Actually, composer will change Faker -> faker. Just a suggestion for other contributors contribute the project. Thank you for your time.
