### ISSUE TITLE
Not all the words in Lorem::$wordList are unique.

### ISSUE THREAD

**Issue by zhekaus** [fzaninotto/Faker#1329]
Look the duplicates:
Word	Count
et	11
ut	6
qui	6
aut	6
est	5
voluptatem	4
quia	4
voluptas	3
sed	3
sit	3
omnis	3
non	3
rerum	3
consequatur	3
vel	2
sint	2
velit	2
sunt	2
quo	2
nihil	2
molestiae	2
quis	2
eum	2
enim	2
id	2
eos	2
in	2
dolor	2
dolorem	2
dolores	2
autem	2
ea	2

**Comment by andysnell** [comment]
If you are using the provider for a single, random word, I can see where this might be a problem; however, wouldn't this be as expected when using the provider to generate fake sentences and paragraphs?  After all, you wouldn't expect an even distribution of words in real text -- you would expect a number of short words to show up many times as often as others.  Unless the word list is supposed to be unique, this seems to provide a more realistic result for a sample faked sentence or paragraph.

**Comment by fzaninotto** [comment]
That's not a bug, that' a feature™
