### ISSUE TITLE
Unique Word not always working

### ISSUE THREAD

**Issue by FabulousCo** [fzaninotto/Faker#1359]
I'm using these fakers in my tests coupled with factories.

I need an attribute to be unique so I did : `$faker->unique()->word;`

Which works fine 80% of the time. And somehow, sometimes it returns words that are not unique :/

Is this because of the provider "Word" that can't be unique or anything like that ? 
Shall I use userName instead of word ?

Thanks

**Comment by alexkart** [comment]
It works correctly for me, maybe you have different $faker in your tests.
Also, there are only 249 words (182 unique words) in `Lorem` class https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/Lorem.php#L7
You can't generate more than 182 unique words.

**Comment by FabulousCo** [comment]
Indeed ! I had a different faker instance !
I'm using faker in my tests and each test was create a new faker instance. I had to build a FakerGeneratorSingleton to make the unique helper work.

Issue closed
