### ISSUE TITLE
Provider not found

### ISSUE THREAD

**Issue by blueminded** [fzaninotto/Faker#1366]
Hi, there.

I'm trying to use a provider in my Laravel Project but It doesn't work. Any advice.

`"fzaninotto/faker": "^1.7",` this the version installed via Composer
 
This is the error:
`[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Faker\Generator\Provider\it_IT\Person' not found  `

and in the factory class:

`<?php

use Faker\Generator as Faker;

$factory->define(App\Code::class, function (Faker $faker) {

    $faker->addProvider(new Faker\Provider\en_ZA\Person($faker));

    return [
        'name'=>$faker->idNumber,
        'status'=>false
    ];
});
`
Any ideas what I'm doing wrong?

**Comment by svanpoeck** [comment]
Hi,

I don't know how you're trying to instantiate Faker, but as far as I can see, you never set the language.
Here's how I do it, no need to explicitly add any standard provider afterwards:

```
use Faker\Factory;
use Faker\Generator;

$faker = Factory::create('it_IT');
```
Then you can simply use the standard providers as such:
```
return [
    'name' => $faker->name,
    'status' => false
];
```
In the code above, `$faker->name` will actually invoke the `name()` method of the `Person` provider in the language you specified when setting up Faker through its Factory - `it_IT` in this case.

Also, as far as I know, only the `Person` providers for languages `en_ZA`, `ar_SA` and `mn_MN` provide the `idNumber` method. If you wish to have that method for your language, you should add it to the `Person` class of `it_IT` it and add a pull request on this repository.

HTH,
Steven

**Comment by fzaninotto** [comment]
I suggest you ask the Laravel people, I don't know how their factory system works.
