### ISSUE TITLE
Missing phpDoc arguments for certain formatters

### ISSUE THREAD

**Issue by willemo** [fzaninotto/Faker#1367]
In the phpDoc for the `Faker\Generator` class some formatters are missing. For now I'm missing the `secondaryAddress` and `state` formatters, but more might be missing.

**Comment by fzaninotto** [comment]
That's because only the formatters expected to be found in all languages are included. Otherwise, your IDE would suggest methods that don't exist for your locale.

**Comment by willemo** [comment]
Ah alright, that makes sense. Thanks for the quick reply!
