### ISSUE TITLE
Regexify doesn't work

### ISSUE THREAD

**Issue by John6985** [fzaninotto/Faker#1377]
Hello,
First of all thanks for this faker library it saves me a lot of time :)
So I have an issue when I use the function regexify :

`$faker = Faker::create('fr_FR');
echo $faker->regexify('[A-z0-9]');`

my result : "Z^_`abcdefghijklmnopqrstuvwxyz0123456789]"

Thanks for all.

**Comment by John6985** [comment]
Ok I change the regex by this '[A-Za-z0-9]' and it works !!!

**Comment by fzaninotto** [comment]
I can live with this limitation.

**Comment by svanpoeck** [comment]
FYI, the seamingly erroneous reported result for `[A-z0-9]` is the expected result, not an error or limitation.

From  : https://stackoverflow.com/a/4923397/1602497

> [A-z] will match ASCII characters in the range from A to z, while [a-zA-Z] will match ASCII characters in the range from A to Z and in the range from a to z. At first glance, this might seem equivalent -- however, if you look at this table of ASCII characters, you'll see that A-z includes several other characters. Specifically, they are [, \, ], ^, _, and `` ` (which you clearly don't want).
