### ISSUE TITLE
Allow Iterable Objects in `randomElement()`

### ISSUE THREAD

**Issue by browner12** [fzaninotto/Faker#1384]
is there a roadmap for Faker to eventually break off a PHP > 7.0 branch?

The reason I ask is I was looking into the `randomElement()` method and noticed it only accepts arrays.  I would love to make a PR so it accepts all iterables.  While I think it could be done in 5.6, there are some nice methods and type hints only available in 7.

curious so I know how to proceed. Thanks!

**Comment by fzaninotto** [comment]
No, there is no such roadmap.
