### ISSUE TITLE
Can't reliably use multiple instances 

### ISSUE THREAD

**Issue by Danonk** [fzaninotto/Faker#1388]
```
$first = FakerFactory::create();
$first->seed(69);

$second = FakerFactory::create();
$second->seed(69);

$first->randomNumber();  // 4015787
$second->randomNumber(); // 39868167
```

But `randomNumber()` results should be the same.

**Comment by fzaninotto** [comment]
This is because Faker uses `mt_rand`, which uses a singleton under the hood. It's not something we're going to fix.

**Comment by Danonk** [comment]
What's the problem?

Store the seed in an instance variable and use it when you're invoking `mt_rand()`.

**Comment by fzaninotto** [comment]
No, that would mean reseeding `mt_rand` before every call. If you know a way to do it, show me the code.
