### ISSUE TITLE
Feature: domainName with protocol

### ISSUE THREAD

**Issue by rossjcooper** [fzaninotto/Faker#1399]
Add a feature similar to `domainName` but with a random HTTP/HTTPS protocol appended to the domain name.

Would be happy to contribute to this feature if people think its worth it.

**Comment by fzaninotto** [comment]
IMO, it's so easy to do in userland that it's not worth adding to the core.

**Comment by elwinmartin** [comment]
I hope it's not too rude to comment here in support of this; I was surprised I couldn't generate a protocol specific URL. FTP, SFTP, and FTPS are commonly used and often require differentiation in our tests. I was about to open an issue and propose implementing it myself, as well.

**Comment by fzaninotto** [comment]
Don't worry, it's not too rude, but it's not enough to make me change my mind either.
