### ISSUE TITLE
binary boolean

### ISSUE THREAD

**Issue by spud** [fzaninotto/Faker#1438]
My MySQL database schemas usually make use of tinyint(1) as a boolean field, using integers instead of proper boolean values. For example, I have an `is_public` field that takes a 0 or 1 (or any non-zero tinyint for "true").

If I use the built-in "Name" guesser (mostly super useful!), all my `is_xyz` fields return the "boolean" formatter. This appears to return a _pure_ PHP boolean value, e.g. true or false, and I found that my code was throwing an Exception because the "is_public" field was **empty.** (The result of attempting to set it to boolean false).

Now, I know there are a number of ways around this particular problem, by either avoiding or overriding the default Guesser, but it occurred to me that a new "Miscellaneous" formatter:

`booleanInt`

that always return a 0 or 1 **as an integer** would be convenient. I can't be the only one casting boolean values to tinyint(1). (To clarify, for this particular project I'm bypassing my object setters and writing straight to the database, otherwise I would simply cast the value to integer in the setter method.)

Just a thought. I'd be happy to issue a proper pull request, but it seems trivial to implement, simply casting the return value of the existing "boolean" to an integer.

Is this the most efficient alternate solution otherwise?

$faker->randomElement(array(0,1));

**Comment by ppelgrims** [comment]
I'm not sure what you mean, wouldn't this work anywhere?
```php
(int) $faker->boolean(0); // 0
(int) $faker->boolean(100); // 1
(int) $faker->boolean; // 0 or 1
```
or
```php
intval($faker->boolean(0)); // 0
intval($faker->boolean(100)); // 1
intval($faker->boolean); // 0 or 1
```

**Comment by spud** [comment]
Yes, frankly, that should. I think the issue stems from that fact that my first use of Faker is to attempt a full ORM integration (using Propel as my example) for my own CMS. So rather than addressing every possible object property by hand, I relied on the handy **Name.php** guesser to do some of the guesswork for me, and it has a handler that catches all "is_xyz" field names and uses a "boolean" formatter to generate values. So all of my "is_xyz" fields (which I need to be "0" or "1") end up getting simple "true" or "false" values instead. And I thought to myself "I wish there were a built-in formatter that would return a simple 0 or 1 as an integer instead of true or false."

I was unwittingly lulled into some laziness by the convenience of `Name.php` which is sometimes useful, but I really should just roll my own...
