### ISSUE TITLE
Faker prone to random usage

### ISSUE THREAD

**Issue by lferro9000** [fzaninotto/Faker#1448]
```php
$faker = Faker\Factory::create();
$faker->seed(1234);

echo 'faker 1: ' .$faker->name . "\n"; // 'Jess Mraz I';

$faker = Faker\Factory::create();
$faker->seed(1234);
$a = random_bytes(10);
$b = rand(0,255);
$c = mt_rand(0,255);

echo 'faker 2: ' .$faker->name . "\n"; // 'Jess Mraz I';
```
I get as output:

faker 1: Miss Lorna Dibbert
faker 2: Carolyne Luettgen

Should faker be sensitive to random usage at all?

**Comment by fzaninotto** [comment]
yes, because Faker uses `mt_rand`, which relies on a global seed.

**Comment by lferro9000** [comment]
Yes, i noticed that, would be useful a PR to allow the injection of a random generator that isn't prone to that? (a plain procedural number generator)

**Comment by lferro9000** [comment]
I've read the contribution guidelines and this PR would break some of them, mainly:

Never use rand() in your providers. Faker uses the Mersenne Twister Randomizer, so use mt_rand() or any of the base generators (randomNumber, randomElement, etc.) instead.

Would need to be changed to:

Faker uses the Mersenne Twister Randomizer or the provided Randomizer.

Always use the base generators on your providers (randomNumber, randomElement, randomInRange, etc.).

And

"Speed is important in all Faker usages. Make sure your code is optimized to generate thousands of fake items in no time, without consuming too much memory or CPU."

would need to be added a warning:

"Speed is important in all Faker usages. Make sure your code is optimized to generate thousands of fake items in no time, without consuming too much memory or CPU."

"When using a custom Randomizer, the performance of Faker will be directly dependent on the Randomizer performance."

So not sure if such PR would be a good thing unless those changes are also acceptable.

I need to do some performance testing on this, by the look of it.

**Comment by fzaninotto** [comment]
No, implementing another randomizer is outside of the scope of Faker.

**Comment by lferro9000** [comment]
Okie. Fair enough :)
