### ISSUE TITLE
Incorrect string value in russian language

### ISSUE THREAD

**Issue by RomanKolosov** [fzaninotto/Faker#1458]
Hello!

Sometime I have error

>  SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD1.' for 
> column 'seo_keywords' at row 1

Fixed this please.

**Comment by ppelgrims** [comment]
You probably need utf8mb4 instead of utf8?

**Comment by RomanKolosov** [comment]
@ppelgrims I use mysql with utf8 and utf8_general_ci collation

**Comment by ppelgrims** [comment]
I reckon you should use `utf8mb4` and `utf8mb4_unicode_ci`. This has to do with character encoding and not with Faker.

**Comment by RomanKolosov** [comment]
@ppelgrims Ok, thank you. I change collation
