### ISSUE TITLE
conditional fake data (e.g. postcode change in Ireland)

### ISSUE THREAD

**Issue by LegendOfGIT** [fzaninotto/Faker#1464]
I was wondering if there is a need of conditional fake data.

E.g.:
The postcode of Ireland was recently adjusted to another format.

If you want to create fake data with correct formatting of postcode before and after adjustment, there is currently no proper way to do that without injecting a custom provider.

I thought about that issue.
There would be a way to deal with it.
My solution goes like that:
Each item in an fake data array can either be a simple string or an instance of a class implementing a new interface "FakeDataItemInterface".
In this interface you handle additional information like "validFromDate".
The base class than would inspect every item of an fake data array and checks if items with the new interface are valid.
If this is the case, the value of the item will be considered for random returning.

**Comment by fzaninotto** [comment]
That's a nice idea for your code, but too much indirection for the Faker core IMO. I'll leave that to userland.
