### ISSUE TITLE
Doctrine entity population for large amount of data hits memory limit

### ISSUE THREAD

**Issue by buffcode** [fzaninotto/Faker#1471]
Currently the Doctrine populator (probably also the other populators) holds all generated entities in a variable while executing. When generating real life test data (in terms of object amount) we hit memory limits quite fast.

One possible workaround would be to replace the entity with a more lightweight Reference/proxy object.

Another workaround:
Using DoctrineFixturesBundle one could use the `--append` flag in order to create multiple batches of data. But splitting the generation into multiple fixtures won't help as the associations won't pick up data from previous batches. So I cannot run `--append` 100 times for 1.000 products resulting in 1.000.000 entities and then another run for just orders containing random (existing) products.

Any ideas?

**Comment by tomzx** [comment]
How much RAM are we talking about? Could you provide an example snippet of code of your use case?

**Comment by pimjansen** [comment]
@buffcode the memory limit hit due the generation or due to object size? I expect the last bit which is a bit how `Doctrine` works. We could make a choice to flush on specific batch sizes instead of the total size
