### ISSUE TITLE
Generator For Random Path Names

### ISSUE THREAD

**Issue by kiler129** [fzaninotto/Faker#1472]
It will be great to add static Unix/Windows paths generator without actually manipulating any files.

WDYT?

**Comment by buffcode** [comment]
How about:
```php
// paths
var_dump($faker->bothify('?:\\') . implode('\\' ,$faker->words($faker->numberBetween(0, 4))));

// filenames
var_dump($faker->regexify('[0-9a-zA-Z]{1,32}\.\w{3}'));
```

Output:
```
string(15) "m:\fugiat\rerum"
string(21) "22Etmm4eXSF1a9A7C.aje"
```

**Comment by tomzx** [comment]
@buffcode Could be interesting to see support for spaces and "special characters" :wink:

**Comment by fzaninotto** [comment]
Nice idea! However, we won't add it to the core, so I suggest you make it a standalone package, and open a PR here to add your package to the README.

**Comment by thorne51** [comment]
@marjetika Sorry I've been a bit busy. I'll try to finalize sometime this week in-between packing and moving :)

@fzaninotto Did you mean for me to create a separate 3rd party library like https://github.com/tamperdata/exiges?
