### ISSUE TITLE
French mobile number : +33 7 {{phoneNumber07WithSeparator}}

### ISSUE THREAD

**Issue by camlafit** [fzaninotto/Faker#1481]
Hello

Some error occurs with this code 
```
    $faker = Faker\Factory::create('fr_FR');
    echo  $faker->mobileNumber;
```

In some case, I get as result :  **+33 7 {{phoneNumber07WithSeparator}}**

Thanks :)

**Comment by ppelgrims** [comment]
I'll make a PR for this

**Comment by ppelgrims** [comment]
Already fixed by #1343

**Comment by camlafit** [comment]
Thanks to have see this issue.

Then is not available from composer download. Last release is august 2017 and patch looks done in november.
Maybe is time to propose a new release :)

thank alot

**Comment by ppelgrims** [comment]
see #1391
