### ISSUE TITLE
lorempixel.com has been down since 8am UTC - there should be a plan 'b'!

### ISSUE THREAD

**Issue by ChangePlaces** [fzaninotto/Faker#1484]
Could it be possible to:

- generate random images locally
- use another placeholder site silently
- dynamically create placeholder images

**Comment by kp-syginteractiveAU** [comment]
+1 for using picsum.photos as a backup. Just change the $baseUrl value in Faker/Provider/Image.php

**Comment by ChangePlaces** [comment]
I think it'd be better if there was an image generator in faker. It's faster and doesn't rely on any external sites.

**Comment by ChangePlaces** [comment]
@eriwin yep, from two years ago

**Comment by brunogaspar** [comment]
Seems that lorempixel.com is up again, however, very slow and not sure for how long it will be up.

Will be awesome to get @fzaninotto input on how he would prefer to proceed with solving this issue, either by using a different service or something else.

**Comment by ChangePlaces** [comment]
@tomzx  yes, that's exactly what i'm using atm. it's so simple something like it should be in faker. Perhaps even something more simpler, like just "image width x image height" as the text

**Comment by fzaninotto** [comment]
See my comments in #957

**Comment by kandrejevs** [comment]
It is down again
