### ISSUE TITLE
Incorrect names 

### ISSUE THREAD

**Issue by ahmadzissa** [fzaninotto/Faker#1500]
Hello, I noticed the system product incorrect names like 

1-hoppe zelma
2- trop jess
3- jaskoilski zackary 

it start with family names instead of first names

The names are back to front sometimes 

I'm using this code 

```php
private function get_fake_name($shop_options)
	{
		$faker             = Factory::create();
		$faker_options = $shop_options->fake_names_type;
		switch ($faker_options){

			case ($faker_options == 1):
				return $faker->userName;
				break;
			case ($faker_options == 2):
				return $faker->firstNameFemale.'.'.$faker->lastName;
				break;
			case ($faker_options == 3):
				return $faker->firstNameMale.'.'.$faker->lastName;
				break;
			case ($faker_options == 4):
			return $faker->firstName.'.'.$faker->lastName;
			break;
			default:
				return $faker->firstName.'.'.$faker->lastName;
				break;
		}
	}
```

> return $faker->firstName.'.'.$faker->lastName;

**Comment by fzaninotto** [comment]
What's your locale?

**Comment by ahmadzissa** [comment]
I'm using default names for US 

and noticed this happen  only  with usernames

**Comment by ahmadzissa** [comment]
Thank you for replying  once I get another report from my customers  I will check further in the issue since I know where to search now. 

I will gather more details and inform you if there's an issue. 
I wish you can close the report for now.

Thank you
