### ISSUE TITLE
ORM Entities Hints

### ISSUE THREAD

**Issue by kiler129** [fzaninotto/Faker#1501]
From what I see you can “hint” unrecognized fields found in entities manually generating dat. I wonder if there is some helper (or maybe we can add one?) which allows hinting which type of data  we expect to be faked in a field inside of the entity object itself?

**Comment by pimjansen** [comment]
@kiler129  i would like you to ask to raise question about `Faker` directly on Stackoverflow with labels like `faker` and `php`. Since there is not a real bug here i will close this issue.
