### ISSUE TITLE
Feature(Faker): add a feature to generate unique email.

### ISSUE THREAD

**Issue by m-amr** [fzaninotto/Faker#1502]
### Problem

We have used faker to generate fake data for testing and we faced the following issue
we generate a fake email and try to create user in the testing database and the email must be unique but sometimes faker generate an email which was generated before cause the testing to fail.

### Solution

We solved the issue by appending a random hash to the email. so if someone else think that this will be a good feature we can introduce a new param to force the faker to return unique email based on the developer request like 

```php

$faker = Faker\Factory::create();

echo $faker->uniqueEmail;

```

**Comment by ppelgrims** [comment]
Did you check out [modifiers](https://github.com/fzaninotto/Faker#modifiers)?

```php
$faker = Faker\Factory::create();

echo $faker->unique()->email;
```

**Comment by fzaninotto** [comment]
Yep, `unique()` is the way to go.
