### ISSUE TITLE
Data with seed has changed

### ISSUE THREAD

**Issue by trasher** [fzaninotto/Faker#1509]
I was using faker on commit c3f82846fdfd1760b277767ac21426ca030f795e (I know it's quite old) and I've tried to update to 28e848bc077a202c6a17ecc8e8f299d629c188f7

I'm using a fixed seed for my project's unit tests; and it seems something has changed in generated data (if I understand well, using a seed should prevent this).

Here is the code where the problem happens:
```php
$faker->optional(
    $weight = 0.3,
    $default = Status::DEFAULT_STATUS
)->randomElement($this->status)
```

I don't know if there are other issues; since my unit tests are broken :( And since the result is not tested directly, it's hard to know what exactly has changed (but I can investigate if it may helps, of c ourse).

Thank you.

**Comment by ppelgrims** [comment]
I'd say use `git diff 28e848b c3f8284 src/Faker/Provider/Base.php`, which defines `optional` and `randomElement`:
```diff
diff --git a/src/Faker/Provider/Base.php b/src/Faker/Provider/Base.php
index 45568d0..d314be7 100644
--- a/src/Faker/Provider/Base.php
+++ b/src/Faker/Provider/Base.php
@@ -168,19 +168,9 @@ class Base
      *
      * @return array New array with $count elements from $array
      */
-    public static function randomElements($array = array('a', 'b', 'c'), $count = 1, $allowDuplicates = false)
+    public static function randomElements(array $array = array('a', 'b', 'c'), $count = 1, $allowDuplicates = false)
     {
-        $traversables = array();
-
-        if ($array instanceof \Traversable) {
-            foreach ($array as $element) {
-                $traversables[] = $element;
-            }
-        }
-
-        $arr = count($traversables) ? $traversables : $array;
-
-        $allKeys = array_keys($arr);
+        $allKeys = array_keys($array);
         $numKeys = count($allKeys);
 
         if (!$allowDuplicates && $numKeys < $count) {
@@ -201,7 +191,7 @@ class Base
                 $keys[$num] = true;
             }
 
-            $elements[] = $arr[$allKeys[$num]];
+            $elements[] = $array[$allKeys[$num]];
             $numElements++;
         }
 
@@ -216,7 +206,7 @@ class Base
      */
     public static function randomElement($array = array('a', 'b', 'c'))
     {
-        if (!$array || ($array instanceof \Traversable && !count($array))) {
+        if (!$array) {
             return null;
         }
         $elements = static::randomElements($array, 1);
```

What does `$this->status` return?

**Comment by fzaninotto** [comment]
Depending on the locale, this may come from the addition of more test data, or the removal of wrong test data. We know that these changes have a negative impact, so we only do them when it's really necessary (e.g. offensive words, or too low entropy).

Which locale are you using?

**Comment by trasher** [comment]
Hello, thanks for your answers.

@ppelgrims on both commits, `$this->status` is the following array:
```php
array(10) {
  [0] =>
  int(1)
  [1] =>
  int(10)
  [2] =>
  int(2)
  [3] =>
  int(3)
  [4] =>
  int(4)
  [5] =>
  int(5)
  [6] =>
  int(6)
  [7] =>
  int(7)
  [8] =>
  int(8)
  [9] =>
  int(9)
}
```

@fzaninotto yes, I know this may change with tests data. For the case, I'm just updating the lib, so tested data should not change.
According to `\Locale::getDefault()`; locale is set to "fr_FR" with both commits.

**Comment by fzaninotto** [comment]
Right. then I don't see why the changes reported by @ppelgrims can modify the results. 

Are you sure the problems come from that place? I suggest another cause: earlier in your program, you call a formatter which uses a loop to pick a valid output. If this formatter has changed, the loop duration potentially changed, so the random numbers generated after this loop are different, even if you use the same seed.

**Comment by trasher** [comment]
It may be possible the issue is caused from an earlier call. I do not have time to investigate right now, but I will do as soon as possible.

**Comment by pimjansen** [comment]
@trasher any update on this?

**Comment by trasher** [comment]
Sorry, no; I did not have time to investigate on that issue :/

**Comment by pimjansen** [comment]
@trasher any update when you do?

**Comment by trasher** [comment]
No idea, but to be honest I do not think I'm going to spend time on this.
I'll try again later if needed, and adapt my tests.

Thanks all for your help :)
