### ISSUE TITLE
$faker->unique()->numberBetween(1, 20)

### ISSUE THREAD

**Issue by datner** [fzaninotto/Faker#1512]
Hey! A very wierd problem I've encountered.

I'm using Laravel and I have 2 factory states: `user`  and `post`.
I generate **20** users, and **50** posts. 
Now the interesting part, here are the 2 states, redundent code removed:
User:
```PHP
factory(App\Photo::Class, 20)->states('user')->create();
```
```PHP
$factory->state(App\Photo::class,'user', function (Faker $faker) {
    return ([
        'imageable_id' => $faker->unique()->numberBetween(1,20),
        'imageable_type' => 'App\User'

    ]);
});
```
Post:
```PHP
factory(App\Photo::Class, 50)->states('post')->create();
```
```PHP
$factory->state(App\Photo::class,'post', function (Faker $faker) {
    return ([
        'imageable_id' => $faker->unique()->numberBetween(1,50),
        'imageable_type' => 'App\Post'

    ]);
});
```
You'd think that everything would work, but no matter how many times I try,
I get ` OverflowException  : Maximum retries of 10000 reached without finding a unique value
`
Not on both, only on user. Post works perfectly fine every time 100% of the time generating the range between 1 to 50.
User on the other hand fails.

I am either really dumb and can't find whats wrong, or something fails in the internal logic

**Comment by fzaninotto** [comment]
Can you try if they test both in isolation?

**Comment by ppelgrims** [comment]
```php
>>> $faker->unique()->numberBetween(1, 20)
=> 5
>>> $faker->unique()->numberBetween(1, 20)
=> 13
>>> $faker->unique()->numberBetween(1, 20)
=> 11
>>> $faker->unique()->numberBetween(1, 20)
=> 1
>>> $faker->unique()->numberBetween(1, 20)
=> 2
>>> $faker->unique()->numberBetween(1, 20)
=> 19
>>> $faker->unique()->numberBetween(1, 20)
=> 6
>>> $faker->unique()->numberBetween(1, 20)
=> 16
>>> $faker->unique()->numberBetween(1, 20)
=> 8
>>> $faker->unique()->numberBetween(1, 20)
=> 10
>>> $faker->unique()->numberBetween(1, 20)
=> 7
>>> $faker->unique()->numberBetween(1, 20)
=> 14
>>> $faker->unique()->numberBetween(1, 20)
=> 17
>>> $faker->unique()->numberBetween(1, 20)
=> 15
>>> $faker->unique()->numberBetween(1, 20)
=> 3
>>> $faker->unique()->numberBetween(1, 20)
=> 20
>>> $faker->unique()->numberBetween(1, 20)
=> 18
>>> $faker->unique()->numberBetween(1, 20)
=> 9
>>> $faker->unique()->numberBetween(1, 20)
=> 4
>>> $faker->unique()->numberBetween(1, 20)
=> 12
>>> $faker->unique()->numberBetween(1, 20)
OverflowException with message 'Maximum retries of 10000 reached without finding a unique value'
```
Are you using this in a loop or so?

**Comment by jeffwhite-619** [comment]
To the unique() method I tried passing false for $retry and 50000 for $maxRetries, but keep getting the error that Maximum retries of 10000 reached without finding a unique value. I have the memory limit high enough to handle it.

**Comment by fzaninotto** [comment]
If you ask an integer value between 1 and 20, no matter how many retries you allow, you're guaranteed to hit a wall after generating 20 values.

**Comment by datner** [comment]
The problem is that when you try and get 20 values between 1 and 20
(including) and you can only fetch 19. The 20th number will never pass the
unique() validation. The odd thing is that getting 50 numbers between 1 and
50 does not yield the same problem. I've only found this to happen between
1 and 20

**Comment by jeffwhite-619** [comment]
My issue is with word, catchPhrase(), and text(). There should be plenty of permutations in lorem ipsum, even if you limit text to 100 chars. I'm about to resort to an old phonetic password algorithm I found in an old issue of 2600.

**Comment by iamriajul** [comment]
### Solved
**Do this: $faker->unique(true)->numberBetween(1, 50)**
The first parameter of unique is 'reset'

**Comment by deleugpn** [comment]
What does the `reset` mean in the unique method?

**Comment by ekaranja306** [comment]
> What does the `reset` mean in the unique method?

I think its because when you run the first instance of unique, for instance `$faker->unique()->numberBetween(1, 20)` then run it in another factory, laravel kinda extends the previous instance, if that makes sense.
But when you pass `true` like `$faker->unique(true)->numberBetween(1, 20)` it starts searching from `1 to 20` again
