### ISSUE TITLE
add fake information "salutation"

### ISSUE THREAD

**Issue by LegendOfGIT** [fzaninotto/Faker#1513]
Hey there,

at the moment the information "salutation" and "title" are mixed within the fake information "title".

In my opinion, live for developers would be much easier if the fake information "title" only contains titles like "dr., prof., dr. med., ..." and a new fake information contains salutations like "mr., mrs., madam, ..."

**Comment by fzaninotto** [comment]
Hi there,

Nice suggestion. But the added complexity (and BC break) makes it not worth the change.

**Comment by LegendOfGIT** [comment]
The structure of this project is a piece of ........
