### ISSUE TITLE
Literal parentheses not outputting with regexify

### ISSUE THREAD

**Issue by marcost5m** [fzaninotto/Faker#1523]
Doing something like this in a model factory in Laravel; I can't get the parentheses to output:

`$faker->unique()->regexify('\(\d{3}\) \d{3}-\d{4}')`

**Comment by ppelgrims** [comment]
That might be solved with #1515

**Comment by icanhazstring** [comment]
Sadly, even with #1515 this problem is not solved.
The parentheses are still not printed.

**Comment by icanhazstring** [comment]
@localheinz @pimjansen using this code above opens a new issue.
Seems like the old `array_replace(['(', ')', '', ...])` did solve a some misconfigured regexify calls.

For example:
`Provider/fr_FR/PhoneNumber.php:117`

The regex here is totally screwed:
```
$regex = '([012]{1}\d{1}|(9[1-357-9])( \d{2}){3}';
                         ^- this parentheses is too much here, since the test matches it without it
```

As mentioned, the old code did "fix" it behind the scenes.

**Comment by icanhazstring** [comment]
@fzaninotto think we can close this one as well.
