### ISSUE TITLE
Fix pls ukraine name person you have a space at the beginning of the name

### ISSUE THREAD

**Issue by Yasuslik** [fzaninotto/Faker#1524]
in file "Faker/src/Faker/Provider/uk_UA/Person.php"

![screenshot_42](https://user-images.githubusercontent.com/37928986/42559723-9f395a7e-84fd-11e8-8f17-70d6003c98ae.png)

Thank you

**Comment by ruslanQA** [comment]
I create pull requests https://github.com/fzaninotto/Faker/pull/1525
