### ISSUE TITLE
Cannot fake imageUrl from https://lorempixel.com/

### ISSUE THREAD

**Issue by nguyenphuocnhatthanh** [fzaninotto/Faker#1543]
Maybe https://lorempixel.com/ die . We should set custom url for fake imageUrl
Example:
imageUrl($width, $height, 'cats', true, 'Faker', true, $fromUrl)

**Comment by HarmlessEvil** [comment]
Same problem. It seems, that Lorem Pixel is broken. Maybe, we should use an alternative for now - [Lorem Pixum](https://picsum.photos), it has almost similar API

**Comment by nguyenphuocnhatthanh** [comment]
I think PR:https://github.com/fzaninotto/Faker/pull/1542 that resolve problem :)

**Comment by Necko1996** [comment]
@fzaninotto when will we see some progress in this field?
Lorempixel is broken site...

**Comment by pavels-hyuna** [comment]
@Necko1996, https://github.com/fzaninotto/Faker/issues/957

**Comment by Necko1996** [comment]
@pavels-hyuna ye I saw that. Developers must do something about that because now it's not working and face a lot of problems...

**Comment by pablorsk** [comment]
*lorempixel* site is back. This issue can be closed.

Maybe, #1557 is a good idea for prevent issue like this, #1484, #1503 and #957.
