### ISSUE TITLE
AT Postcodes - Some of the values are not valid

### ISSUE THREAD

**Issue by tniemann** [fzaninotto/Faker#1544]
Hi,

i used fixtures for addresses in different countries. But the provided post code for Austria has in some cases a leading zero like 0476 which is not valid. Austrian post codes does start with 1-9 and not with 0. Is there a fix for that?

Regards
Thomas

**Comment by mpge** [comment]
Added a fix for this. Although, I did notice Austrian postal code rules aren't completely being followed, see: https://en.wikipedia.org/wiki/List_of_postal_codes_in_Austria

I put a simple fix (limiting first number from 1-9), todo should be to implement rules on the aforementioned wiki link.

**Comment by tniemann** [comment]
Thx.

**Comment by localheinz** [comment]
Shall we close this issue as #1545 has been merged?

We can still follow up with stricter post code generation if we can.

**Comment by pimjansen** [comment]
Agree
