### ISSUE TITLE
Allow Generation of Countries Without Uninhabited Regions

### ISSUE THREAD

**Issue by kiler129** [fzaninotto/Faker#1554]
It will be very useful to add option to countries generator to exclude uninhabited countries. Projects like e.g. Symfony Intl (which is used by validators) are [already doing that by default](https://github.com/symfony/symfony/blob/528eef336bddc276b3d3ad9344f6fa6ddf9ac486/src/Symfony/Component/Intl/Data/Generator/RegionDataGenerator.php#L49-L51) which is [indeed intentional and expected](https://github.com/symfony/symfony/issues/18263).

Setting this as default may be seen as a breaking change, however I think adding parameter to generators is feasible. 

WDYT?

**Comment by ppelgrims** [comment]
They are filtered out by key, so it's language agnostic (the label can be translated) but in this package all the `$country` attributes are values without keys. So in addition to the filter, each attribute would have to be updated across each language as well?
