### ISSUE TITLE
Please add my picsum.photos provider to Third-Party Libraries list

### ISSUE THREAD

**Issue by bluemmb** [fzaninotto/Faker#1557]
I have written a picsum.photos provider, since lorempixel works slow or gets down recently that is mentioned in  #1484 , #1503 , #957.

I'd be glad If you'd add this provider to the Third-Party Libraries list.

[Faker-PicsumPhotos](https://github.com/bluemmb/Faker-PicsumPhotos)

Thanks in advance.

**Comment by standaniels** [comment]
See [#957](https://github.com/fzaninotto/Faker/issues/957#issuecomment-231672453), so chances are it will not be added.

You could create images locally instead, for example by using this [image generator](https://github.com/standaniels/image-generator). This way you're never dependent on an external service.

**Comment by bluemmb** [comment]
@standaniels Thanks and Nice job. Yes, I have seen that he has planned to remove it. 

But even in case real images are out of official support, It still can be provided by third parties as extra feature and have the developers to accept the downsides of it. I don't see any problem with it.

Also as a developer I see that it is a very good decision and I can live with it. But you know, when it comes to the project owner that only knows the UI to understand and accept what you are doing during the writing of his website or app, it is hard to make him understand a page of artistic pictures than a page of real life pictures.

**Comment by ppelgrims** [comment]
Can you make a PR to add it to the list of third party providers?
