### ISSUE TITLE
Using faker with VRT

### ISSUE THREAD

**Issue by dondmcg** [fzaninotto/Faker#1585]
Francois et al,
I am trying to use Visual Regression Testing on a project that uses faker.  The problem is when we run a build faker generates different text strings, which is great for dev but when the VRT process is comparing the pre-build to the post-build there are many differences, too many to check.  So I need a way to secure the same non-random generation for specific builds.

I found this https://www.npmjs.com/package/faker#setting-a-randomness-seed which indicates there is a way to pass in a hardcoded number to get the faker process to produce identical results.

I use patternlab in a drupal enviro and have a php file created by a David Olsen that adds faker support to Pattern Lab for patternData.dataloaded and it runs a method when this is called to create faker data.

I plan to figure out how to pass in the hardcoded random seed number on patternData.dataloaded when the build is a VRT build.

Do you have any advice on how to implement a solution or is there anything built in I can leverage or am I on the completely wrong track?

**Comment by fzaninotto** [comment]
Hi,

You're on the right track (seeding the generator), but I have no idea how you can do it in your Drupal stack. If you cant find the answer, I suggest you use Faker directly, and not through another third-party library!
