### ISSUE TITLE
Deprecated  $schema->column in CakePHP

### ISSUE THREAD

**Issue by gus0074** [fzaninotto/Faker#1616]
Hello @fzaninotto, sorry I'm a newbie, CakePHP throw an error loop. Fixed it changing line 45 in:
cakephp\your-project\vendor\fzaninotto\faker\src\Faker\ORM\CakePHP\ColumnTypeGuesser.php
from:
$columnData = $schema->column($column);
to:
$columnData = $schema->getColumn($column);

**Comment by icanhazstring** [comment]
@pimjansen @localheinz could be closed then with #1777 merged
