### ISSUE TITLE
$faker->numberBetween return wrong minimum and maximum value

### ISSUE THREAD

**Issue by adrian-zawada** [fzaninotto/Faker#1632]
Hello!
In my loop i defined max value for loop and method numberBetween return bad value of records. I don't now why because loop construction is very simple. 

```
$max_pages_per_user = 5;
$max_tags_per_page = 3;

for ($page_id = 1; $page_id <= $faker->numberBetween($min = 1, $max = $max_pages_per_user); $page_id++) {
	
	DB::table('pages')->insert([
		'user_id' => $user_id,
		'title' => $faker->sentence($nbWords = 2, $variableNbWords = true),
		'content' => $faker->paragraph($nbSenteces = 2, $variableNbSentecens = true),
		'created_at' => $faker->dateTimeThisYear($max = 'now'),
		]);

for ($tag_id = 1; $tag_id <= $faker->numberBetween($min = 1, $max = $mag_tags_per_page); $tag_id++) {
	
        DB::table('tags')->insert([
		'page_id' => $page_id,
		'content' => $faker->colorName,
		'created_at' => $faker->dateTimeThisYear($max = 'now'),
		]);

	    } // tags loop
	
} //pages loop
```

As a result, he receives 10 tags for the first page for the next 8 tags for the next few and the last number of tags equals 0. Why result is wrong?

**Comment by amarjitsingh52922** [comment]
i think there is typo in your 2nd for loop

for ($tag_id = 1; $tag_id <= $faker->numberBetween($min = 1, $max = $mag_tags_per_page); $tag_id++) {

$max = $mag_tags_per_page// should be $max_tags_per_page

**Comment by pimjansen** [comment]
I will close this ticket due to inactivity and solution above
