### ISSUE TITLE
Suggestion: being able to generate questions! No? :)

### ISSUE THREAD

**Issue by andreasba** [fzaninotto/Faker#1638]
Hi there

first of all thanks for this extremely valueable library, it really helps a lot.

I have one time remark though: there seems to be no possibility to create fake questions out of Lorum or realText.

Why is that? I think this is a missing piece, if I might suggest this :)

Thanks
Andreas

**Comment by fzaninotto** [comment]
I think the average developer can add a question mark, so no, thanks.
