### ISSUE TITLE
README example should show PSR-4 autoloader instead of PSR-0

### ISSUE THREAD

**Issue by prahladyeri** [fzaninotto/Faker#1657]
I've observed that in `composer.json` you have configured auto-loader to `PSR-4` standard, yet the comment in README.md example suggests using `PSR-0` compliant autoloader:

```
// require the Faker autoloader
require_once '/path/to/Faker/src/autoload.php';
// alternatively, use another PSR-0 compliant autoloader (like the Symfony2 ClassLoader for instance)

```
Perhaps, the require should read something like this in case of PSR-4?

`require_once 'vendor/autoload.php';`

**Comment by Dzhuneyt** [comment]
Your request is not quite clear. Could you elaborate?

**Comment by prahladyeri** [comment]
Its too old, I've almost forgotten PHP since then lol! But from what I remember, there are different PSR standards for importing the auto-loader classes (PSR-0 & PSR-4 are most common). I think the one standard you are actually using in code differs from what you've provided in the example in `README.md` page (or at least did in February when I'd raised that bug).

But as I said, I may have mistaken. I've moved on to Python since then, so don't quite recall about this bug.

**Comment by Dzhuneyt** [comment]
The readme now states:

> // require the Faker autoloader
> require_once '/path/to/Faker/src/autoload.php';
> // alternatively, use another PSR-4 compliant autoloader

So I think this issue is no longer valid. Could be closed @fzaninotto @webr.

**Comment by pimjansen** [comment]
Lets review the docs since it should explain both. Its recommended overall to load the composer autoloader but both should be possible

**Comment by pimjansen** [comment]
PR create:
https://github.com/fzaninotto/Faker/pull/1780

**Comment by pimjansen** [comment]
#1780 https://github.com/fzaninotto/Faker/pull/1780
