### ISSUE TITLE
There is no 'Company::catchPhrase' for ru_RU locale

### ISSUE THREAD

**Issue by axklim** [fzaninotto/Faker#1667]
There is no 'Company::catchPhrase' for ru_RU locale

![image](https://user-images.githubusercontent.com/12901433/53658224-44804380-3c69-11e9-9ceb-7ce200835956.png)

**Comment by axklim** [comment]
https://github.com/fzaninotto/Faker/pull/1668

**Comment by fantomiks** [comment]
Good job, I need it too!

**Comment by fzaninotto** [comment]
Fixed by #1668
