### ISSUE TITLE
[Help needed] Will I be able to use this in my procedural project ? 

### ISSUE THREAD

**Issue by abrhambas01** [fzaninotto/Faker#1670]
I just came back coding to procedural PHP and I want to know how do you run it, this is  my whole directory image

![image](https://user-images.githubusercontent.com/12043306/53693079-f177cf00-3dd5-11e9-8974-d3bc73c4fcbb.png)

**Comment by fzaninotto** [comment]
Hi, I suggest you ask your question on StackOverflow instead. This is more searchable, and it helps me focus my work on solving issues in the library.
