### ISSUE TITLE
[proposal] Remove BV and HM country codes.

### ISSUE THREAD

**Issue by oliverpool** [fzaninotto/Faker#1685]
I use the country-list from https://github.com/umpirsky/country-list, and my tests randomly fail because of 2 unrecognized country codes: `BV` & `HM` (https://github.com/umpirsky/country-list/issues/52).

[According to the Symfony sources](https://github.com/symfony/intl/blob/b79b8efab454ee088857df98467fd5b85f8f08b7/Data/Generator/RegionDataGenerator.php#L52), they are `Uninhabited islands`, hence blacklisted.

Would it be somehow possible to account for this? (either remove them, or add an `nonBlacklistedCountryCode` generator, or..?)

**Comment by Dzhuneyt** [comment]
Agreed on this one. There's no reason to keep these 2 codes.

**Comment by pimjansen** [comment]
@oliverpool can you raise a PR with the removal? If not let me know so i can handle it upcoming week
