### ISSUE TITLE
[personal] cloning problems

### ISSUE THREAD

**Issue by Khazhinov** [fzaninotto/Faker#1691]
$ git clone https://github.com/fzaninotto/Faker.git
Cloning into 'Faker'...
remote: Enumerating objects: 15597, done.
error: RPC failed; curl 56 OpenSSL SSL_read: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac, errno 0
ffatal: The remote end hung up unexpectedly
atal: early EOF
fatal: index-pack failed

all other repositories on github are fine

**Comment by Khazhinov** [comment]
yesterday everything worked 😄

**Comment by fzaninotto** [comment]
Sorry, this is a GitHub issue.

**Comment by Khazhinov** [comment]
ok, sorry
