### ISSUE TITLE
Allow nested formatters in token templates

### ISSUE THREAD

**Issue by jon-ht** [fzaninotto/Faker#1693]
Hi,

WDYT about the ability to use nested formatters ?

What I'm thinking of is to define template strings like the following in custom providers

 `'{{sentence({{numberBetween(1, 5)}}, true)}}'`

I've implemented my own by overriding default [Generator](src/Faker/Generator.php). It looks like this

<details>
<summary>Generator.php</summary>

```php
<?php


namespace App\DataFixtures\Faker;


class Generator extends \Faker\Generator
{
    /**
     * Replaces tokens ('{{ tokenName }}') with the result from the token method call
     * It's also possible to use nested tokens :
     * {{ tokenName({{ tokenName2(1, {{ tokenName3(2, 5) }}) }}, true) }}
     * {{ tokenName({{tokenName2(1, 5)}}, true) }}
     *
     * @param  string $string String that needs to bet parsed
     * @return string
     */
    public function parse($string)
    {
        return preg_replace_callback(
            '/(?<expr>\{\{\s?(?<format>\w+)\s?(?:\((?<params>(?:[\w,\s]|(?P>expr))+)\))?\s?\}\})/u',
            [$this, 'callFormatWithMatches'],
            $string
        );
    }

    protected function callFormatWithMatches($matches)
    {
        if ($matches['params'] ?? false) {
            $arguments = preg_split('/(\s?,\s)+/',$this->parse($matches['params']));
        }

        return $this->format($matches['format'], $arguments ?? []);
    }

}
```
</details>

You can also find some [tests](https://regex101.com/r/B6FlC9/2/tests)

**Comment by pimjansen** [comment]
@jon-ht it looks fun but what is the actual use case for it? Since can't come up with any at this point which means it will make it pretty complex.

**Comment by jon-ht** [comment]
Hi @pimjansen

If I remember right, it was to allow something like this :

I have a custom provider named `Notice` which defines `noticeContent` formatter. It generates random text content with nested formatters. Example :

```yml
# File definition for my fixtures
App\Entity\Notice:
    notice_html_content_{1..20}:
        content: <noticeContent()>
```

As said before, `noticeContent` have its own logic and calls other formatters. One of this formatters might returns something like :
```
{{ name }}, {{ toLower({{ noticeFamilyMembers(1, true) }}) }}
```

So, in this case, I need to call `$this->generator->parse($content)` to be sure that substrings are well parsed, otherwise, I will get the string above as notice content and I that's not what I'm expecting.

I don't know if it's clear enough to you. If you need more info, I could try to go back on the project needing that feature

**Comment by pimjansen** [comment]
@fzaninotto @localheinz what are your thoughts about something like this? Will not be an enhancement right now but maybe for the future?

**Comment by fzaninotto** [comment]
I'm -1 on this one, this is like reinventing programming using a templating language. Sure, it can be done, but what's the advantage when compared to pure PHP code? And I see a strong disadvantage: cost of writing the code, of testing it, and of documenting it.

```php
public function noticeContent()
{
    return $this->name + ' , ' + strtolower($this->noticeFamilyMembers(1, true));
}
```
