### ISSUE TITLE
Generate HSL color

### ISSUE THREAD

**Issue by n8udd** [fzaninotto/Faker#1720]
I've checked the docs, and scoured this repo, but I can't seem to find the command for generating HSL colors.

This commit looks like it adds tests for it: https://github.com/stympy/faker/pull/310, but having tried `$faker->hslcolor`, `$faker->hslacolor`, `$faker->hslColor`, `$faker->hslCssColor`
I can't seem to work it out?

This file doesn't seem to have a command for it: So I'm guessing it's not available: https://github.com/fzaninotto/Faker/blob/eef05943cd5f9b00edf81daac1f1ef28b16942d6/src/Faker/Provider/Color.php

Would this be of use https://gist.github.com/bedeabza/10463089 ?

**Comment by icanhazstring** [comment]
@n8udd sounds good. Will create a PR for that :)

**Comment by icanhazstring** [comment]
By looking at it, we don't need a proper rgb to hsl conversion. We simply need valid values for each `H`, `S` and `L`. With that said, looking at the specs of HSL this is simply 3 numbers.

1. 0-360 (hue in degree; 0-359, to be precise)
2. 0-100 (saturation in percent)
3. 0-100 (lightness in percent)
