### ISSUE TITLE
Question, not really an issue

### ISSUE THREAD

**Issue by bertalanimre** [fzaninotto/Faker#1732]
Hey Mate! Is it possible to make certain column with different localization? I mean OFC it is, but is there a simple way? :smile: 

For example, instead of:
```
$table->column('name')->replaceWith(function ($generator) {
        return $generator->unique()->name;
    });
```
If I want to have the name be generated in a different language, then maybe something like:
```
$table->column('name')->replaceWith(function ($generator) {
        return $generator->unique()->localization('hu_HU')->name;
    });
```

That would be great :smile: Or if there is a similar option, then I'm just blind and please ignore my ignorance, just point me to the right direction.

**Comment by chinleung** [comment]
One generator has one locale, so switching locale would require to load all providers again. Can't you do something like this instead?

``` php
$table->column('name')->replaceWith(function ($generator) {
    return \Faker\Factory::create('hu_HU')->unique()->name;
});
```

**Comment by localheinz** [comment]
@bertalanimre 

As @chinleung pointed out, you need to create a new instance of `Faker\Generator` - or otherwise access it from a list of previously created instances.

Please also take a look at https://github.com/fzaninotto/Faker#localization.
