### ISSUE TITLE
Dropping PHP support < 5.6

### ISSUE THREAD

**Issue by pimjansen** [fzaninotto/Faker#1771]
Hey all,

I was wondering what your view is on dropping support for older PHP versions that are currently already out of their lifecycle support (https://www.php.net/supported-versions.php)
At this point `Faker` is working still fine on those versions but since official support stopped it could also give side-fx. So a few ideas

* Lock composer to ^5.3 | ^7.0 so that it stays as is but note in the docs and bug reports that <5.6 is not officially supported
* Bump composer to match ^5.6. However that would mean that older versions cant use the library anymore on the next minor update
* Any other ideas?

_I added RFC label for discussions like this, any other ideas on that are also welcome_

Best,
Pim

**Comment by localheinz** [comment]
@pimjansen 

I'd suggest to drop support for older versions after a `1.9.0` release, when we can start working on `2.0.0`, what do you think? I'd probably require at least PHP 7.1 for `2.0.0`, so we can use type and return type declarations.

**Comment by pimjansen** [comment]
@localheinz yeah would work for me as well but its also a bit tricky to keep a library open for a language which is in not supported state as well. Since if its an option people will use it i guess

**Comment by fzaninotto** [comment]
I agree: I don't want to drop support for older versions in a minor release (that is a breaking change), so we should keep PHP >= 5.3 for the next minor version. For the major version, we can bump it to whatever we like.

I don't mind releasing a new version for an unsupported version of PHP. There are millions of web apps running on unsupported versions of PHP.

**Comment by icanhazstring** [comment]
Like @fzaninotto mentioned. I think the pretty good start for me as a user, would be a nice "deprecation" mention in the `README.md` or similar. Which states that bugs below 5.6 will not be addressed. 

This would also mean, that bug reports should include the current version a user was using. Maybe using issue templates? So we can then, as mentioned before, switch to 7.2 with next major.

**Comment by fzaninotto** [comment]
Before adding a mention in README, do we have bugs that are due to PHP < 5.6 issues? I don't think so. Let's not add noise for the reader if it's for an imaginary purpose.

**Comment by pimjansen** [comment]
@fzaninotto i agree that we should not create noise. I do think that we should start adding an issue template where we could ask for the PHP version used for example.

**Comment by fzaninotto** [comment]
@pimjansen I agree
