### ISSUE TITLE
Trying to get date between formerly faked date and now

### ISSUE THREAD

**Issue by mdhas** [fzaninotto/Faker#1787]
This is the code:

```
$created_at = $faker->dateBetween('-1 month', 'now');
$updated_at = $faker->dateBetween($created_at->format("U"), 'now');
```

I've tried several versions of the above and nothing seems to work. Any ideas would be helpful.

**Comment by pimjansen** [comment]
@mdhas for support related questions i would like to forward you to stackoverflow where this is not a bug on its own.

**Comment by localheinz** [comment]
@mdhas 

Perhaps take a look at https://stackoverflow.com/questions/tagged/php+faker!
