### ISSUE TITLE
Fatal error-  include_once(Faker/Provider/en_US/Barcode.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by lijoatimaginea** [fzaninotto/Faker#1793]
**### Summary**

We are getting the Fatal error 

include_once(Faker/Provider/en_US/Barcode.php): failed to open stream: No such file or directory

while using the faker inside zend framework.

### **Versions**

|                               | Version |
|:-------------------------|:--------   |
| PHP                      | 7.1        |
| `fzaninotto/faker`  | 1.8.0     |
| zend                     | 2           |

### **Steps to reproduce**

Include the library in the composer.json file

```
"require-dev": {
	"fzaninotto/faker": "^1.4"
}
 
```
 and run **composer update** command. 

 Include the below code in any controller file and we are getting the fatal error.

```
use Faker;

$faker = Faker\Factory::create();
echo $faker->name;
```

### **Expected output**

It should print the names of person.

### **Actual output**

Getting this fatal error as output.

Fatal error- include_once(Faker/Provider/en_US/Barcode.php): failed to open stream: No such file or directory

**Comment by pimjansen** [comment]
Please use the template provided when raising a bug since we miss a lot of information here

**Comment by lijoatimaginea** [comment]
Updated the issue with more info.

**Comment by pimjansen** [comment]
@lijoatimaginea there are no issues in the library itself so i assume it is in your implementation:

```php
<?php
require_once 'vendor/autoload.php';

$faker = Faker\Factory::create();
echo $faker->name;
```

gives me:

```sh
➜  faker-testroom php index.php
Westley Ziemann%     
```

So i assume you have other code that is causing a call to the Barcode locale somewhere
