### ISSUE TITLE
Lorem sentence() don't work with number words

### ISSUE THREAD

**Issue by khangkhangtg** [fzaninotto/Faker#1797]
### Summary
Lorem sentence() don't work with number words
### Versions
|                              | Version  |
| PHP                       | 7.2.11    |

| `fzaninotto/faker`  | 1.8.0      |
|Laravel                    | 5.8        |

I used Laravel tinker for testing my code, but I didn't get expected value as I wanted
Let's see my working screen

![faker](https://user-images.githubusercontent.com/27077431/65826056-ce989500-e2a8-11e9-8ab2-969a61841a4c.jpg)

**Comment by khangkhangtg** [comment]
The number words for a sentence weren't right

**Comment by pimjansen** [comment]
This is not a bug. As you can see in the docs and also in the settings the second argument is defaulting to true. So this means on default:

`set to false if you want exactly $nbWords returned, otherwise $nbWords may vary by +/-40% with a minimum of 1`
