### ISSUE TITLE
Generating fake data with a 'unique' DB constraint?

### ISSUE THREAD

**Issue by connecteev** [fzaninotto/Faker#1803]
### Summary

Is there a better way to generate fake data with a 'unique' DB constraint?

### Versions

PHP version: PHP 7.3.5
Faker version: "fzaninotto/faker": "^1.4",

I have a users table in laravel with:
* unique 'username'
* unique 'email'

I am using Faker to generate a large number of fake users for testing. However, I kept hitting an 'integrity constraint violation', so I started checking for uniqueness manually (below). My question is, is there a better way? I would love to use:
```
factory(User::class, 400)
```
but it doesn't seem to generate unique values for username and email. I need both of them to be individually unique.

```
        // Note: need a for loop to check for unique usernames and emails, otherwise could have instead used: factory(User::class, 400)
        for ($i = 0; $i < 400; $i++) {
            $fakeUserName = $faker->userName;
            while (User::where('username', '=', $fakeUserName)->exists()) {
                // echo "username $fakeUserName exists, attempt to find a unique username..\n";
                $fakeUserName = $faker->userName;
            }
            $fakeEmail = $faker->unique()->safeEmail;
            while (User::where('email', '=', $fakeEmail)->exists()) {
                // echo "email $fakeEmail exists, attempt to find a unique email..\n";
                $fakeEmail = $faker->unique()->safeEmail;
            }
            factory(User::class, 1)
                ->create([
                    'username' => $fakeUserName,
                    'email' => $fakeEmail,
                ]);
        }

```

**Comment by pimjansen** [comment]
This is not something that Faker can do you for since it also has a limited record set for you to create unique data for so many records. This of course is also done by a specific locale implementation.

The best suggestion is to add a random number to the email or username in the loop
