### ISSUE TITLE
composer  install     failure

### ISSUE THREAD

**Issue by caochengshun** [fzaninotto/Faker#1811]
- Installing fzaninotto/faker (v1.8.0): Cloning f72816b43e from cache              f72816b43e74063c8b10357394b6bba8cb1c10de is gone (history was rewritten?)        Failed to download fzaninotto/faker from source: Failed to execute git check out "f72816b43e74063c8b10357394b6bba8cb1c10de" -- && git reset --hard "f72816b43 e74063c8b10357394b6bba8cb1c10de" --                                                                                                                               fatal: reference is not a tree: f72816b43e74063c8b10357394b6bba8cb1c10de                                                                                              Now trying to download from dist                                               - Installing fzaninotto/faker (v1.8.0): Downloading (failed)                   Downloading (failed)                                                             Downloading (failed)                                                                                                                                                [Composer\Downloader\TransportException]                                         The "https://api.github.com/repos/fzaninotto/Faker/zipball/f72816b43e74063c      8b10357394b6bba8cb1c10de" file could not be downloaded: SSL: Զ▒▒▒▒▒▒ǿ▒ȹ▒         ▒▒▒▒һ▒▒▒▒▒е▒▒▒▒ӡ▒                                                                                                                                                 send of 141 bytes failed with errno=10054 Զ▒▒▒▒▒▒ǿ▒ȹر▒▒▒һ▒▒▒▒▒е▒▒▒▒ӡ             ▒                                                                                                                                                                 send of 22 bytes failed with errno=10054 Զ▒▒▒▒▒▒ǿ▒ȹر▒▒▒һ▒▒▒▒▒е▒▒▒▒ӡ▒                                                                                              send of 98 bytes failed with errno=10054 Զ▒▒▒▒▒▒ǿ▒ȹر▒▒▒һ▒▒▒▒▒е▒▒▒▒ӡ▒                                                                                              send of 2 bytes failed with errno=10054 Զ▒▒▒▒▒▒ǿ▒ȹر▒▒▒һ▒▒▒▒▒е▒▒▒▒ӡ▒                                                                                               send of 2 bytes failed with errno=10054 Զ▒▒▒▒▒▒ǿ▒ȹر▒▒▒һ▒▒▒▒▒е▒▒▒▒ӡ▒                                                                                               failed to open stream: HTTP request failed!
--

**Comment by pimjansen** [comment]
![image](https://user-images.githubusercontent.com/1457219/66753478-3d264700-ee94-11e9-8ce0-b07ccd0b86a6.png)

I dont see any issue with Faker here. Please flush caches and try again
