### ISSUE TITLE
lorempixel.com problem with $faker->image.

### ISSUE THREAD

**Issue by Rishats** [fzaninotto/Faker#1813]
### Summary
My CI/CD pipelines failed because lorempixel.com have some problem.
```php
    $file = $faker->image($uploadPath,640,480, null, false);
```
**vendor/fzaninotto/faker/src/Faker/Provider/Image.php**
imageUrl() return link:
https://lorempixel.com/640/480/?12829
I tried to open this link a couple of times.

### Versions
|                     | Version |
|:--------------------|:--------|
| PHP                 | 7.3.9   |
| `fzaninotto/faker`  | 1.8.0  |

### Self-enclosed code snippet for reproduction
https://lorempixel.com/640/480/?12829 try to open this link a few times.

### Expected output
![image](https://user-images.githubusercontent.com/21194702/66943112-5550be80-f06c-11e9-9d3d-fa05ac7274ba.png)

### Actual output
![image](https://user-images.githubusercontent.com/21194702/66943190-6dc0d900-f06c-11e9-917f-3d595f026ad8.png)

**Comment by pimjansen** [comment]
@Rishats this is not something we can easily fix on faker since its a LorumPixel issue it seems. Did you try to reach out there?

**Comment by Rishats** [comment]
> @Rishats this is not something we can easily fix on faker since its a LorumPixel issue it seems. Did you try to reach out there?

I just install - https://github.com/bruceheller/images-generator. 
Will the faker have this kind of function out of the box?

**Comment by pimjansen** [comment]
@Rishats no idea yet if this should be part of the Faker core or not. In my opinion we could however it should be fairly easy to run it as a provider as well. Im going to close this issue now since it is not a faker bug itself
