### ISSUE TITLE
Some strange behavior with usage --ignore-platform-reqs (+PHP 7.4)

### ISSUE THREAD

**Issue by Eugentis** [fzaninotto/Faker#1830]
### Summary

I am working with your lib on server with php 7.4. Some dependencies require php ~7.3 and I've used flag --ignore-platform-reqs
As I can see in composer.lock it was installed version with reference f72816b43e74063c8b10357394b6bba8cb1c10de.

During the generation of fake data ($generator->text(200)) I've hit with error
'implode(): Passing glue string after array is deprecated. Swap the parameters'

As I can see it is a problem with usage implode in provider Lorem.php:95. It is actual only for this reference.
After investigation your master branch I can see there are correct code in this provider.

Could you advice how I can work with your lib in this case?

### Versions

|                     | Version |
|:--------------------|:--------|
| PHP                 | 7.4.0RC3   |
| `fzaninotto/faker`  | 1.8.0   |

**Comment by spaceemotion** [comment]
It looks like this has been fixed in https://github.com/fzaninotto/Faker/commit/167d8052c50ab4849ca7389671530ad8088cf302
Since there hasn't been a new release since then, I guess we'll just have to wait.

**Comment by pimjansen** [comment]
Indeed, it will be fixed in the next minor. Since PHP 7.4 is not release yet we will not patch this as a fix right away
