### ISSUE TITLE
How to generate US Specific Address

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [fzaninotto/Faker#1845]
Trying to generate US address collection through Node js. 
```

data.address = [
      {
        street: faker.address.streetAddress(),
        city: faker.address.city(),
        state_code: faker.address.stateAbbr(),
        state: faker.address.state(),
        country_code: faker.address.countryCode(),
        country: faker.address.country(),
        postal_code: faker.address.postal_code,
        address: faker.address.address
      }
    ];

```
This gives everything random/unrelated values,  How can I mention to use one country based related complete address? Tried this faker.setLocale = "en_US"  but that didnt work, still it gives different country addresses.

**Comment by plumthedev** [comment]
Hello! :)
How do you try to use Faker in Node.js? This is PHP library
Maybe you made a mistake in in repositories? [Faker.js](https://github.com/Marak/Faker.js) is probably this what you search for.

**Comment by Elamurugan-Nallathambi** [comment]
My bad :(, still you got me right repo. to post the query. Thank you so much.

**Comment by plumthedev** [comment]
I'm glad I could help you, remember to look for solutions to your problems in the right technology in the future.

Greetings, plumthedev!
