### ISSUE TITLE
Invalid lastname generation in ru_RU locale

### ISSUE THREAD

**Issue by nnrudakov** [fzaninotto/Faker#1848]
### Summary

Female lastnames generates with invalid ending letter.

### Versions

|                     | Version |
|:--------------------|:--------|
| PHP                 | 7.2   |
| `fzaninotto/faker`  | 1.9.0   |

### Self-enclosed code snippet for reproduction

```php
$faker = Factory::create('ru_RU');
echo $faker->lastName;
```

### Expected output

```txt
Петрова
```

The ending letter `а` must be a Russian letter `а` but now it is an English `a`. Look [here](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/ru_RU/Person.php#L108) and [here](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/ru_RU/Person.php#L172).

**Comment by pimjansen** [comment]
Can you raise a PR for this ?

**Comment by pimjansen** [comment]
Fixed with 1902
