### ISSUE TITLE
bad service lorempixel.com 

### ISSUE THREAD

**Issue by kvlknctk** [fzaninotto/Faker#1859]
I usualy migrating db with fake image. 
But all days http://lorempixel.com/ servers very busy. lorempixel usign shit servers. 
And now I couldn't migrate a image for the last hour. 

Best regards. 

![](https://i.hizliresim.com/1plyq1.png)

**Comment by pimjansen** [comment]
This is a third party service. I suggest to use a different service for this. In faker 2.0 this image generation will also be removed from the core.
