### ISSUE TITLE
Using curly brackets to access array elements is deprecated in PHP 7.4

### ISSUE THREAD

**Issue by tylermarien** [fzaninotto/Faker#1860]
### Summary

When using the Payment provider, it throws the following exception in PHP 7.4.

```Array and string offset access syntax with curly braces is deprecated```

### Versions

PHP - 7.4.0
fzaninotto/faker - 1.9.0

### Self-enclosed code snippet for reproduction

```php
$faker = \Faker\Factory::create();
$faker->creditCardNumber('Visa');
```

### Expected output

Expect to get a valid Visa card number.

### Actual output

```
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/html/vendor/fzaninotto/faker/src/Faker/Calculator/Luhn.php on line 27
```

**Comment by bolechen** [comment]
it already fix at https://github.com/fzaninotto/Faker/pull/1843
