### ISSUE TITLE
Release for latest PHP 7.4 compatibility

### ISSUE THREAD

**Issue by brendt** [fzaninotto/Faker#1863]
Would it be possible to tag a new release containing this commit (https://github.com/fzaninotto/Faker/commit/c981c04a1bab15b39a69303a2f2f4ccb6612eab5) to ensure PHP 7.4 compatibility?

**Comment by pimjansen** [comment]
Yes we are discussing it to push the 1.9.1 earlier to ensure 7.4 compatibility.

**Comment by brendt** [comment]
For those finding this issue before 1.9.1 is released:

```json
"fzaninotto/faker": "dev-master#c981c04a1bab15b39a69303a2f2f4ccb6612eab5",
```

Will do the trick

**Comment by localheinz** [comment]
For those finding this issue before `1.9.1` is released, please do not edit `composer.json` manually, run

```
$ composer require --dev "fzaninotto/faker:dev-master#c981c04 as 1.9.1"
```

instead.

😉

**Comment by pimjansen** [comment]
1.9.1 just has been released. Enjoy
