### ISSUE TITLE
Typos in /Faker/Provider/ru_RU/Person.php and tests/Faker/Provider/ru_RU/PersonTest.php

### ISSUE THREAD

**Issue by piunChik** [fzaninotto/Faker#1902]
The function lastName() is incorrrect. You use latin 'a' in 172 string instead of cyrillic 'а'.
So these female last names don't pass my validation, where all symbols should be cyrillic.
There is the same toruble in PersonTest.php

I've made a pull request https://github.com/fzaninotto/Faker/pull/1901.
But it doesn't pass your tests (some troubles with environment?).

**Comment by pimjansen** [comment]
Thanks!

**Comment by piunChik** [comment]
I found another one typo, fixed it in this pull request https://github.com/fzaninotto/Faker/pull/1905

**Comment by ulcuber** [comment]
[Same](https://github.com/fzaninotto/Faker/issues/1925)

**Comment by localheinz** [comment]
Closed with #2045.
