### ISSUE TITLE
Document that seed argument gets casted to an int

### ISSUE THREAD

**Issue by mlazze** [fzaninotto/Faker#1934]
### Summary

Seed method internally casts the value to an int.
I wasn't expecting it to be, so i used two strings without numbers as seed value.

### Versions

v1.9.1

### Self-enclosed code snippet for reproduction

```php
$faker = Factory::create();

$faker->seed('a');
$first = $faker->uuid;
$faker->seed('b');
$second = $faker->uuid;

assert($first !== $second); <- fails
```

### Solution

A simple phpdoc or a type hint would allow an IDE to warn the user about this.

**Comment by localheinz** [comment]
Closed with #1894.
