### ISSUE TITLE
In DatabaseServiceProvider.php line 88:    Class 'Faker\Factory' not found

### ISSUE THREAD

**Issue by stephenjason89** [fzaninotto/Faker#2067]
running composer install --no-dev
version 1.9.1

Results to this error:
```
In DatabaseServiceProvider.php line 88:

  Class 'Faker\Factory' not found
```
I already delete all my migrations/seeders/factory and still having this error

**Comment by raphaeldealmeida** [comment]
This is a Laravel question.
Faker is a required-dev dependence

https://github.com/laravel/laravel/blob/master/composer.json#L20

**Comment by stephenjason89** [comment]
Thank you for the reply. i have actually resolved it by deleting the module and recreating it.
For some unknown reason i may have npm install or composer install on the module dir that caused the error.
