### ISSUE TITLE
Random image category from lorem pixel

### ISSUE THREAD

**Issue by morrislaptop** [fzaninotto/Faker#267]
I've got a prizes page which displays all the prizes, because they are all displayed on the one page, they all get the same image which doesn't look great. If we could somehow get a random category inserted into the URL that would be great..

FYI I'm using this with the alice library so something like

```
image: <imageUrl(270, 270, randomElement(array('sports','fashion','cats'))>
```

isn't possible, so I'm using

```
image: <imageUrl(270, 270, call_user_func(function() { $c = array('abstract', 'animals', 'business', 'cats', 'city', 'food', 'nightlife','fashion', 'people', 'nature', 'sports', 'technics', 'transport'); return $c[array_rand($c)]; }))>
```

**Comment by fzaninotto** [comment]
Superseded by #372
