### ISSUE TITLE
Last insert id in Db module doesn't return last insert id

### ISSUE THREAD

**Issue by cinan** [fzaninotto/Faker#293]
Hello,
I inserted a row with explicitly defined ID (using Db module). However, the row is not deleted after test's finished (Db cleanup is set to false). I've found in Mysql logs these lines:

INSERT INTO `cards` (`id`, `id_client`, `id_user`, `type`, `is_active`, `is_virtual`) VALUES ('6299qejd', '4', '888', '', '1', '1')
...
delete from cards where id = 0

The cards.id type is varchar. The value 0 is actually returned by PDO::lastInsertId().
Maybe better approach would be saving $insertedIds in Db module right from inserted data, if ID is explicitly defined in insert query.

**Comment by fzaninotto** [comment]
No feedback for more than 6 months, closing.
