### ISSUE TITLE
Add biased/weighted “random” numbers

### ISSUE THREAD

**Issue by max-m** [fzaninotto/Faker#304]
What about adding an generator for “weighted random numbers”?
For example a generator like this gamma “corrected” random number generator:
> [Author: bobince](http://stackoverflow.com/a/445363/1112384)
> ```PHP
/*
 * Generates a weighted random number
 *
 * Choose a continuous random number between 0..1
 * Raise to a power γ, to bias it. 1 is unweighted, lower gives more of the higher numbers and vice versa
 * Scale to desired range and round to integer
 *
 * @author bobince <http://stackoverflow.com/a/445363/1112384>
 */
public static function weightedRand($min, $max, $gamma) {
	$offset = $max - $min + 1;
	return floor($min + pow(lcg_value(), $gamma) * $offset);
}
```

Here is the probability distribution of calling `weightedRand(1, 4, $gamma);`.
May need some tweeking with values lower or equal to 0 though.

```
[kernel@~]php development/test.php 2.2
Gamma: 2.2
1: 53233 (53.233%)
2: 19662 (19.662%)
3: 14678 (14.678%)
4: 12427 (12.427%)
[kernel@~]php development/test.php 1.9
Gamma: 1.9
1: 48102 (48.102%)
2: 21317 (21.317%)
3: 16449 (16.449%)
4: 14132 (14.132%)
[kernel@~]php development/test.php 0
Gamma: 0
5: 100000 (100%)
[kernel@~]php development/test.php -.09
Gamma: -0.09
5: 91459 (91.459%)
6: 7433 (7.433%)
7: 901 (0.901%)
8: 155 (0.155%)
9: 35 (0.035%)
10: 8 (0.008%)
11: 5 (0.005%)
12: 3 (0.003%)
14: 1 (0.001%)
```

This might come in handy some times ^^

**Comment by fzaninotto** [comment]
Fixed by #332
