### ISSUE TITLE
Override Base in locales

### ISSUE THREAD

**Issue by serge-kuharev** [fzaninotto/Faker#347]
I was trying to fix another issue and I found interesting thing.

According to the Faker logic, providers are loaded one by one in order they are specified in \Faker\Factory::$defaultProviders. That means, if Color has some method, let's say randomColor and Miscellaneous has method randomColor, only method from Miscellaneous will be loaded. This is cool feature, but not only if we want to override Base class. This won't work in such case, since all our classes are extended from Base.

To illustrate this, see issue #342. To implement it, I need to override randomLetter() method. But only place I can do it to make it work is in Uuid class in my locale, since it is the last one that is loaded.. And that is not logical place.

Possible solution for this specific case would be to move randomLetter to Text class(I think it is better place for it there). But this will be only temporary fix until similar issue appears. 

Any ideas how that might be accomplished?

**Comment by fzaninotto** [comment]
Nope, not possible with the current architecture. Closing the issue since it's more a question.
