### ISSUE TITLE
Faker does not handle locales for days/months names

### ISSUE THREAD

**Issue by miclf** [fzaninotto/Faker#360]
The `dayOfWeek` and `monthName` formatters currently do not handle locales. Whatever the current PHP locale or the one specified to `Faker\Factory::create()`, they will always return `en_US` strings.

I think of three possibilities to solve this:

1. Make `Faker\Provider\DateTime::dayOfWeek()` and `Faker\Provider\DateTime::monthName()` use `strftime()` to be able to return localized strings.
**Pro:** super easy to implement.
**Con:** the required locale has to be installed on the system. Plus, this change may have side effects I’m unaware of.

2. Add relevant lists of names in locale providers, as it is already the case with `Faker\Provider\cs_CZ::DateTime`.
**Pro:** independant of installed locales.
**Con:** it would introduce some duplication in the codebase for locales that have the same ‘root language’ (e.g. fr_FR, fr_BE, fr_CA, etc.)

3. Same as the second possibility, but using a trait to introduce the relevant properties and methods instead of duplicating them.
**Pro:** no code duplication.
**Con:** Faker’s requirements would have to be bumped to PHP 5.4 instead of 5.3.3. It might not be an issue since [PHP 5.3 will become officially dead in the next two weeks](http://php.net/archive/2013.php#id2013-07-11-1).

Another idea (which could be combined with one of those three possibilities) would be to create dedicated formatters to generate localized strings, such as `localDayOfWeek` and `localMonthName`, and keep the existing formatters as is. This would ensure that any potential side effect is avoided.

What do you think?

**Comment by fzaninotto** [comment]
I'm thinking more about your solution 2, using inheritance to keep the same list for a group of languages.

**Comment by fzaninotto** [comment]
I'm closing it, since the job has to be done in locales by the locale maintainer.
