### ISSUE TITLE
Improve german first names

### ISSUE THREAD

**Issue by mikehaertl** [fzaninotto/Faker#361]
As a native I have to say, that the german first names don't look very german to me :).

Here's a list of the most frequently used first names: 
- http://de.wiktionary.org/wiki/Verzeichnis:Deutsch/Liste_der_h%C3%A4ufigsten_m%C3%A4nnlichen_Vornamen_Deutschlands
- http://de.wiktionary.org/wiki/Verzeichnis:Deutsch/Liste_der_h%C3%A4ufigsten_weiblichen_Vornamen_Deutschlands

**Comment by Findus23** [comment]
I known I'm a bit late, but would it be possible to improve the last names too?
I can't really believe that these are the most common last names. Especially names like `auch Schlauchin` don't make sense.
@mikehaertl Would it be possible to parse the names from https://de.wiktionary.org/wiki/Verzeichnis:Deutsch/Liste_der_h%C3%A4ufigsten_Nachnamen_Deutschlands ?
And while we're on it, is it possible to also update the Austrian Names from https://de.wiktionary.org/wiki/Verzeichnis:Deutsch/Liste_der_h%C3%A4ufigsten_Nachnamen_%C3%96sterreichs (or at least copy them from Germany)

**Comment by mikehaertl** [comment]
@Findus23 It was mainly lack of time - and that I didn't need faker anymore so far. So feel free to send any updates you like. Also consider to update the first names like I've mentioned above. Most of them are not really sounding very german (yes, we have "multikulti" ;) -  but still I think the "classical" german names are most common).

**Comment by Findus23** [comment]
I'll see if I am able to update them.
Do you still have the script to parse the list and create the array?

**Comment by mikehaertl** [comment]
No, sorry. I think I've just copy & pasted this into Vim and then used some regex to extract the names.

**Comment by Findus23** [comment]
I have made the pull requests #825 and #826.
