### ISSUE TITLE
Undefined class constant 'PEER'

### ISSUE THREAD

**Issue by talhazekeriyadurmus** [fzaninotto/Faker#367]
It throws error on page vendor\fzaninotto\faker\src\Faker\ORM\Propel\EntityPopulator.php

Undefined class constant 'PEER'

        $this->columnFormatters = array_merge($this->columnFormatters, $columnFormatters);
    }
 
    public function guessColumnFormatters(\Faker\Generator $generator)
    {
        $formatters = array();
        $class = $this->class;
        $peerClass = $class::PEER;
        $tableMap = $peerClass::getTableMap();
        $nameGuesser = new \Faker\Guesser\Name($generator);

**Comment by fzaninotto** [comment]
Since Propel 2.0 is back into pre-alpha, I guess it's safe to say Faker doesn't support it. Closing.

**Comment by noyessie** [comment]
PLease, I want to help projet to support Propel 2. Can you help me to understand what you are already do and improve it ?
