### ISSUE TITLE
v1.5.0

### ISSUE THREAD

**Issue by GrahamCampbell** [fzaninotto/Faker#463]
What's the roadmap for `v1.5.0`? Will there be a release anytime soon?

**Comment by andrewelkins** [comment]
Any luck on tagging a new release?

**Comment by nunorafaelrocha** [comment]
+1

**Comment by djlemmings** [comment]
That would be very good, as some features are currently unusable when using faker in a composer project (such as password generation).

**Comment by deizel** [comment]
+1 - The latest stable tag is also missing the CakePHP adapters.

**Comment by cordoval** [comment]
I am :+1: for this too, but #579 is actually just requesting the chance of a minor number, please @fzaninotto thankx

**Comment by GrahamCampbell** [comment]
1.5 is a minor release?

**Comment by cordoval** [comment]
fixed typo :smirk:

**Comment by cordoval** [comment]
ok we are all together in this ticket now :+1: thanks @GrahamCampbell

**Comment by fzaninotto** [comment]
I hear you, I'm working on it.

**Comment by GrahamCampbell** [comment]
Take all the time you need. :)

**Comment by fzaninotto** [comment]
Fixed in #585

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by nunorafaelrocha** [comment]
Sweet! :+1:

**Comment by djlemmings** [comment]
Many thanks.
