### ISSUE TITLE
some locales product invalid email addresses

### ISSUE THREAD

**Issue by Kehet** [fzaninotto/Faker#466]
This happens at least with fi_FI, but propably also other locales does same. I use following snippet to product email addresses

```php
$faker = Faker::create('fi_FI');
$faker->safeEmail;
```

However, that function doesn't understand that Finnish names can contains characters outsaid of a-z range. Email address [standard](http://en.wikipedia.org/wiki/Email_address#Local_part) doesn't allow other than a-z, A-Z and some special characters on local part of address and thus produced addresses like ``äärynen.jusu@example.net`` are invalid!

Quick fix for this is obviously not to use localization

**Comment by fzaninotto** [comment]
Fixed by #490
