### ISSUE TITLE
randomFloat produces more decimals than specified

### ISSUE THREAD

**Issue by thinksalot** [fzaninotto/Faker#477]
Hi,
I am using Faker to generate random data for selenium tests. Tests are run on PHP 5.4.27 on a CentOS 6.5 box. On every ~100 test runs, i gets failed reports from jenkins. Upon investigating, it seems Faker is returning values such as 
`92.90000000000001`
`89.95999999999999`
`86.76000000000001`
instead of just 2 numbers after decimal.
My method call is
`$faker->randomFloat(2, 1, 100 );`

Any ideas why this may be happening ?

**Comment by fzaninotto** [comment]
I generated 20,000 random floats with your configuration and saw only valid results. So I can't reproduce your problem.

This is probably due to JavaScript conversion (you were mentioning Selenium). I believe this is not a Faker issue.
