### ISSUE TITLE
Generate ean 10

### ISSUE THREAD

**Issue by MartijnThomas** [fzaninotto/Faker#484]
Is it possible to make the [ean method](https://github.com/fzaninotto/Faker/blob/9c5c88f2576b3c4f0c2e2c4c4ae2a8ec55d8a348/src/Faker/Provider/Barcode.php#L10) protected instead of private? This will make it possible to generate ean10 or ISBN10 (old ISBN) codes.

**Comment by nickurt** [comment]
It isn't related to this one? #451 ..

**Comment by MartijnThomas** [comment]
yep it is, I'll close this one
