### ISSUE TITLE
[Feature Request] Create entities with randomized locale

### ISSUE THREAD

**Issue by althaus** [fzaninotto/Faker#502]
Hey,

I just stumbled upon your funny lib. I'm using it from BazingaFakerBundle in Symfony. I'm working on a website with an international user base and I'd be great to be able to randomize the used locale. So instead of generating all fake users with a fixed locale, it'd be great if I could randomize this so that I get a willd mix of users from all over the world.

As far as I understood this code, it's not possible at the moment, because the given locale is used on the factory setup?

For now I'll just switch the locale between multiple population iterations, but a build-in option would be awesome.

Cheers
Matthias

**Comment by fzaninotto** [comment]
Why don't you use several Faker instances?

```php
function getLocalizedFaker() {
  $mainFaker = Faker\Factory::create();
  try {
    return Faker\Factory::create($mainFaker->locale);
  } catch (Exception $e) { // no Faker for this locale, try again
    return getLocalizedFaker();
  }
}
```

**Comment by anvi** [comment]
I'm using a faker selector like this one:

```php
class FakerRandomSelector
{
    protected $generators;
    protected $main;

    public function __construct()
    {
        $this->main = \Faker\Factory::create();
    }

    public function add(\Faker\Generator $generator)
    {
        $this->generators[] = $generator;
        return $this;
    }

    /**
     * Choose an arbitrary generator among those registered
     * @return \Faker\Generator
     */
    public function choose()
    {
        $max = count($this->generators);
        if (!$max) {
            return $this->main;
        }
        return $this->generators[$this->main->numberBetween(0, $max - 1)];
    }
}
```
Using it is a simple as:
```php
$selector = new FakerRandomSelector();
$selector
    ->add(\Faker\Factory::create('fr_FR')
    ->add(\Faker\Factory::create('de_DE');
$faker = $selector->choose();
```

**Comment by althaus** [comment]
Thanks for your replies. I've stopped using the Faker as my data structure was too complex, so I'm just using a live data dump (re-writing a old project).
