### ISSUE TITLE
imageURL always return the same set of photos.

### ISSUE THREAD

**Issue by ctf0** [fzaninotto/Faker#503]

**Comment by ronanguilloux** [comment]
Hi @ctf0, 

`:imageURL()` method provides fake images URL coming from [Lorempixel.com](http://lorempixel.com), which is a tiny but useful free service. Such fake images are **for layout purposes**, and therefore this remote provider is not a royalty free stock photos service - which is a much more difficult (and valuable) service to provide ;-)

Feel free to propose any pull-request hack based on a reliable [public domain photos provider](http://en.wikipedia.org/wiki/Wikipedia:Public_domain_image_resources): such improvement would be greatly appreciated!

We're looking forward to review your suggestion/code!

**Comment by fzaninotto** [comment]
Great answer, @ronanguilloux. I don't see an easy way to fix this one, So I'll close the issue.

**Comment by ctf0** [comment]
@ronanguilloux i made a PR for that.
