### ISSUE TITLE
unknown formatter "departmentname"

### ISSUE THREAD

**Issue by erickmonteiro** [fzaninotto/Faker#506]
Hi, i have error in:

$faker = Faker\Factory::create('pt_BR');
echo $faker->departmentName;

ERROR: unknown formatter "departmentname"

Sorry my bad english, i'm from Brazil, thanks.

**Comment by fzaninotto** [comment]
Yes, this formatter doesn't exist in this locale, only in the fr_FR locale.

**Comment by lloricode** [comment]
how sad
