### ISSUE TITLE
Fatal error: Class 'Faker\Factory' not found

### ISSUE THREAD

**Issue by phonem** [fzaninotto/Faker#509]
Hi,

I've just installed Faker with composer with the composer.json file you provide.

As a result I get Fatal error: Class 'Faker\Factory' not found error with the php example code you provide.

I've updated the composer.json file with "fzaninotto/faker": "1.5.*@dev" in require section but as a result I get this composer error after composer update command : The requested package fzaninotto/faker 1.0.0 could not be found.

Could you help please ?

**Comment by fzaninotto** [comment]
Weird. Can you paste the `composer.json` file? Also, the right way to install Faker to an existing project would be to call:

```sh
composer require fzaninotto/Faker "~1.5@dev"
```

**Comment by phonem** [comment]
The json file content 
{
    "name": "fzaninotto/faker",
    "type": "library",
    "description": "Faker is a PHP library that generates fake data for you.",
    "keywords": ["faker", "fixtures", "data"],
    "license": "MIT",
    "authors": [
        {
            "name": "François Zaninotto"
        }
    ],
    "require": {
        "php": ">=5.3.3"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "squizlabs/php_codesniffer": "~1.5"
    },
    "suggest": {
         "ext-intl": "*"
     },
    "autoload": {
        "psr-4": {
            "Faker\\": "src/Faker/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Faker\\PHPUnit\\": "test/Faker/"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "1.5.x-dev"
        }
    }
}

And what happens when i run the command composer require fzaninotto/Faker "~1.5@dev"
[root@xxx1 faker]# composer require fzaninotto/Faker "~1.5@dev"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package fzaninotto/faker 1.0.0 could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
[root@xxx01 faker]#

**Comment by fzaninotto** [comment]
OK, you have copied the Faker `package.json`, which is not the way it works. This is a not a Faker issue: you probably need to learn more about composer.
