### ISSUE TITLE
Use realText provider to get random word/sentence/etc

### ISSUE THREAD

**Issue by Anahkiasen** [fzaninotto/Faker#516]
Currently you can either use all the text related methods (word/words/sentence/etc) and get only Lorem Ipsum, or use the realText method but you can only get X characters. Is there any way to combine the two and get per example 2 words in non-latin?

**Comment by fzaninotto** [comment]
No, not with the current architecture, sorry.

**Comment by cleentfaar** [comment]
@Anahkiasen Not sure if you solved this already but I needed this too (for Dutch language), and got a pretty simple solution by using a Dutch translation of the Alice in Wonderland book as a source. You can check it out here and perhaps try something similar yourself: https://github.com/cleentfaar/Faker/pull/1

To get good sentences it tries to find those which match the requested number of words as close as possible, so sentences don't get broken up too easily (making them less readable).

@fzaninotto would this be something worth making a PR for, I suppose it deviates a bit from current behaviour.

**Comment by fzaninotto** [comment]
What you ask for is a dictionary for a given language. I suggest you create a custom formatter for your own usage. Faker won't be the repository storing dictionaries for every language in the world, it doesn't make sense.

**Comment by Anahkiasen** [comment]
This isn't what the original issue was about though, it was about adding methods to use the Text provider the way you use the Ipsum one

**Comment by fzaninotto** [comment]
You were mentioning a new implementation. I was referring to the underlying use case. If this is about generating random words, the solution is to use a dictionary.
