### ISSUE TITLE
transliterator_transliterate "unable to open ICU transliterator"

### ISSUE THREAD

**Issue by yoghi** [fzaninotto/Faker#520]
In the library was used if (function_exists('transliterator_transliterate')) but isn't a garantee that all ICU transliterator necessary was installed 

```
b>Warning</b>:  transliterator_transliterate(): Could not create transliterator with ID &quot;Any-Latin; Latin-ASCII; NFD; [:Nonspacing Mark:] Remove; NFC; Lower();&quot; (transliterator_create: unable to open ICU transliterator with id &quot;Any-Latin; Latin-ASCII; NFD; [:Nonspacing Mark:] Remove; NFC; Lower();&quot;: U_INVALID_ID) in <b>/home/returntogf/bin/test.php5</b> on line <b>6</b><br />
```

**Comment by fonsecas72** [comment]
Hi,
Can you suggest a solution for this?
Do you think that the following would fix the issue for you?
```if (function_exists('transliterator_transliterate') && $transliterator = Transliterator::create("Any-Latin; Latin-ASCII; NFD; [:Nonspacing Mark:] Remove; NFC; Lower();") !== null) {
     $transString = $transliterator->transliterate($string)
} else {
    $transString = static::toAscii($string);
}...```

**Comment by yoghi** [comment]
fixed for me :)

**Comment by fonsecas72** [comment]
@fzaninotto what do you think?

**Comment by adamlc** [comment]
@fonsecas72 unfortunately your fix doesn't seem to work for me :(

I'm running php5.4 inside a docker container if that makes any difference? I have a feeling the webtatic.com el6 repos have a broken implementation of something somewhere!

```
PHP Warning:  transliterator_transliterate(): Could not create transliterator with ID "Any-Latin; Latin-ASCII; NFD; [:Nonspacing Mark:] Remove; NFC; Lower();" (transliterator_create: unable to open ICU transliterator with id "Any-Latin; Latin-ASCII; NFD; [:Nonspacing Mark:] Remove; NFC; Lower();": U_INVALID_ID) in /root/core/workbench/jumplead/apiv1/vendor/fzaninotto/faker/src/Faker/Provider/Internet.php on line 150
```

**Comment by adamlc** [comment]
Turns out the ICU and ext-intl where seriously out of date in the el6 repos. I installed ICU and pecl intl from source and it's now fixed :)

**Comment by fzaninotto** [comment]
That doesn't silence the warning, does it?

**Comment by fonsecas72** [comment]
I don't think so, but @yoghi can you help with the answer to that?

**Comment by yoghi** [comment]
@adamlc which linux distro have  you used?

**Comment by fonsecas72** [comment]
@yoghi I'm sorry, I think you misunderstood the question.
My question was about the likely silencing of the warning if we use my fix for this problem. I assume that you have applied my suggestion so, when you did that, did you get any warning?

**Comment by adamlc** [comment]
@yoghi I'm using CentOS 6 and the php 5.4 repos from webtatic.com

**Comment by Perfect-Web** [comment]
it happens to me as well, very annoying

**Comment by fzaninotto** [comment]
Can you post an update which silences the warning?

**Comment by fonsecas72** [comment]
@fzaninotto this should avoid the php warning https://github.com/fzaninotto/Faker/pull/541
