### ISSUE TITLE
Adding geometry (in WKT format)

### ISSUE THREAD

**Issue by rap2hpoutre** [fzaninotto/Faker#524]

**Comment by fzaninotto** [comment]
I have no idea what this is about. Probably the wrong repo?

**Comment by nineinchnick** [comment]
It's a feature request for a geometry generator. I've found [a Wikipedia article about WKT](http://en.wikipedia.org/wiki/Well-known_text). DB support looks impressive, covering MySQL/MariaDB, PostgreSQL and MSSQL.

The format looks simple, but I think a useful implementation should allow to set some constraints (contained in a shape, dimensions bounds), which would require some geo library.

This is somehow related to the Address latitude/longitude generators. They could also use a constraint argument, for example for countries boundaries.

**Comment by nineinchnick** [comment]
Anyway, if @fzaninotto thinks this could be useful, I'm interested in implementing it.

**Comment by nineinchnick** [comment]
And as a reference, I've found this [phayes/geoPHP](https://github.com/phayes/geoPHP) library.

**Comment by rap2hpoutre** [comment]
Thanks @nineinchnick, that's it, you explained it very well !

**Comment by fzaninotto** [comment]
I think it makes a lot of sense for a third-party provider, not sure if it's worth putting it in Faker code.
