### ISSUE TITLE
Doctrine composite foreign key

### ISSUE THREAD

**Issue by Nihaux** [fzaninotto/Faker#529]
I am having a problem with a relation table:
ArticleTag has two ManyToOne relations: --> Article --> Tag
It's primary key is a composite of Article and Tag.
When I execute the following code, I get a mysql error:
QLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-3' for key 'PRIMARY'

Is there a way to make this work ?

```
$generator = \Faker\Factory::create('en_US');

$populator = new \Faker\ORM\Doctrine\Populator($generator, $this->entityManager);
$populator->addEntity(
    new \Faker\ORM\Doctrine\EntityPopulator($this->entityManager->getClassMetadata('\PMD\TEL\CoreBundle\Entity\Article')), 5
);
$populator->addEntity(
    new \Faker\ORM\Doctrine\EntityPopulator($this->entityManager->getClassMetadata('\PMD\TEL\CoreBundle\Entity\Tag')), 5
);

$populator->addEntity(
    new \Faker\ORM\Doctrine\EntityPopulator($this->entityManager->getClassMetadata('\PMD\TEL\CoreBundle\Entity\ArticleTag')), 15
);

$insertedPKs = $populator->execute();
```

**Comment by bigfoot90** [comment]
I'm also interested

**Comment by fzaninotto** [comment]
I'm really unable to help, I only merged the work from Doctrine people who don't maintain this anymore. We need a Doctrine expert to take over the Doctrine integration...
