### ISSUE TITLE
Is there any way to specify a required format for phone #'s

### ISSUE THREAD

**Issue by markalanevans** [fzaninotto/Faker#531]
Since it randomly selects a phone number, we can't really use the phoneNumber method as it returns formats we don't accept.

**Comment by ulrikjohansson** [comment]
You could just skip using the `phoneNumber()` method and go straight for the `numerify()` method instead. Just specify your allowed formats in your own array and call numerify() like faker does itself in [PhoneNumber.php](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/PhoneNumber.php).
This way you have full control over the values Faker returns.

**Comment by markalanevans** [comment]
@ulrikjohansson Perfect! I'll do that.
