### ISSUE TITLE
seed() without parameter is broken

### ISSUE THREAD

**Issue by schmengler** [fzaninotto/Faker#538]
Currently the generator allows seeding the RNG with arbitrary numbers:

    public function seed($seed = null)
    {
        mt_srand($seed);
    }

Unfortunately, leaving out the parameter does not call `mt_srand()` without parameters, but with `null` which has the same effect as `mt_srand(0)` (tested on PHP 5.4 and PHP 5.6)

**Comment by fzaninotto** [comment]
Right, it shouldn't accept a null value. Would you mind submitting a patch for that?

**Comment by fzaninotto** [comment]
Fixed in #543
