### ISSUE TITLE
copy(): The first argument to copy() function cannot be a directory

### ISSUE THREAD

**Issue by montogeek** [fzaninotto/Faker#539]
I get that error doing 
`$faker->file()`

The `/tmp` folder exists.
PHP 5.4.38 (cli) (built: Feb 20 2015 02:42:34)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

CentOS 6.2

**Comment by vuchl** [comment]
What are your parameters for ```$faker->file();``` like ```$faker->file($sourceDir, $targetDir, false)```

**Comment by montogeek** [comment]
I didnt use any parameters, just `file()`

**Comment by fzaninotto** [comment]
`file()` returns a random file from the source directory (here `/tmp). I suspect it fails because this directory is empty, am I right?

**Comment by fzaninotto** [comment]
Sorry, I just understood the source of the problem (#547). Continuing discussion there.

**Comment by fzaninotto** [comment]
Fixed by #547
