### ISSUE TITLE
Why you need parameter $asText in words method

### ISSUE THREAD

**Issue by aohorodnyk** [fzaninotto/Faker#555]
Hello,

I watch Faker\Provider\Lorem and can't understand why you need parameter $asText in words method if you have sentence method?

And second question about PhpDoc comments. Why you don't use arrays with type hints like string[] or int[]? I think it's will be more clearly, or not?

Thanks

**Comment by fzaninotto** [comment]
`sentence()` capitalizes the first letter and adds a dot - it's not the same as a string made of words.

As for the phpDoc, Faker is following an old version of phpDoc's convention. I see it has now changed. If you'd like to submit a pull request to update the phpDoc of all Faker method, I'd be happy to merge it!
