### ISSUE TITLE
Keeping data consistency

### ISSUE THREAD

**Issue by timotheemoulin** [fzaninotto/Faker#557]
Hi,
In my case, I would like to generate a full profile with consistent data.
e.g.
```
Mr. John Doe (jdoe@example.com)
Montreal, QB, Canada
+1 250 218 50 78
```
Is there any way to achieve it? Like defining a "profile" for the next generation or giving a country code to the formatters so they would only generate data (phone number as example) for the given country?

Thanks for your amazing tool.

tim

**Comment by fzaninotto** [comment]
Hi Tim,

No, unfortunately this is not possible for the moment.

Cheers

**Comment by sameernyaupane** [comment]
This would be really handy to simulate a consistent profile for verification. I wish this could be added to Faker.
