### ISSUE TITLE
Doctrine entities are created without calling their constructor

### ISSUE THREAD

**Issue by vith** [fzaninotto/Faker#558]
This means if you do things like assign empty doctrine ArrayCollection instances to relation properties in the constructor so you can always access the property in a consistent way, you end up with errors such as "Call to member function count() on null" whenever Faker created the entity.

**Comment by liwo** [comment]
If used with the Neos Flow framework this behavior is especially bad as Flow uses UUIDs for primary keys and these are generated in the constructor. If the constructor is not called the entities have no primary key and inserting them into the database consequently fails.

**Comment by fzaninotto** [comment]
See https://github.com/hautelook/AliceBundle
