### ISSUE TITLE
Missing regexify() method

### ISSUE THREAD

**Issue by rhysp** [fzaninotto/Faker#561]
Documentation of **Faker\Provider\Base** presents an example of _regexify()_ but this method is not found in the latest codebase.

**Comment by fzaninotto** [comment]
It is available on the master branch, not yet released with a tag number.

**Comment by paquitodev** [comment]
@fzaninotto I think your bundle is installed as a dependencies from `h4cc/alice-fixtures-bundle": "^0.5.1` how do I force composer to use master branch instead of the branch setup as dependency in AliceFixturesBundle?
