### ISSUE TITLE
Disable CakePHP Model Behavior before populating data

### ISSUE THREAD

**Issue by aydot** [fzaninotto/Faker#568]
Is there a way/or could you provide a config to remove behaviors from a table before data gets populated?

**Comment by fzaninotto** [comment]
ping @jadb

**Comment by jadb** [comment]
Definitely. Adding this to my todo :) Thanks for pinging @fzaninotto!

**Comment by aydot** [comment]
Will this suffice?
```
        if (isset($options['behaviors']) && $options['behaviors'] === false) {
            $behaviors = $table->behaviors()->loaded();
            array_walk($behaviors, [$table, 'removeBehavior']);
            unset($options['behaviors']);
        }
```
right before save is called?

**Comment by aydot** [comment]
Also, on [https://github.com/fzaninotto/Faker/blob/master/src/Faker/ORM/CakePHP/EntityPopulator.php#L82]

Would you consider skipping the belongsTo if the key is passed in to $customColumnFormatters ?
This will prevents needless records from being created.
```
                if ( ! empty($this->columnFormatters[$assoc->foreignKey()])) {
                    return $data;
                }
```

**Comment by fzaninotto** [comment]
ping: any updates on this one?

**Comment by pimjansen** [comment]
@jadb pretty any updates still on this? Else we will close it as a stale issue.
