### ISSUE TITLE
Unknown formatter "regexify"

### ISSUE THREAD

**Issue by paquitodev** [fzaninotto/Faker#571]
I'm trying to use `regexify` faker from [NelmioAlice][1] in a fixture as follow:

    state_licensed: <regexify('(?=.{12}$)([a-z]{1,7}[a-z|0-9|*]{5,11})')>

But I got:

> Unknown formatter "regexify"

Why? Do I need to include something else?

  [1]: https://github.com/nelmio/alice

**Comment by TimWolla** [comment]
#561

**Comment by paquitodev** [comment]
Fixed by setting this `"fzaninotto/faker": "dev-master as 1.0.0",` at `composer.json`, thx for the tip @TimWolla
