### ISSUE TITLE
Ideas for write a custom faker that works with Doctrine ArrayCollection

### ISSUE THREAD

**Issue by reypm** [fzaninotto/Faker#576]
I have this piece of code in a entity:

    class Email
    {
        /**
         * @ORM\ManyToMany(targetEntity="Media", inversedBy="mediaXrefMail", cascade={"persist", "remove"})
         * @ORM\JoinTable(name="emails_media_xref",
         *      joinColumns={@ORM\JoinColumn(name="emails_id", referencedColumnName="id")},
         *      inverseJoinColumns={@ORM\JoinColumn(name="media_id", referencedColumnName="id")}
         * )
         */
        protected $emailsMediaXref;

        /**
         * @ORM\ManyToMany(targetEntity="Message", inversedBy="messageXrefMail", cascade={"persist", "remove"})
         * @ORM\JoinTable(name="emails_messages_xref",
         *      joinColumns={@ORM\JoinColumn(name="emails_id", referencedColumnName="id")},
         *      inverseJoinColumns={@ORM\JoinColumn(name="messages_id", referencedColumnName="id")}
         * )
         */
        protected $emailsMessageXref;

        public function __construct()
        {
            $this->emailsMediaXref = new ArrayCollection();
            $this->emailsMessageXref = new ArrayCollection();
        }
    }

Any time I try to run fixtures using Nelmio/Alice I got this error:

> [Symfony\Component\Debug\Exception\ContextErrorException] Catchable Fatal Error: Argument 1 passed to 
> Doctrine\Common\Collections\ArrayCollection::__construct() must be of the type array, object given, 
> called in /var/www/html/reptooln_admin/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 555 and defined

I need some ideas for write a small faker that cover the issue, can any help me here?

**Comment by fzaninotto** [comment]
ping @beberlei @terite

**Comment by fzaninotto** [comment]
Sorry, I have no Doctrine knowledge to help you on that one.
