### ISSUE TITLE
Unable to find provider “Images” with locale “en_US”

### ISSUE THREAD

**Issue by FerchoCarcho** [fzaninotto/Faker#577]
Im trying to Feed my database but when I run php artisan db:seed I get that error.

Can you tell me what is happening noting that I could Fed the database in earlier days.

**Comment by fzaninotto** [comment]
I don't know how `artisan db:seed` works, please refer to the team making this command.

**Comment by minhlong** [comment]
the same problem when i build with laravel 5.2 :)
