### ISSUE TITLE
Sports Team Fakers

### ISSUE THREAD

**Issue by aloha** [fzaninotto/Faker#578]
Anyone interested in the addition of sports teams?  I started this in a fork but curious if @fzaninotto is interested in a pull request with the additional information when completed.

Pro Football
Pro Hockey
Golf
Tennis
Soccer (UK & American)
Basketball
Baseball  ....etc

**Comment by fzaninotto** [comment]
This is a great idea, but I don't believe it belongs to the core. As you know, it's very easy to extend Faker with your own providers, so I suggest you create a standalone provider, host the repository on your Github account, and I'll be very happy to link to it from Faker's readme file.

**Comment by aloha** [comment]
:+1:
