### ISSUE TITLE
tagging?

### ISSUE THREAD

**Issue by cordoval** [fzaninotto/Faker#579]
it is going to be a year now since last tag? any chance to at least get a lowest number bump up please? :+1: thanks

**Comment by GrahamCampbell** [comment]
Duplicate. Please close this.

**Comment by GrahamCampbell** [comment]
See https://github.com/fzaninotto/Faker/issues/463.

**Comment by cordoval** [comment]
no @GrahamCampbell please read carefully, I am not begging for 1.5.0, I am begging for a minor bump

**Comment by GrahamCampbell** [comment]
You mean a patch release? There's never going to be another patch release since the code in here already needs a minor release.

**Comment by cordoval** [comment]
oh it has BCs? did not know that. Then i am closing.
