### ISSUE TITLE
Arrays with multiple values not echoing correctly

### ISSUE THREAD

**Issue by elarue** [fzaninotto/Faker#586]
I am attempting to post something using the templates that use arrays of multiple values, but only the first element is echoing correctly.  Namely, I have tried using the randomElements template from the "Base" file, as well as the "words" template from the Lorem file.  In each case, only the first element gets returned.

Here is the PHP code I have tried implementing:

$array = array ('a','b','c','d','e');
$count = 2;
foreach($faker->randomElements as $nextElement){
	echo $nextElement . ', ';
}

I am wondering if it is because the function appears to be hard coded with an array of three elements (a, b, c) and a $count = 1;

**Comment by ikwattro** [comment]
There is no meaning of variable initialization, you need to pass it as argument to the method call : 

```
$array = array ('a','b','c','d','e');
$count = 2;
foreach($faker->randomElements($array, $count) as $nextElement){
echo $nextElement . ', ';
}
```

Related to #587

**Comment by elarue** [comment]
Thank you!
