### ISSUE TITLE
randomNumber don't return good number

### ISSUE THREAD

**Issue by jcodt** [fzaninotto/Faker#592]
Sometimes randomNumber with param's don't return good number.

I try this 
```php
$faker->randomNumber(5)."-".$faker->randomNumber(5)."-".$faker->randomNumber(5);
```
70% of result is good like 
45678-69542-45213

but sometimes the result don't return 15 numbers like
45987-568-45123

**Comment by fzaninotto** [comment]
The parameter `$nbDigits` is a maximum number. If you want to have exactly that number of digits, pass `$strict = true`as second parameter. 

This is all documented, in the formatter phpDoc:

```php
    /**
     * Returns a random integer with 0 to $nbDigits digits.
     *
     * The maximum value returned is mt_getrandmax()
     *
     * @param integer $nbDigits Defaults to a random number between 1 and 9
     * @param boolean $strict   Whether the returned number should have exactly $nbDigits
     * @example 79907610
     *
     * @return integer
     */
    public static function randomNumber($nbDigits = null, $strict = false)
    {
```
