### ISSUE TITLE
[Potential Bug] Image Randomizer Not Working

### ISSUE THREAD

**Issue by vinkla** [fzaninotto/Faker#595]
When setting the `$random` parameter to `false` in the `imageUrl` method it still generates a new image on each page load. Is this expected behavior? 

This is possible to test by reloading an image url like this one: http://lorempixel.com/500/500/cats/

**Comment by fzaninotto** [comment]
Yes, the `$random` is here to prevent that several calls from a single page generate the same image.

**Comment by vinkla** [comment]
The request always return a new image. It doesn't matter if you set it to true or false.

**Comment by vinkla** [comment]
Are you sure this is working correctly?

**Comment by vinkla** [comment]
It seems calling http://lorempixel.com/500/500/cats/ will always return a random image. If you want the same one then you need to add the ID in the end like this http://lorempixel.com/500/500/cats/2 the two being the ID.
