### ISSUE TITLE
Populate a table with static data.

### ISSUE THREAD

**Issue by alexandrebodin** [fzaninotto/Faker#603]
Hello, I have recently started to use this Library and it's great ! Thank you for your work.

I would like to know if you have an elegant way to load static data (e.g.  A simple list of industries with id and name columns maybe from a yaml file) ? 

I thought of using the default propel fixtures loader, but I realised I won't be able to use the generated entities ids as foreign keys in the PropelPopulator. 

The trick I'm currently using is to use a Custom provider which generates a random unique element from my list, but I have to specify the exact number of rows to populate, which is inconvenient and prone to errors. 

Any advise would be appreciated !

**Comment by fzaninotto** [comment]
Hi Alexandre, thanks for the compliment. 

If your list of industries is loaded in memory, you can still use the `randomElement` formatter. It takes an array as argument, and returns... a random element. 

For a more sophisticated approach , take a look at [thephpleague/factory-muffin](https://github.com/thephpleague/factory-muffin) and [nelmio/alice](https://github.com/nelmio/alice).

Hope this helps!
