### ISSUE TITLE
Seeding the generator not consistant

### ISSUE THREAD

**Issue by stefanvangastel** [fzaninotto/Faker#604]
Hi, maybe its my bad but I use the faker->seed(1000) feature to keep the seeding consistant. This works (9 out of 10, sometimes one of the generated uuids is different (?)).

When I add an extra field to my database and add the field to the object I want to save all the data in all the entities is different?

This means that every extra field I add to my db and want to generate data for changes all the generated data? Is this correct?

**Comment by fzaninotto** [comment]
If you can provide a unit test showing that the `uuid` formatter isn't properly following seeding, I'm willing to take a look. But from my point of view, it's implemented correctly.

Seeding works by setting the *initial* seed of a random generator. If you always generate the same number of random numbers based on the same seed, they will be the same. But in your case:

```php
$faker->seed(1);
echo $faker->name; // gets the first random number after the seed (e.g. 1)
echo $faker->phoneNumber; // gets the second random number after the seed (e.g. 2)

$faker->seed(1);
echo $faker->name; // gets the first random number after the seed (e.g. 1)
echo $faker->country; // gets the second random number after the seed (e.g. 2)
echo $faker->phoneNumber; // gets the third random number after the seed (e.g. 3)
```

In the above example, you understand why adding a field in the middle of a series modifies the whole suite after that. 

That's the way random generators work, sorry.

**Comment by Tetragramat** [comment]
@fzaninotto This behavior should be described in documentation under 'Seeding the Generator' section. Not everyone may know how random generators work.
