### ISSUE TITLE
Cannot instanciate abstract class Text

### ISSUE THREAD

**Issue by nitriques** [fzaninotto/Faker#612]
I do not see why this class is abstract.

https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/Text.php#L5

I get error when I try to call `Factory::create()`

**Comment by FayneAldan** [comment]
Download the latest release instead of the master branch. Still, this is a bug that should be fixed.

**Comment by nitriques** [comment]
> You should be able to fix this easily by using the autoloader included with Faker.

Well, that's what I am doing. https://github.com/DeuxHuitHuit/random_entries_generator/blob/master/extension.driver.php#L9

**Comment by nitriques** [comment]
Well I was able to fix the problem by adding an `!empty()` check on that line: https://github.com/fzaninotto/Faker/blob/master/src/Faker/Factory.php#L24


```php
if (!empty($locale) && $providerClass = self::findProviderClassname($provider, $locale)) {
```

**Comment by hypeJunction** [comment]
I am using composer and running into this issue as well. Due to the nature of the application using build-in autoloader is a bit of an issue, so I had to roll back to using version 1.3

**Comment by nitriques** [comment]
Same thing is happening today, with version 1.6.0. I re-applied 4a55edd to solve the problem.

**Comment by pimjansen** [comment]
I cannot reproduce this issue anymore on the 1.8 branch. I will close this issue for now
