### ISSUE TITLE
Get doctrine fake objects without inserting into database ?

### ISSUE THREAD

**Issue by vishalmelmatti** [fzaninotto/Faker#619]
Hi,

Thanks for this awesome library, I am trying to use it in Rest api tests.  I am able to populate fake data in database and run my get request tests. 

But in case of post, I dont want to insert data to database rather I want to generate data and post it to URL. Post resource URL will write it to database and will return json response. I would then want to compare objects generated by faker with response objects. 

$populator->execute();  persits and flush data before returning $insertedEntities. Is there any way to get these $insertedEntities without persisiting to database ?

If its not there in current version, is it worth adding it to this library ?

**Comment by fzaninotto** [comment]
There is currently no way to do that in Faker. I guess what you want is a way to populate an arbitrary object (since Doctrine entities are POPO) with random data. I think it's the purpose of thinks like factory_girl (or its PHP port, [FactoryMuffin](http://factory-muffin.thephpleague.com/).
