### ISSUE TITLE
Annotations to configure doctrine entity fields for which fake data need to be generate ?

### ISSUE THREAD

**Issue by vishalmelmatti** [fzaninotto/Faker#620]
The existing faker Doctrine adapter (EntityPopulator) creates fake data for all fields of doctrine entity. But form might not have all fields.

Should it be configurable (may be with annotations @Faker\Expose)  etc on each entity field something like JMSSerializer does ?

**Comment by fzaninotto** [comment]
No idea, I'm not much into Doctrine these days.
