### ISSUE TITLE
Faking Legitimate Addresses

### ISSUE THREAD

**Issue by browner12** [fzaninotto/Faker#625]
I am using Faker to generate locations for my database. The fields include city, state, zip, latitude, and longitude. The problem I am running into is, while each individual field is legitimate, when combined they make no actual sense.  This can cause problems when testing. For example, with my Google Maps integration, Google has no idea where the address I'm requesting is.

I am not familiar with the inner workings of the package, but what I would like to see is the ability to create full legitimate addresses.

```php
$address = $faker->address;

$city = $address->city;
$state = $address->state;
$zip = $address->zip;
$latitude = $address->latitude;
$longitude = $address->longitude;
```

Thoughts?

**Comment by nineinchnick** [comment]
I'm using Faker together with an address database. First I select a random postcode, then fetch cities matching this postcode and select a random element. Then I do the same with a street.

Faker databases are no related, so to obtain a valid address you need some external data.

**Comment by fzaninotto** [comment]
+1 with @nineinchnick, what you need is an address database, not Faker. Alternative: use Faker to fake geo coordinates, and use geocoder to get the related (correct) address via a web service.
