### ISSUE TITLE
RandomNumber for integer/biginteger for CakePHP fails

### ISSUE THREAD

**Issue by GuidoHendriks** [fzaninotto/Faker#646]
When guessing the column type for CakePHP, `randomNumber` gets called with either `10` or `20` number of digits. This causes an error, because that's above the `mt_getrandmax()` on basically all systems.

The calls causing this issue:
https://github.com/fzaninotto/Faker/blob/master/src/Faker/ORM/CakePHP/ColumnTypeGuesser.php#L24-L31

Maybe just generate a lower random value for those fields? Usually real data won't go to the max of the range anyway.

**Comment by fzaninotto** [comment]
I guess you're right. Other ORMs take a different approach, see https://github.com/fzaninotto/Faker/blob/master/src/Faker/ORM/Propel/ColumnTypeGuesser.php. 

@GuidoHendriks would you mind updating the CakePHP provider? Ping @jadb.
