### ISSUE TITLE
[Feature Request] Setting the Locale

### ISSUE THREAD

**Issue by vinkla** [fzaninotto/Faker#647]
It would be cool if we could change the locale after initiating the factory. Something like this: 

```php
$faker = new Faker\Factory::create();

$faker->setLocale('fr_FR');
```

Currently we've to create a new instance whenever we want to change the localization.

What do you think? Something you would consider adding?

**Comment by fzaninotto** [comment]
Define "cool". I don't understand the use case. You can already setup several Faker instances with different locales.

**Comment by vinkla** [comment]
Maybe cool is the wrong word. My use case is in Laravel. They provide a faker instance by default in their factories. There is no way of updating the current Faker instance instead we've to create our own.

```php
$factory->define(App\User::class, function ($faker) {

    $newFaker = \Faker\Factory::create('fr_FR');

    return [
        'city' => $newFaker->city,
    ];
});
```

Personally I think it looks messy having to instances. Instead I would like to see something like this:

```php
$factory->define(App\User::class, function ($faker) {

    $faker->setLocale('fr_FR');

    return [
        'city' => $faker->city,
    ];
});
```

**Comment by okj579** [comment]
You should just configure the container to set the right locale itself.

**Comment by vinkla** [comment]
There are ways to handle it. Like overwriting registration of the current Factory. Though, it would still only give me one locale at the time.

**Comment by vinkla** [comment]
I don't know, maybe this is something that should be done in Laravel. The current implementation works just fine. This could just be a personal preference.

**Comment by fzaninotto** [comment]
I don't know Laravel, but when I see a "factory" method, I expect it to return a new instance. Your first example modifies another instance, it's a code smell. 

Anyway, I don't understand the use case and you have other options, so I'll close. 

Thanks for the suggestion anyway.

**Comment by vinkla** [comment]
No worries, thanks anyways.
