### ISSUE TITLE
null values after several calls

### ISSUE THREAD

**Issue by cordoval** [fzaninotto/Faker#651]
This below gives null on the second call, not sure why

```php
$faker->phoneNumber;
$faker->phoneNumber;
```

**Comment by okj579** [comment]
What locale are you using?

**Comment by cordoval** [comment]
default_locale:  "%locale%"

locale: en

**Comment by fzaninotto** [comment]
Can't reproduce on my side. Can you isolate a particular seed to reproduce the issue?

```php
<?php
require __DIR__ .'/../vendor/autoload.php';

$faker = Faker\Factory::create();

for ($i=0; $i < 10; $i++) {
  echo $faker->phoneNumber, "\n";
}
```

Also, what's your platform (OS version, 32/64 bits, PHP version)?

**Comment by cordoval** [comment]
php5.6.11
OSX
64bit mac retina pro

I will try when i get home

**Comment by fzaninotto** [comment]
No news for some time, closing.
