### ISSUE TITLE
dateTimeInInterval() formatter listed in documentation but is not in library

### ISSUE THREAD

**Issue by ajskelton** [fzaninotto/Faker#652]
I was trying to use the dateTimeInInterval formatter but kept getting the error:

[InvalidArgumentException]
Unknown formatter "dateTimeInInterval"

After digging into the src files I saw this formatter wasn't in the library anymore. I looked through previous versions but couldn't find a time when it did exist. Not sure if it was supposed to be removed from the documentation and was just missed.

**Comment by fzaninotto** [comment]
It is in the master branch, not yet released. Use the master branch if you want the latest formatters.
