### ISSUE TITLE
Faker Truck Factor

### ISSUE THREAD

**Issue by gavelino** [fzaninotto/Faker#656]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Faker** and obtained a value of **21**.

The developers responsible for this TF are:

Francois Zaninotto - author of 26% of the files
John Was - author of 10% of the files
Bernhard Essl - author of 3% of the files
Hugo Fonseca - author of 3% of the files
Tz-Huan Huang - author of 3%% of the files
Tim Dusterhus - author of 2% of the files
Roman Shvets - author of 3% of the files
umpirsky - author of 3% of the files
Domingo Oropeza - author of 1% of the files
ognjen miletic - author of 1% of the files
bazo - author of 1% of the files
Abu Ashraf Masnun - author of 1% of the files
Mikulas - author of 1% of the files
WouterJ - author of 1% of the files
toin0u - author of 1% of the files
Wim Vandersmissen - author of 1% of the files
pdaether - author of 1% of the files
AlesÌŒ FarcÌŒnik - author of 1% of the files
YAMANE Nana - author of 1% of the files
zaid-86 - author of 1% of the files
Huy TQ - author of 1% of the files

To validate our results, we would like to ask **Faker** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Faker**?

(b) Do you agree that **Faker** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Faker** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by Anahkiasen** [comment]
> if they win in the lottery, to be less morbid

u wot m8

**Comment by nineinchnick** [comment]
In my biased opinion Fakers strongest point is large number of supported locale. Devs usually speak two languages, native one and english, so most people contribute to single locale. That's a unique characteristic of Faker, compared to other projects like frameworks.

Exceptions to this are standarts, like IBAN and VAT numbers (I can't wait for #594 to get accepted).

Here's my answers:
(a) I contributed in a short period of time. Now I just watch, waiting for new interesting generators that can be localized. So I wouldn't consider myself a main dev.
(b) Not as devs, but Francois is doing fantastic work as a maintaner, keeping the quality high.
(c) Lots of examples in other locale helps to pick up the work, for example the Luhn algorithm for generating various numbers like bank accounts. There is no contribution tips written down but the PR comments history would be a good reference.

PS. What does Y stand for? I'd expect the TF to be a number.

**Comment by gavelino** [comment]
Sorry, I forgot to replace Y by TF value of the project. The TF calculated for Faker is 21.

Jan Waś, thanks for your answer.
