### ISSUE TITLE
Please tag a new stable version of the library

### ISSUE THREAD

**Issue by stof** [fzaninotto/Faker#658]
Many changes have been done since the 1.5.0 release. It would be great to make a new release including them.
For anyone using the default Composer settings (allowing only stable versions of packages), any unreleased change is quite the same than non-existent change (``quite`` is because there is still a way to force composer to consider dev versions)

**Comment by fzaninotto** [comment]
What new features do you so desperately need?

1.5.0 is only two months old. Releasing a new version requires some work, and I can't do that six times a year. 1.6 won't happen before a month or two.

**Comment by stof** [comment]
@fzaninotto Do you have an ETA for the release ?

**Comment by fzaninotto** [comment]
No, sorry.
