### ISSUE TITLE
Float MUST have a "dot" ?

### ISSUE THREAD

**Issue by apsylone** [fzaninotto/Faker#661]
Sometimes, random value gives value without "dot". I think, float number MUST returns always a "dot" and value. I had the case for the number "1". I think it should be "1.0xxx".

Am I wrong ?

**Comment by akireikin** [comment]
Agree. Came across with some strange behaviour because of that.

**Comment by okj579** [comment]
When a float is cast to a string, PHP uses the shortest representation. They don't have to have a dot.
```
$ php -r 'echo 1.0;'
1
```

**Comment by akireikin** [comment]
I use Faker with Codeception. When I test my JSON API strange bug appeared. One of my tests failed in 10% percent cases.

```php
// by default in 10% cases Faker generate float with 0 digits after the dot
$message = ['number' => $faker->randomFloat()];

// simplified JSON request-response processing
$response = json_decode(json_encode($message), true);

// in 10% cases I get false (test failed)
var_dump($message === $response);
```

The number in `$message` array has type `float` while the number in `$response` array has type `int`.

**Comment by okj579** [comment]
Unfortunately, this is part of how `json_encode` works. As of PHP 5.6.6, you can add the option [`JSON_PRESERVE_ZERO_FRACTION`](http://php.net/manual/en/json.constants.php#constant.json-preserve-zero-fraction) to make it output floats as floats.

**Comment by akireikin** [comment]
Thank you. Exactly what I need.
