### ISSUE TITLE
E.164 phone number generator

### ISSUE THREAD

**Issue by martinlindhe** [fzaninotto/Faker#668]
Hello. Is there an E164 number generator in here somewhere?
If not, would one be accepted if i produced a patch?

I'm in the need to seed database with some random phone numbers, but db rarely store phone numbers as those generated by the "phoneNumber" formatter.

E.164 numbers looks like this "+442193483844", ie always a leading +, always country code, never leading zero in area code.

https://en.wikipedia.org/wiki/E.164

**Comment by ibarral** [comment]
+1

**Comment by fzaninotto** [comment]
Closing this one, as the discussion continues in #753
