### ISSUE TITLE
[Proposal] Generate Random Base64 Images

### ISSUE THREAD

**Issue by vinkla** [fzaninotto/Faker#671]
What do you think? Is generating random base64 images a feature you would be interested in adding?

**Comment by fzaninotto** [comment]
No. I really don't see the use. Faker can generate random images, but if you want to get fancy with formats (TIFF/PNG/GIF/Base64/Whatever), it's your job, not Faker's...

**Comment by vinkla** [comment]
Okay.

**Comment by mikebsg01** [comment]
I think it could be a good idea for a new feature, I need something like that in this moment.

**Comment by shez1983** [comment]
i think generating a base64images should be be something faker can do.. its not about getting fancy its about generating random base64 images..

**Comment by didotsonev** [comment]
+1 for faker base64 images

**Comment by malohtie** [comment]
it will be useful to see this function
