### ISSUE TITLE
Extend latitude/longitude to have (locale?) bounding areas

### ISSUE THREAD

**Issue by xfxf** [fzaninotto/Faker#684]
Hi, the built in latitude/longitude generators are an amazing idea but they're not too useful for me right now as they spill out worldwide.

Two ways I'd like to see this extended (I'm happy to have a go at writing the code if you can indicate if this is preferred + if so, which way):

* Allow latitude() and longitude() to have a min and a max fed into it,
* Allow each locale to define bounding areas these functions should use.  Most countries don't fit into a nice square, so this is obviously more complicated to implement (array of points to bound within?)

**Comment by xfxf** [comment]
Ah, I've just noticed that a few of the locales do have latitude() and longitude() defined.  I'll submit a PR for my locale (en_AU) but it's going to be a little janky due to (2), so feedback still appreciated.

**Comment by fzaninotto** [comment]
Latitude and longitude should not be extended, see #387
