### ISSUE TITLE
Make optional and unique stackable

### ISSUE THREAD

**Issue by ravage84** [fzaninotto/Faker#685]
Today I had a requirement of a value that needed to be unique but could be omitted.

It would be nice to be able to stack ``optional()`` and ``unique()``.
Certainly this would only work in one way:
```` php
$faker->optional()->unique()->name
````
But not in the other:
```` php
$faker->unique()->optional()->name
````

**Comment by fzaninotto** [comment]
Are you sure it doesn't work yet?

**Comment by ravage84** [comment]
No, it seems not.
I get a ``Fatal error: Call to a member function randomElement() on a non-object``, when I try to execute ``$faker->optional()->unique()->randomElement();``

**Comment by fzaninotto** [comment]
All right, so modifiers aren't stackable, it it's really easy to achieve with two ad hoc PHP statements. So no modification to Faker is actually needed.
