### ISSUE TITLE
Uniqueness in conjunction with

### ISSUE THREAD

**Issue by ravage84** [fzaninotto/Faker#686]
May be this is out of scope of Faker, but often I need values for a field A that is only valid if it is unique in conjunction with field B.

So, for example, I have a ``networks`` table that I want to get populated.
And my data validation prevents me from saving duplicated networks.
Dupllicated means that the ``network_ip_address`` and the ``netmask`` combination must not exist already.

Certainly I can implement specific code to prevent collisions, but I thought I throw this in to be discussed since I believe this problem could be common enough to consider a solution provided by Faker.

**Comment by fzaninotto** [comment]
This is not in the most common use cases IMO, so not something for Faker core to take care of. But feel free to develop a new provider and open-source it!
