### ISSUE TITLE
Subnet IPv4 formatter

### ISSUE THREAD

**Issue by ravage84** [fzaninotto/Faker#687]
I've developed a derived version of the ipv4 formatter.

You can pass a subnet bitmask (8 - 32) and get a valid network/subnet IPv4.

So instead of getting ``192.168.1.153`` you get 
``192.168.1.128`` for subnet ``25``
``192.168.1.0`` for subnet ``24``
``192.168.0.0`` for subnet ``16``
``192.0.0.0`` for subnet ``8``
etc.

This helps if you want to get valid network and subnet IPv4 addresses.
If this is interesting for the library, I will create a PR.

```` php
/**
 * A valid IPv4 for a given bitmask
 *
 * @param int $bitmask A bitmask between 8 and 32.
 * @return string
 * @throws OutOfBoundsException If bitmask is invalid.
 */
public function subnetIpv4($bitmask) {
	if ($bitmask < 8 || $bitmask > 32) {
		throw new OutOfBoundsException('Bitmask must be between 8 and 32');
	}
	$ip = $this->generator->ipv4;
	$ip = ip2long($ip) & (-1 << (32 - $bitmask));
	$ip = long2ip($ip);
	return $ip;
}
````

**Comment by fzaninotto** [comment]
Yes, i think it's interesting, but I would do taht directly in the `ipv4` formatter.

Feel free to open a PR!
