### ISSUE TITLE
RFC: Only use functions but not prroperties as formatter method

### ISSUE THREAD

**Issue by ravage84** [fzaninotto/Faker#688]
It is certainly more convenient to call ``$this->name`` as a property to generate data instead of having to call ``$this->name()`` as a function. You're saved from writing an additional ``()`` __each time__! :trollface: 

But seriously, I think, at the moment, Faker lacks a consistent API.
For some formatters you need to call them as property, for some you need to call them as function.
While I understand the reasoning behind it, I feel Faker could benefit from not using properties at all to generate data in future versions.

Also, this would make unit testing easier, since right now, I have to mock a Generator object and assert in some cases that ``__call`` gets called an in some ``__get`` gets called.

**Comment by fzaninotto** [comment]
I don't understand. You can already use both syntax in your code:

```php
echo $faker->phoneNumber; // (998)031-4637
echo $faker->phoneNumber(); // 1-491-867-3560
```

By the way, unit testing should not use the generator but directly the formatter *method*.

**Comment by ravage84** [comment]
Hm... it seems this is not documented explicitly. Or have I missed something?
Though you can find an example in the ``README.md`` where ``ean13`` gets called as function ``$generator->ean13();``, instead of as a property.

May be a note could be iadded in https://github.com/fzaninotto/Faker#basic-usage or https://github.com/fzaninotto/Faker#faker-internals-understanding-providers .

Anyway, what I initially thought to propose was the deprecation of accessing the data through properties and only allow access through function calls.

I'm currently unit testing a re-iplementation of https://github.com/fzaninotto/Faker/blob/master/src/Faker/ORM/CakePHP/ColumnTypeGuesser.php and I assert that for certain column types certain Generator prperties/methods get called. Asserting the actual return value is not secure in my opinion. Not even with a fixed seed.

For example:
```` php
// Mock Faker's Generator to create expectations
$this->_faker = $this->getMock('\\Faker\\Generator', array('__get', '__call'));

// Test that boolean gets accessed for booleans
$this->_faker->expects($this->at(0))->method('__get')->with($this->equalTo('boolean'));
$column['type'] = 'boolean';
$result = $this->_guesser->guessFormat($column);
$result();

// Test that randomNumber gets called for integers
$this->_faker->expects($this->at(0))->method('__call')->with($this->equalTo('randomNumber'));
column['type'] = 'integer';
result = $this->_guesser->guessFormat($column);
$result();
````

**Comment by fzaninotto** [comment]
I don't want to deprecate the usage of property calls.
