### ISSUE TITLE
Erroneous example at beginning of the README

### ISSUE THREAD

**Issue by vlakoff** [fzaninotto/Faker#692]
In [Basic Usage](https://github.com/fzaninotto/Faker#basic-usage) section of the README I'm reading the following:

    echo $faker->text;
      // Sint velit eveniet. Rerum atque repellat voluptatem quia rerum. Numquam excepturi
      // beatae sint laudantium consequatur. Magni occaecati itaque sint et sit tempore. Nesciunt
      // amet quidem. Iusto deleniti cum autem ad quia aperiam.
      // A consectetur quos aliquam. In iste aliquid et aut similique suscipit. Consequatur qui
      // quaerat iste minus hic expedita. Consequuntur error magni et laboriosam. Aut aspernatur
      // voluptatem sit aliquam. Dolores voluptatum est.
      // Aut molestias et maxime. Fugit autem facilis quos vero. Eius quibusdam possimus est.
      // Ea quaerat et quisquam. Deleniti sunt quam. Adipisci consequatur id in occaecati.
      // Et sint et. Ut ducimus quod nemo ab voluptatum.

This seems to be wrong, as `text` generates no more than 200 chars by default.

**Comment by fzaninotto** [comment]
True. Would you mind sending a PR to fix it?

**Comment by fzaninotto** [comment]
Fixed by #694
