### ISSUE TITLE
[Proposal] ascending() and descending() modifiers

### ISSUE THREAD

**Issue by vlakoff** [fzaninotto/Faker#695]
I thought about adding an `ascending()` modifier, to ensure generated numbers, dates, etc. are in ascending order. Shipping it with a `descending()` modifier, for completeness. Basically, it would be pretty like the `unique()` modifier.

Do you think it would be a good addition?

**Comment by fzaninotto** [comment]
What's the use case?

**Comment by vlakoff** [comment]
I had this idea while working on a CMS, where published articles have ascending timestamps. Of course it *seems* to also work with shuffled timestamps, but this way the generated sample dataset is closer to real usage. Moreover, some methods might assume the correct ordering in DB (ie. they don't add an `ORDER_BY created`)…

It *might* also be helpful for testing custom "select random" implementations for MySQL ([examples](http://www.warpconduit.net/2011/03/23/selecting-a-random-record-using-mysql-benchmark-results/)), on fields being ordered but with holes.

Nonetheless, these are quite peculiar examples, and I probably could live without the modifiers I'm proposing. But maybe people could think of other uses?

**Comment by drodil** [comment]
This would require generator that generates multiple data entities with one call. Something like:

```php
$faker->order($num = 5, $order = 'asc')->address
```

Not bad idea in my opinion but ordering different types of information is not so straight forward. Numeric and text types are easy but then there is DateTime and other objects (?) which need to be handled separately.

**Comment by fzaninotto** [comment]
Fakrer isn't a general purpose library. It's not Faker's job to re-implement features like `array_map()`
