### ISSUE TITLE
state / stateAbbr the same

### ISSUE THREAD

**Issue by josephzidell** [fzaninotto/Faker#697]
I'm generating a full address and verifying after. Data input accepts a statename, and verification happens with the abbreviation. When I generate a ->state and ->stateAbbr, they are not the same, even when using seed.

Is there a way to get the same state or is this a bug?

**Comment by vlakoff** [comment]
This is normal behaviour, the two generated items are completely independent from each other.

**Comment by fzaninotto** [comment]
Duplicate of #625
