### ISSUE TITLE
How about a generator for a CRONtab interval?

### ISSUE THREAD

**Issue by danielrhodeswarp** [fzaninotto/Faker#705]
How about a generator for a CRONtab interval?

You know, like "* * * * *" or "*/10 * * * *" or "59 23 1-7 * 5" or what-have-you?

A bit niche though obviously :-)

**Comment by fzaninotto** [comment]
Great idea, but as you said, a bit niche. But it's easy to do as a standalone repository, see https://github.com/fzaninotto/CompanyNameGenerator.

**Comment by danielrhodeswarp** [comment]
Cool, thanks man.

**Comment by TimWolla** [comment]
In fact there already is one in the README: https://github.com/swekaj/CronExpressionGenerator

**Comment by fzaninotto** [comment]
Indeed, thanks Tim!

**Comment by danielrhodeswarp** [comment]
Awesome! Many thanks for this. You guys are the best guys ever! I'm loving this Faker stuff by the way, it's useful for so many different things :-)

**Comment by fzaninotto** [comment]
@danielrhodeswarp Thanks! Don't hesitate to publicize your enthusiasm in a blog post or a tweet to make Faker even more popular!
