### ISSUE TITLE
$buildingNumber can be 0, 00, 000

### ISSUE THREAD

**Issue by xfxf** [fzaninotto/Faker#706]
Hi there, $buildingNumber can actually produce numbers like 0, 00, 000.  Is this actually valid anywhere in the world?

Happy to provide a patch, just verifying if this is intentional behaviour first.

**Comment by fzaninotto** [comment]
Nope, you're right, it'a a bug.

**Comment by okj579** [comment]
According to Wikipedia, house numbers sometimes start at 0, with at least one example in the UK. Faker probably doesn't need to generate them though.
https://en.wikipedia.org/wiki/House_numbering

**Comment by vlakoff** [comment]
Replacing e.g. `###` with `%##` in `$buildingNumber` property of [Provider/Address](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/Address.php), [Provider/en_US/Address](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/en_US/Address.php), etc. should do the job.

Note that [Provider/fr_FR/Address](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/fr_FR/Address.php) is already correct (it even has RNG weighting!). I haven't checked the rest.
