### ISSUE TITLE
Datetime formatter "min" option

### ISSUE THREAD

**Issue by adrianbj** [fzaninotto/Faker#726]
Thanks for a fantastic library - just wondering if I am missing something, or if you would consider adding a "min" option to go along with "max" for the Datetime formatter.

I'd be happy to put together a PR if you would be amenable to adding support for this.

**Comment by fzaninotto** [comment]
Hi adrianbj, and thanks for your happy feedback!

For your use case, you should use `dateTimeBetween()`.

**Comment by adrianbj** [comment]
Thanks @fzaninotto - that of course works, but I was thinking that a min option would provide a little more flexibility so it could be used with unixTime etc, but I guess it would actually require quite an overhaul to implement and it is not really necessary.
