### ISSUE TITLE
protected static function iban 

### ISSUE THREAD

**Issue by InfoTracer** [fzaninotto/Faker#745]
Why is the iban function protected in Faker/Provider/Payment.php? Because when i try to call it from Alice i gets this warning 'Warning: call_user_func_array() expects parameter 1 to be a valid callback, cannot access protected method Faker\Provider\Payment::iban()'.

File: https://github.com/fzaninotto/Faker/blob/v1.5.0/src/Faker/Provider/Payment.php#L213

**Comment by okj579** [comment]
In v1.5.0, `iban()` was not part of the public API and only used by localized providers to implement `bankAccountNumber`. In the next version, it will become public. 
https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/Payment.php#L214

**Comment by InfoTracer** [comment]
Thanx! It's also not in the docs of 1.5.0. I was spoiled by the docs of the master banch :(

I appreciate you took the time to answer my issue!

**Comment by elkenzi** [comment]
Si on ouvre par exemple la classe abstractService on va avoir comme method geters/seters plus les services les autres traitement sont dans les traits idem pour par exemple userRepository on trouve seulement les méthodes propores aux repositories les restes se trouve dans le TTP\ApiBundle\Traits\Repository\Organization\UserTrait
