### ISSUE TITLE
Unique doesn't work with words.

### ISSUE THREAD

**Issue by berpcor** [fzaninotto/Faker#748]
```
\Faker\Factory::create()->unique()->words(14);
```

returns 

```ErrorException in UniqueGenerator.php 
line 50: array_key_exists(): The first argument should be either a string or an integer```

(Laravel)

Is it normal?

**Comment by berpcor** [comment]
Damn...
I just need 250 unique words.

for ($i = 1; $i <= 250; $i++) {
      $iadefaults[] = $faker_iattributes_label->unique()->word();
}

gives me 

Maximum retries of 10000 reached without finding a unique value

How to generate unique words???

**Comment by fzaninotto** [comment]
For your need of unique words, don't use the `Lorem` provider, but create a custom provider based on a dictionary (as in #754). This won't be merged to Faker core, though.
