### ISSUE TITLE
Class 'Faker' not found

### ISSUE THREAD

**Issue by Adagal** [fzaninotto/Faker#750]
I installed the library with:
composer require fzaninotto/faker --dev

On my Seeder I have
use Faker\Factory as Faker;

But I get the error "Class 'Faker' not found" again and again. What I need for use it in my seeds?

**Comment by engelju** [comment]
Did you include the composer autoloader with `require 'vendor/autoload.php'` within the main entry point in your application?

Can you please try out the basic example outlined in the [README](https://github.com/fzaninotto/Faker#basic-usage)?

**Comment by fzaninotto** [comment]
No response from the author, closing.
