### ISSUE TITLE
accept Traversable inside randomElement/randomElements

### ISSUE THREAD

**Issue by maryo** [fzaninotto/Faker#762]
Hi. What about accepting any traversable instead of just an array inside randomElement/randomElements? Would such a PR be accepted or is it considered as a BC break (it probably is since it's public)?

And why `$count` inside `randomElements` defaults to 1? It has actually almost the same behavior (with the default value) as `randomElement`, it just can't return `null`. I think it would be more convenient to accept also null and `count($array)` in such case. But that would be even a bigger BC break OFC if it was the default value :-/.

**Comment by fzaninotto** [comment]
No BC break possible, sorry.
