### ISSUE TITLE
Make locale and country match

### ISSUE THREAD

**Issue by rulrok** [fzaninotto/Faker#771]
# Problem

It would be helpful if such locale related methods, when called one after the other, could make the results consistent rather then only generating them randomly.

See one example that I have for this

```php
$factory(\App\Language::class, [
    'language_code' => $faker->locale,
    // I know, this is not the language name,
    //yet it would have some relevance for data consistency,
    //after all, this is only for making testable objects.
    'language_name' => $faker->country 
]);
```

# Proposed solution
Maybe `$faker->country` could be called passing the `locale` code to return the appropriate name

```php
  $country = $faker->country($faker->locale);
```

The same would apply for all other related methods such as 

```php
  $country = $faker->country($faker->countryCode);
```

**Comment by fzaninotto** [comment]
I don't know where your `$factory` comes from, but that's not the main Faker API. A faker instance is already based on a locale (see [the constructor documentation](https://github.com/fzaninotto/Faker#localization)).

**Comment by rulrok** [comment]
@fzaninotto The `$factory` is not important here. This is just from [TestDummy](https://github.com/laracasts/TestDummy) package that uses your Faker package. This is just one real life application of your package. The `$faker` variable IS about your package. Sorry for the confusion.

I'm _not_ referring the [Localization](https://github.com/fzaninotto/Faker#localization) feature of faker, but rather about the [Miscellaneous provider](https://github.com/fzaninotto/Faker#fakerprovidermiscellaneous) which allows to generate valid `locale codes`.

**Comment by fzaninotto** [comment]
This is a recurrent question, and not an ability Faker can have in the short term.
