### ISSUE TITLE
Add labels to Pull Requests

### ISSUE THREAD

**Issue by Newman101** [fzaninotto/Faker#774]
Hello.

Just a small suggestion: Could it be possible to add labels to categorize pull requests, please? 

It makes it a bit easier to filter through especially if there are a lot of un-merged PR's. 

Thank you.

**Comment by fzaninotto** [comment]
Which labels do you thinnk would make sense?

**Comment by Newman101** [comment]
Few suggestions: Bug, Problem, Feature, Enhancement, Optimization.

**Comment by Newman101** [comment]
As a further suggestion, I would strongly advice that red colour is being used in Problem and Bug tags as those tags are considered to be high priority in general.

**Comment by fzaninotto** [comment]
I've made it simpler and added only 3 labels. thanks for your suggestions.
