### ISSUE TITLE
tollFreePhoneNumber missing from en_US

### ISSUE THREAD

**Issue by jajajaime** [fzaninotto/Faker#794]
Trying to use tollFreePhoneNumber is giving me

```
[InvalidArgumentException]
Unknown formatter "tollFreePhoneNumber"
```

**Comment by okj579** [comment]
Are you using the master branch? This feature hasn't been tagged yet.

**Comment by jajajaime** [comment]
using `"fzaninotto/faker": "^1.5"`

**Comment by okj579** [comment]
Then see the docs for the [current version](https://github.com/fzaninotto/Faker/tree/v1.5.0).

Improved phone numbers  for en_US are coming in the next version.
