### ISSUE TITLE
Faker->dateTime resturn dateTime object not the value

### ISSUE THREAD

**Issue by lemonCMS** [fzaninotto/Faker#797]
Thus creating an error. For now i had to fix all my seeders with an format to get them running again.

Everything is up to date with composer.

I hope this can be fixed soon.

Kind regards,
Raymond

**Comment by Thijmen** [comment]
When you look at the documentation (https://github.com/fzaninotto/Faker#fakerproviderdatetime), you see that dateTime returns a DateTime object. What's your point? You can always do a `$faker->dateTime()->format('d-m-Y')`

**Comment by lemonCMS** [comment]
hmm, then nevermind, but until last week i was able to just do the following in the db seeder

$faker->dateTime() without the format. But perhaps the something in laravel changed that broke this functionality.
