### ISSUE TITLE
Restricting Characters?

### ISSUE THREAD

**Issue by drewclauson** [fzaninotto/Faker#803]
I have an issue where my code blows up when right single quotes get put into the database. 

```
Smith’s Mill Road
```

Unfortunately, my db driver is the root cause of this, not returning certain characters from the database to PHP correctly.  I'm eventually switching out the database, but I'm stuck on accessing SQL Server from Linux for right now (yuck).

Anyways, is there a way to restrict what characters are populated into db fields?  That would be the quick fix for my issue at this point.

**Comment by fzaninotto** [comment]
`preg_replace()`?

It's not in the scope of Faker to handle escaping for all platforms/softwares.

**Comment by drewclauson** [comment]
Thanks, I can use that for sure!
