### ISSUE TITLE
PHP support version

### ISSUE THREAD

**Issue by BePsvPT** [fzaninotto/Faker#810]
Both PHP 5.3 and 5.4 are EOL.

In order to resolve the compatible issues with old php version, it may take lots of time to fix this problem, like the third parameter default value of mb_substr had changed since 5.4.8.

Thus, is that a good idea to support php which version is under maintained?

**Comment by fzaninotto** [comment]
Not for now, sorry.

**Comment by WillGibson** [comment]
I'm just having some fun making things work on PHP 5.5- and 5.6+.

I appreciate not wanting to leave folks still stuck with older versions of PHP in the lurch, but would like to suggest a 2.0 release which drops support for PHP 5.5-. People can still use earlier versions of Faker if they really can't upgrade their PHP to a supported version.
