### ISSUE TITLE
CakePHP 3.x - InvalidArgumentException to relate entities

### ISSUE THREAD

**Issue by edsonmgoz** [fzaninotto/Faker#813]
When I try to relate two entities, faker is not executed correctly and that generates a InvalidArgumentException: 

[InvalidArgumentException]                                      

randomNumber() can only generate numbers up to mt_getrandmax() 

As a result it does not generate the data in the related table let alone the FK. Clarify that I'm not using the method randomNumber() anywhere in my code. I'm working with CakePHP 3.1.7

Please appreciate it if you could check that detail.

Thank you very much for all your great work!

**Comment by fzaninotto** [comment]
I don't use CakePHP, can any of the contributors of this part take a look? ping @jadb @daniel-mueller @pomaxa @davidyell

**Comment by davidyell** [comment]
As a reference, https://github.com/cakephp/bake/issues/162

If you're using [Phinx](https://github.com/robmorgan/phinx) `> 0.5.0` you can now use that for your database seeding, which is part of `cakephp/migrations`.

Using Faker, I used the `$faker->numberBetween(1, 4)`, for some fields, which might give you more reliable results. Although it sounds like you're generating a pretty large dataset.

You might get some more insight from https://github.com/gourmet/faker

**Comment by davidyell** [comment]
I've also just found a random Gist with a pre-configured migration which might prove helpful as a reference.

https://gist.github.com/davidyell/e784e70eb06903a790de

**Comment by edsonmgoz** [comment]
Thank you very much @davidyell !!!
