### ISSUE TITLE
Unique long digit

### ISSUE THREAD

**Issue by approached** [fzaninotto/Faker#816]
Hi @all

i try to create a fake long digit. It has length of 14 digit. 
Example:
`$gtin = $faker->unique()->randomNumber(14);`
Output:

>   [InvalidArgumentException]                                      
  randomNumber() can only generate numbers up to mt_getrandmax()  

Soo, okay than i try to use this:
`$gtin = $faker->unique()->numberBetween(10000000000000, 99999999999999);`
With this function it create a right number but this isn't unique!

Has anybody a idea?

**Comment by fzaninotto** [comment]
How many unique numbers are you trying to create? Since `unique()` keeps the past values in memory, it is far from efficient for storing a large number of values.

**Comment by approached** [comment]
It was 30 numbers.

**Comment by fzaninotto** [comment]
`numberBetween()` can only generate integers up to `mt_getrandmax()` with reasonnable randomness. For your need, instead of using randomNumber, I suggest you use `numerify()` with a string containing a large arrays of `#`.

**Comment by JDsWebService** [comment]
This has helped me so much. I know I might be about 4 years later, but still. Thank you!
