### ISSUE TITLE
Undefined class constant 'PEER'

### ISSUE THREAD

**Issue by ayyoub-** [fzaninotto/Faker#829]
I'm trying to run this script 

`$generator = \Faker\Factory::create();
        $populator = new Faker\ORM\Propel\Populator($generator);
        $fenetre = new Fenetre();
        $populator->addEntity(get_class($fenetre), 5);`

in order to produce a fake date for an entity, but an issue stop my code.

**Comment by fzaninotto** [comment]
You're probably using Propel 2, the Propel generator was made for Propel 1

**Comment by ayyoub-** [comment]
Great, how can i change the version of Propel ?

**Comment by noyessie** [comment]
PLease, I want to help projet to support Propel 2. Can you help me to understand what you are already do and improve it ?
