### ISSUE TITLE
username without a dot(.)

### ISSUE THREAD

**Issue by kadnan** [fzaninotto/Faker#832]
What if I want a username without a dot? Is it possible without doing any string operation?

**Comment by fluo392** [comment]
You can set your own username format in **Faker/Provider/Internet.php** at line 11-14.

**Comment by fzaninotto** [comment]
You can do it easily with a custom formatter, e.g.

```php
public function myCustomUserName()
{
    $format = '{{lastName}}{{firstName}}';
    $username = static::bothify($this->generator->parse($format));
    return strtolower(static::transliterate($username));
}
```
