### ISSUE TITLE
Dummy data with Arabic

### ISSUE THREAD

**Issue by kossa** [fzaninotto/Faker#842]
It's possible to generate dummy data with Arabic ?

**Comment by fzaninotto** [comment]
Yes: 

```php
$faker = Faker\Factory::create('ar_JO');
echo $faker->firstName;
```

Look in the `src/Faker/Provider` for a list of all existing locales.

**Comment by kossa** [comment]
Thank you @fzaninotto :)

**Comment by kossa** [comment]
Thank you @CaddyDz :)
