### ISSUE TITLE
http://lorempixel.com is down, making fake image generator down

### ISSUE THREAD

**Issue by rohithmeethal** [fzaninotto/Faker#851]
Hi just would like to notify you that http://lorempixel.com is down right now, I will try to add some provider, if any one is already have please make pull request.

**Comment by fzaninotto** [comment]
I think it'd be better to ping loremPixel at the beginning of the image test. If it's down, skip the entire ImageTest class. 

Do you think you could work on such a PR?

**Comment by sasin91** [comment]
I vouch for adding support for User defined Url in method: imageUrl.
suggests: http://loremflickr.com

**Comment by Newman101** [comment]
This might be related to #863.

**Comment by bruceheller** [comment]
Another placeholder would be a nice addition as LoremPixel has many troubles recently;

Anyway, if the content of the pictures doesn't matter to you, you might have a look on my image generator provider : https://github.com/bruceheller/images-generator

**Comment by fzaninotto** [comment]
Fixed by #866

**Comment by Tachii** [comment]
[ErrorException]
  copy(http://lorempixel.com/640/480/?34375): failed to open stream: HTTP request failed!

Happens again

**Comment by alshf89** [comment]
guys try [Picsum](https://picsum.photos/) it has same behavior like `LoremPixel`.
just change temporary lorempixel in `src/Faker/Provider/Image.php` file or someone should create a PR for it.
