### ISSUE TITLE
Incorrect locale no_NO

### ISSUE THREAD

**Issue by stelgenhof** [fzaninotto/Faker#854]
Correct me if i'm wrong but there is no such locale no_NO. According to Unicode.org (CLDR) there is nn_NO and nb_NO.

**Comment by nicolaiskogheim** [comment]
Norwegian here. Can confirm.

**Comment by fzaninotto** [comment]
Can you tell me if I should rename the current `no_NO` to either one of the two locales you mentioned, or remove it altogether?

**Comment by stelgenhof** [comment]
Good question. For one of my own projects I have chosen 'nb_NO', but in fact both are equally valid. In the same way 'en_US' and 'en_GB' are both valid locales (albeit in different regions). After doing a bit more research (https://en.wikipedia.org/wiki/Norwegian_language) it looks like 'nb_NO' is the main locale, therefor I opted for that one.

Maybe another expert can shed more lights on this :)

**Comment by nicolaiskogheim** [comment]
'nb_NO' is the main locale, indeed. I would've chosen 'nb_NO', but I'm pretty sure everything is valid 'nn_NO' as well.
