### ISSUE TITLE
Avoid sea latitude and longitudes

### ISSUE THREAD

**Issue by stephen-talari** [fzaninotto/Faker#871]
Random latitude,longitude combination resulting geo points in sea(waters) also. Is it possible to restrict geopoints to land only?

**Comment by okj579** [comment]
Including a world map would be beyond the scope of Faker (try a
mapping/geocoding service for that), however on the master branch you can
set your own bounding box for the coordinates.

**Comment by fzaninotto** [comment]
Yep, Faker won't implement this one.
