### ISSUE TITLE
Create json

### ISSUE THREAD

**Issue by lukasoppermann** [fzaninotto/Faker#872]
Hey,

I am missing the option to create a json object (e.g. just a couple of key value pairs in json). Any chance of that being added? An array would be fine as well, as one could encode it easily.

**Comment by fzaninotto** [comment]
Nope, you have PHP for that. Faker isn't a general purpose utility.

**Comment by Sopheakmorm** [comment]
@lukasoppermann  you can use json_encode with you customer array key_value pair 
`<?php

use Faker\Generator as Faker;

$factory->define(\App\JsonData::class, function (Faker $faker) {
    return [
        'data' => json_encode(
            [
                'id'=>$faker->randomDigit,
                'qty'=>$faker->randomFloat($nbMaxDecimals = NULL, $min = 0, $max = NULL)
            ]
        )
    ];
});
`

Hope this can help you !!!
