### ISSUE TITLE
[InvalidArgumentException] Unknown formatter "jobTitle"

### ISSUE THREAD

**Issue by beningreenjam** [fzaninotto/Faker#873]
I'm getting an unknown formatter issue when calling `Faker\Factory::create('en_GB')->jobTitle`, despite all my other formatters on the same instance of the factory working fine.

UPDATE: By the way, I'm running it under Laravel 5.1 with PHP 7.

**Comment by okj579** [comment]
Are you using the latest version? It's only available on master, not
v1.5.0.

**Comment by dadastudio** [comment]
The same issue with Faker\Factory::create('pl_PL')->vat and Faker\Factory::create('pl_PL')->secondaryAddress. 
Occurs on 1.4 and 1.5.

**Comment by beningreenjam** [comment]
Ah yes, v1.5.

That'll be why then.

**Comment by fzaninotto** [comment]
OK, closing the issue then.
