### ISSUE TITLE
Packagist out of sync?

### ISSUE THREAD

**Issue by gcphost** [fzaninotto/Faker#876]
Is the packagist out of sync? 3 days ago dev-master enabled the latest features in your doc (ie e164PhoneNumber) but today, it gives 1.5, and no features.

Am I doing something wrong?

**Comment by GrahamCampbell** [comment]
No? 1.6.0 has not been released yet.

**Comment by gcphost** [comment]
Had to clear my composer cache, maybe the last update had some effect - or I did something
