### ISSUE TITLE
Data changes when using factory

### ISSUE THREAD

**Issue by kevin93w** [fzaninotto/Faker#895]
Hi there,

Been using Faker in combination with sqLite in-memory database for testing in Laravel lately and I have this strange issue where my model has a factory and everything except the first variable (which happens to also be the primary key of the table) gets set correctly.

Let's explain further, the variable I'm pointing at uses the following rule in the factory:

<code>'kvk' => strval($faker->randomNumber(9)),</code>

So it should become a string containing a 9 digit number. Now the next step is calling the factory from my controller test and I also have another User model which uses this 'kvk' variable from my company as a foreign key reference:

<code>
$this->_company = factory(Company::class)->create([
        'address_id' => $this->_address->id
]);
$this->_user = factory(User::class)->create([
        'kvk' => $this->_company->kvk
]);
</code>

But when I put an <code>echo $this->_company->kvk;</code> in between, it shows me that 'kvk is set to 1, which should not be possible because of the rule I put in my factory.

Finally the user is used to mock the session in the test and is also used to check wether I should have the rights to edit an address using the following check:

<code>
$user = Auth::user();
$company = Company::where('kvk', $user->kvk)->first();
$address = Address::whereId($id)->first();

if($company->address_id != $address->id){
    return abort(403);
}
</code>

So first I get the current logged in user (which is mocked to the created user above, and this works perfectly. Next I get the company associated with this user (which should be the one created above, since I used the company->kvk as a foreign key reference), however when I output the saved Company to my log I see that the kvk is set to a 9 digit string like it's supposed to.

I really can't put my finger on why at first the kvk is set to 1 and afterwards in my test it seems perfectly fine the way it should be, but my test fails because the wrong reference is set in my User so it can't find the right Company. Do you have any idea what could be the reason for this? I've also tried setting the 'kvk' explicitly while creating with the factory, but this also does not work and will stil output 1.

**Comment by fzaninotto** [comment]
Hi, I'm not a Laravel user. From what I can see, your problem isn't with Faker but with Laravel. Please reduce the description of your problem to a reproductible, plain-old-PHP script. Feel free to reopen once you can update the description with a simple test case.
