### ISSUE TITLE
Doctrine Entities with Setter Association Behavior Failing

### ISSUE THREAD

**Issue by bobdercole** [fzaninotto/Faker#910]
Hello,

I am having an issue populating Doctrine entities that have setters that contain behavior. Here is a simplified snippet of problematic code (in an entity):

``` php
public function setCanceled(bool $canceled)
{
    if ($canceled === true) {
        $this->event->decrementActiveAttendeeCount();
    } else {
        $this->event->incrementActiveAttendeeCount();
    }
    $this->canceled = $canceled;
}
```

Upon running Faker, this happens:

```
PHP Fatal error:  Uncaught Error: Call to a member function decrementActiveAttendeeCount() on null in MyEntity.php
```

This started happening when I upgraded to v1.6.0. I assume it's due to [this change](https://github.com/fzaninotto/Faker/commit/42f37ebfefaae438089788436b2033075bdd72ac). My use case would work if #558 is addressed. I could just give my method a better name, but I thought I would bring this up anyhow.

Thanks!

**Comment by fzaninotto** [comment]
ping @beberlei

**Comment by fzaninotto** [comment]
See https://github.com/hautelook/AliceBundle
