### ISSUE TITLE
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value

### ISSUE THREAD

**Issue by abkrim** [fzaninotto/Faker#914]
When try seed a table users using Laravel 5.0, and fzaninotto/faker: ^1.6, get a error, with MariaDB 10.1.14 on Debian Jessie

I can't reproduce this error on normal operations, and also I put a bug on MariaDB 

```
[Illuminate\Database\QueryException]
  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2008-03-30 02:56:12' for column 'created_at' at row 1 (S
  QL: insert into `users` (`type`, `name`, `email`, `nick`, `password`, `vat`, `address`, `zipcode`, `city`, `state`, `country`, `cr
  eated_at`, `updated_at`) values (customer, Adrian Santos, qpuig@live.com, rzavala12, y$Veqd2mkgRHtl6VKtYBV0yey77tVLo34.6THXqhtGRwg
  /Ea73/FhlK, 02058805Y, Plaça Abril, 85, 96º D, 44824, Vargas de San Pedro, 57431, San Roig, Huesca, ES, 2008-03-30 02:56:12, 2008-
  03-30 02:56:12))
```

UsersTableSeeder.php
```
$date = $faker->dateTimeBetween($startdate,$endDate);
...
\DB::table('users')->insert(array (
            ...
            'created_at'   => $date,
            'updated_at'   => $date

```

Over 750000 users mysq app generate 5 millons of rows with created_at and update_at (datetime) without any problem.

My problem only on this configuration.

On my develop computer with Mysql 5.7.12 not problem.
On my testing raspberrypi with 5.5.44-0+deb8u1 (Raspbian) problem exists.

**Comment by abkrim** [comment]
I checked the problem.

The question is simple. It is a problem concerning the "Daylight Saving Time"

The faker for dates not verified, the "Daylight Saving Time"

By consulting the table for the time change in Spain, http://www.timeanddate.com/time/dst/2011.html and that date is the day indeed 27/03/2011 at 02:00 PM. Therefore, any date is a day that contains a time, between 02:00 and 02:59 will be a failure, because the clock is moved forward from 02:00 to 02:59.

**Comment by fzaninotto** [comment]
Then this is a PHP bug - Faker does nothing special there. 

Please open an issue in the PHP tracker.

**Comment by piwel** [comment]
More probably, it's not a bug, it's a feature :) Just configure your php.ini to the correct timezone for PHP not to get dates outside of your zone.

**Comment by EricBusch** [comment]
What @piwel mentioned fixed it for me but **without** editing my php.ini file. 

With Faker you can set the `timezone` parameter.

```
$faker->dateTimeBetween('-2 years', 'now', 'America/New_York')
```

That let me import 50,000 records with no errors! :)
