### ISSUE TITLE
Unique slug faker has really high memory usage

### ISSUE THREAD

**Issue by shopblocks** [fzaninotto/Faker#921]
```php
ini_set('memory_limit', -1);

function dd()
{
    array_map(function ($x) {
        dump($x);
    }, func_get_args());

    die( 1 );
}

function human_filesize($bytes, $dec = 2)
{
    $size   = array('B', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB');
    $factor = floor((strlen($bytes) - 1) / 3);

    return sprintf("%.{$dec}f", $bytes / pow(1024, $factor)) . @$size[$factor];
}

$mem_before = memory_get_peak_usage(true);

$faker = Faker\Factory::create();

$result = collect(range(1,20))->map(function() use ($faker) {
    return [
        'name' => $faker->unique()->sentence(3),
        'slug' => $faker->unique()->optional()->slug,
    ];
});

$mem_after = memory_get_peak_usage(true);

dd($result, human_filesize($mem_after - $mem_before));
```

Going for just the `name` the memory usage comes out as "0.00B"  and takes `0.018624067306519  seconds` which is odd, and i'm not sure how else to measure this. But the `slug` one being added in, memory goes up to `1.01GB` and takes `3.6474552154541 seconds`.

Removing the `unique` on the `slug` takes it down to `0.011013031005859 seconds` and `0.00B`

**Comment by fzaninotto** [comment]
Surprising results. I guess this is because the slugs are long. Maybe we should store cryptographic hashes instead of full content.

**Comment by fzaninotto** [comment]
what's `collect()`?

**Comment by fzaninotto** [comment]
OK, I get the problem. Each of these statements are fats and consume low memory:

```php
$faker->unique()->sentence(3);
$faker->unique()->slug;
$faker->optional()->slug;
```

What takes a large amount of memory is the combination of `unique()` and `optional()` in that order, which somehow makes sense. I don't know what you expect exaclty, but swapping the order of the two modifiers solves the issue:

```php
// slow as hell, doesn't make sense
$faker->optional()->unique()->slug;
// naturally fast
$faker->unique()->optional()->slug;
```

**Comment by shopblocks** [comment]
collect is github.com/tightenco/collect.

I'll give a better sample code to show the example. 

Also, you are saying that `unique()->optional()` is fast, but it is not. Unless you meant `optional()->unique()`

```php
<?php require_once "../vendor/autoload.php";

function human_filesize($bytes, $dec = 2)
{
    $size   = array('B', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB');
    $factor = floor((strlen($bytes) - 1) / 3);

    return sprintf("%.{$dec}f", $bytes / pow(1024, $factor)) . @$size[$factor];
}

ini_set('memory_limit', -1);

$results = [];

$time_start = microtime(true);
$mem_start = memory_get_peak_usage(true);

$faker = Faker\Factory::create();

for ($i = 0; $i < 21; $i ++) {
    $results[] = [
        'name' => $faker->unique()->sentence(3),
        'slug' => $faker->unique()->optional()->slug, // Very Slow currently - Hence commented out
    ];
}

$mem_end = memory_get_peak_usage(true);
$time_end = microtime(true);

echo '<pre>';

print_r([
    'time' => ($time_end - $time_start),
    'memory' => human_filesize($mem_end - $mem_start),
]);

exit;
```

**Comment by shopblocks** [comment]
Also, doing it the other way around `optional()->unique()` gives me property of non objects.

**Comment by shopblocks** [comment]
@fzaninotto I think this is still a bug, can it be reopened? Your proposed solution throws errors.

**Comment by iguanaman** [comment]
$faker->optional()->unique()->userName;
Triggers a fatal error "Trying to get property of non-object" when optional returns default value null.

$faker->unique()->optional()->userName;
Uses large amounts of memory

This really should be re-opened, unless it's not intended to be able to combine them.
