### ISSUE TITLE
Opposite of Unique

### ISSUE THREAD

**Issue by shopblocks** [fzaninotto/Faker#923]
Is it possible to get a function that gives a value that has already been chosen. The opposite of unique()

The reason being, that for our testing API we generate random internal UUID's that have to be unique, but we also want to have a relationship setup with parent and children on other rows, which have to match a UUID that already exists.

**Comment by softius** [comment]
If you are populating entries using ORM / ODM, Faker will relate the populated Child entity to one of the populated Parent entities.

**Comment by shopblocks** [comment]
The use case here is for generating a JSON file for testing an API. There is no ORM or ODM attached, there are no entities, only what is currently in memory to generate testing files.

The unique() array is already there, so choosing $faker->exists()->uuid would be a good addition.

**Comment by sprunka** [comment]
I like this idea. I am willing to look into it. (Forking in 3..2..

**Comment by ikwattro** [comment]
I like the idea as well, however couldn't you just keep an array of the previously generated uuids and pass it as argument to `randomElement()`?

**Comment by softius** [comment]
AFAIK unique() holds a copy of all generated values per provider, in this case UUID. This could be used to implement exists(). However, resetting the unique modifier will also provide an empty dataset for exists... 

Nevertheless, I like the idea suggested by @ikwattro (as a good practice) since it leaves the control to developer, especially in cases where we have many sets of UUIDs. Perhaps, it can be added as a note in README.

**Comment by ikwattro** [comment]
@softius Yes, actually the array keys are holding the values (I did this change for performance reasons).

I would however investigate the feasibility or the popularity this feature can have, there are use cases where the user don't have control, like in my principal usage of faker here http://graphgen.graphaware.com/#/ where users are actually my app users and this feature could be triggered with a single character.

**Comment by shopblocks** [comment]
Leaving it to the developer as well makes the code less clean than it being a natively supported feature. having to maintain your own array (or array of arrays), when there is one already storing the exact same data is not a clean solution.

**Comment by fzaninotto** [comment]
This won't be done in the core, feel free to keep track of the already generated data on your side to create data that is relevant for your use case.
