### ISSUE TITLE
Get data from random locale

### ISSUE THREAD

**Issue by magnetik** [fzaninotto/Faker#940]
Hi,

I'd like to populate my fixtures with data as if there were people from different countries.

I don't see any clean way of getting a generator for a random locale? (Other than for instance getting a random locale with Faker and check if it exists, but it won't exists for most).

Thanks

**Comment by fzaninotto** [comment]
That's right, there is no easy way to do it. 

The easiest way is parsing the source for existing locale directories. But that won't be enough, since some locales don't implement all the formatters. 

Your solution, based on a `try/catch`, may be better.
