### ISSUE TITLE
Timezone conversion issue

### ISSUE THREAD

**Issue by thealonekhan** [fzaninotto/Faker#945]
Hi, i have an issue while converting a giving date or time for a specific **timezone**, using faker **DateTime**.
The issue is: it always convert the date for a given timezone, exact one hour prior.
This is my code:

`$date = new \DateTime($start_time, new \DateTimeZone('GMT')); //start_time will be db pulled time $date->setTimezone(new \DateTimeZone('EDT'));
 $start_time = $date->format('H:i');` 

Now the $start_time will be one hour earlier than given timezone **Eastern Daylight Time(EDT)**.
Any suggestion?

**Comment by fzaninotto** [comment]
fixed by #1231
