### ISSUE TITLE
imageUrl lorempixel is down

### ISSUE THREAD

**Issue by linxlad** [fzaninotto/Faker#957]
Is there any chance to introduce a backup when http://lorempixel.com/ is down?

**Comment by Newman101** [comment]
Again? We could always make an additional check to source code where alternative (such as http://placehold.it/) is used if the check fails.

**Comment by fzaninotto** [comment]
On the contrary, I consider removing the image provider altogether, because I don't want to depend on a third-party with no SLA.

**Comment by okj579** [comment]
I think a disclaimer to that effect would be sufficient. I still find the
provider very useful.

Though an external provider (like EmanueleMinotto/PlaceholdItProvider)
might be a better place for it?

**Comment by damiandennis** [comment]
lorempixel seem to be always down at the moment. it is useful though please don't remove it.

**Comment by atwright147** [comment]
How about letting the user select where the images come from rather than making the source an internal variable?

**Comment by ethanclevenger91** [comment]
If you're looking for an immediate solution, I haven't run into this with FillMurray, either. It offers less flexibility, but you can replace the following function in `Providers/Image.php` (obviously this will be lost if you update/start up somewhere else):

```
public static function imageUrl($width = 640, $height = 480, $category = null, $randomize = true, $word = null, $gray = false)
    {
        // $baseUrl = "http://lorempixel.com/";
        $baseUrl = "http://www.fillmurray.com/";
        // $url = "{$width}/{$height}/";
        $url = "{$width}/{$height}";

        // if ($gray) {
        //     $url = "gray/" . $url;
        // }

        // if ($category) {
        //     if (!in_array($category, static::$categories)) {
        //         throw new \InvalidArgumentException(sprintf('Unknown image category "%s"', $category));
        //     }
        //     $url .= "{$category}/";
        //     if ($word) {
        //         $url .= "{$word}/";
        //     }
        // }

        // if ($randomize) {
        //     $url .= '?' . static::randomNumber(5, true);
        // }

        return $baseUrl . $url;
    }
```

**Comment by gulaandrij** [comment]
#963 fix this issue

**Comment by reno1979** [comment]
```public function robohash($name='robot',$width=200,$height=200,$background=FALSE,$secure=TRUE){

                    $baseUrl = ($secure) ? "https://robohash.org/" : "http://robohash.org";
                    $url = "{$name}.png?size={$width}x{$height}";
                    
                    if ($background) {
                        $url .= "&bgset=bg" . $this->randomDigit;
                    }
                   
                    return $baseUrl . $url;

                }
```

**Comment by Kaijiro** [comment]
Maybe we could consider to choose in a configuration or something else like that the image provider that the user wants to have, so when one is down he can swap to another.

**Comment by ethanclevenger91** [comment]
What about using something like [Intervention Image](http://image.intervention.io/) to [make a fake image](http://image.intervention.io/api/canvas)? It'd certainly be less interesting, but it'd be reliable.

**Comment by fzaninotto** [comment]
Because it adds a dependency on GD or ImageMagick.

**Comment by ethanclevenger91** [comment]
So I guess the question is, do you build in an image generator guaranteed to work and document its dependencies or build in one that fails silently and document that the end user's code should somehow account for that? I certainly don't have the right answer, but the shortcomings _definitely_ need documented.

Is there any data on how many people are running PHP w/o at least GD? I guess it'd be hard to tell on dev environments.

**Comment by Newman101** [comment]
As far as I know, PHP has internal features to build images. At least with PNG and JPEG. Not so sure with other formats though. 

http://php.net/manual/en/function.imagejpeg.php
http://php.net/manual/en/image.examples-png.php

**Comment by Darival** [comment]
maybe using another service like https://unsplash.com/ wich also has an api, and has better looking images.

**Comment by ethanclevenger91** [comment]
@Darival I like that idea, though the Unsplash API does require an application. Does everything get routed through one application deployed with Faker, or does that need to be configured by the end user?

**Comment by Darival** [comment]
@ethanclevenger91 it does require app registration by the end user. This is better as an alternative option than as a replacement to lorempixel.

**Comment by sinkcup** [comment]
Today https://lorempixel.com down again. I write a patch to switch to https://fakeimg.pl

```faker_image_url.patch
--- vendor/fzaninotto/faker/src/Faker/Provider/Image.php	2017-08-16 00:48:10.000000000 +0800
+++ Image.php	2018-01-10 15:25:31.384804140 +0800
@@ -30,22 +30,8 @@
      */
     public static function imageUrl($width = 640, $height = 480, $category = null, $randomize = true, $word = null, $gray = false)
     {
-        $baseUrl = "https://lorempixel.com/";
-        $url = "{$width}/{$height}/";
-
-        if ($gray) {
-            $url = "gray/" . $url;
-        }
-
-        if ($category) {
-            if (!in_array($category, static::$categories)) {
-                throw new \InvalidArgumentException(sprintf('Unknown image category "%s"', $category));
-            }
-            $url .= "{$category}/";
-            if ($word) {
-                $url .= "{$word}/";
-            }
-        }
+        $baseUrl = "https://fakeimg.pl/";
+        $url = "{$width}x{$height}/";
 
         if ($randomize) {
             $url .= '?' . static::randomNumber(5, true);
```

```composer.json
    "scripts": {
        "post-install-cmd": [
            ...
            "patch -N -p0 < faker_image_url.patch || echo 'patch failed'"
        ]
    }
```

**Comment by daraul** [comment]
Lorempixel seems to be down again, today. Any updates on an alternative?

**Comment by tkrause** [comment]
The JS version of Faker although unrelated is using https://loremflickr.com/.

It seems like the best option would be to have a sane default but allow it to be configurable somehow.

**Comment by fzaninotto** [comment]
Again, we won't fix this problem in Faker, but rather remove the Image formatter altogether. 

Feel free to work on a standalone formatter for loremflickr, which seems to be a more reliable source.

**Comment by ChangePlaces** [comment]
Please don't remove image support from faker - they are an essential part of web development.

It's as simple to just implement a random placeholder image with a solid background colour and basic text.

**Comment by ultreson** [comment]
if people want an alternative to lorem pixel, i made a small fix to pass a different image generator as an argument, not incredibly elegant but it works since most of the  alternatives have the same formatting
https://github.com/ultreson/Faker/tree/picture-providers

**Comment by spacedog4** [comment]
it'll be nice if you could pass the param to the baseUrl, I created a pull request about it #1542

**Comment by oliversarfas** [comment]
Lorempixel has been down for 2 days now

The package even dies silently, would be nice if it flagged the problem to the user, or allowed for multiple providers.

**Comment by spacedog4** [comment]
@oliversarfas I created a pull request for multiple providers #1542

**Comment by jonty-comp** [comment]
It took me 20 minutes to figure out why my image tests were returning boolean false...granted, it's a simple check but I didn't know where to start looking!

+1 for throwing an error when failing to pull an image, or indeed, for getting rid of the lorem pixel dependency altogether.

**Comment by falnyr** [comment]
@fzaninotto So you don't want any other third party image providers nor you want to generate the image directly in PHP? Or am I mistaken? What is the goal here?

**Comment by fzaninotto** [comment]
Right. the goal is to have in Faker core only stable and non-third-party dependent formatters. You can publish and share any formatter that doesn't fit these two criterions as third-party packages.

**Comment by marcosdipaolo** [comment]
So in the end no solution for now right?

**Comment by standaniels** [comment]
You could locally create images instead, for example by using [this image generator](https://github.com/standaniels/image-generator). I've created that package so I can generate images instead of using faker to download them.

**Comment by mindplay-dk** [comment]
If anybody else is looking for fake profile photos, try [thispersondoesnotexist.com](https://thispersondoesnotexist.com/) - it's pretty great! I just downloaded 100 or so plausible-looking profile images, named them `f` for female, `m` for male, followed by a number, and I can use faker to randomly pick from those 👍

**Comment by alnassre** [comment]
I relpaced it with:

`    
public static function imageUrl($width = 640, $height = 480, $category = null, $randomize = true, $word = null, $gray = false)
    {
        if ($randomize) {
            $randomize_number =  static::randomNumber(3, true);
        }
        $baseUrl = "https://i.picsum.photos/id/" . $randomize_number . "/";
        $url = "{$width}/{$height}.jpg";
        return $baseUrl . $url;
    }
`
