### ISSUE TITLE
1.6.0 should be marked as latest release

### ISSUE THREAD

**Issue by vlakoff** [fzaninotto/Faker#974]
When I look at https://github.com/fzaninotto/Faker/releases, 1.5.0 is still marked as the latest release.

This page also misses the [1.6.0 changelog](https://github.com/fzaninotto/Faker/blob/master/CHANGELOG.md).

**Comment by fzaninotto** [comment]
Fixed: https://github.com/fzaninotto/Faker/releases/tag/v1.6.0

Thanks for the report
