### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by D0Gmatist** [fzaninotto/Faker#976]
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'text() can only generate text of at least 5 characters' in E:\OpenServer\domains\magazinx.by\f\Faker\Provider\Lorem.php:167 Stack trace: #0 [internal function]: Faker\Provider\Lorem->text(1) #1 E:\OpenServer\domains\magazinx.by\f\Faker\Generator.php(197): call_user_func_array(Array, Array) #2 E:\OpenServer\domains\magazinx.by\f\Faker\Generator.php(248): Faker\Generator->format('text', Array) #3 E:\OpenServer\domains\magazinx.by\f\i.php(125): Faker\Generator->__call('text', Array) #4 E:\OpenServer\domains\magazinx.by\f\i.php(125): Faker\Generator->text(1) #5 {main} thrown in E:\OpenServer\domains\magazinx.by\f\Faker\Provider\Lorem.php on line 167

**Comment by fzaninotto** [comment]
You should read what you've pasted, it contains the explanation of the problem, which is on your side. 

Besides, pasting a stack trace without further context is not the best way to get help.

**Comment by D0Gmatist** [comment]
made 25 requests for a total of 400 entries ... 10000
Error jumped 6-7 times
`$ar_views = trim( $db->safesql( $faker->text( $faker->numberBetween( $min = 0, $max = 10000 ) ) ) );`

**Comment by fzaninotto** [comment]
then change the `$min` value to 5.

**Comment by D0Gmatist** [comment]
Thank you
