### ISSUE TITLE
Upgrading PHPUnit to 5.x

### ISSUE THREAD

**Issue by the-noob** [fzaninotto/Faker#987]
Anyone interested ? I'm willing to pick up the tests upgrade.

**Comment by fzaninotto** [comment]
Not possible: the PHP version compatibility doesn't match Faker's (PHP 5.3.3)

https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-5.0.0#dropping-support-for-php-53-php-54-and-php-55
