### ISSUE TITLE
$faker->unique(true)->numberBetween(1,20) returns duplicate data

### ISSUE THREAD

**Issue by laxx** [fzaninotto/Faker#990]
So I have to use unique on 3 different seeder classes but I noticed the OverflowException thrown if just do $faker->unique(). So as per the doc, i did $faker->unique(true)->numberBetween(1,20) and the result was duplicated numbers. Can someone explain how I can reset the unique() and still receive unique data.

**Comment by fzaninotto** [comment]
`unique` keeps an internal list of already generated items. If it can't generate a new item, it means that you want to generate more items than there are in the dataset. 

So if `unique()` throws an `OverflowExeption`, you can't have more unique data. 

The `true` option resets the internal list. That means that it allows to generate a new series of unique items, but they are not guaranteed to be unique in comparison to previous series.

**Comment by saurabhk06** [comment]
So what is the solution??

**Comment by boyet007** [comment]
> `unique` keeps an internal list of already generated items. If it can't generate a new item, it means that you want to generate more items than there are in the dataset.
> 
> So if `unique()` throws an `OverflowExeption`, you can't have more unique data.
> 
> The `true` option resets the internal list. That means that it allows to generate a new series of unique items, but they are not guaranteed to be unique in comparison to previous series.

I hope the development of unique faker is continue because needed for testing customize id .. thank you
